BASEDIR=$( pwd )

cd $BASEDIR/correlation_elutions


#Data freeze 9/19/2016

echo 3 wheat
python $BASEDIR/scripts/combine_elution_group.py traes virNOG wgSEC1_raw_wide_elution_traes_virNOG.csv wheatgermIEX_raw_wide_elution_traes_virNOG.csv WheatGermSEC_07-2015_raw_wide_elution_traes_virNOG.csv wgIEF_raw_wide_elution_traes_virNOG.csv

echo 2 selaginella
python $BASEDIR/scripts/combine_elution_group.py selml virNOG OP_SelaginellaSEC_20160309_raw_wide_elution_selml_virNOG.csv selaginella_WWC_raw_wide_elution_selml_virNOG.csv


echo 4 arath
python $BASEDIR/scripts/combine_elution_group.py arath virNOG At_Col_0_indark_201505_raw_wide_elution_arath_virNOG.csv At_Col_0_indark_fraction_201504_raw_wide_elution_arath_virNOG.csv At_Col_0_leaf_fraction_2014_raw_wide_elution_arath_virNOG.csv At_Col_0_leaf_fraction_2015_raw_wide_elution_arath_virNOG.csv


echo orysj
echo 2 orysj
python $BASEDIR/scripts/combine_elution_group.py orysj virNOG RiceL_IEX_raw_wide_elution_orysj_virNOG.csv Rice_201505_uniprot_raw_wide_elution_orysj_virNOG.csv



echo broccoli virNOG
echo 3 braol
python $BASEDIR/scripts/combine_elution_group.py braol virNOG Broccolinuclei_6-2016_raw_wide_elution_braol_virNOG.csv BroccoliNE_WWC_raw_wide_elution_braol_virNOG.csv Broccolinuclei_IEF_9-2016_raw_wide_elution_braol_virNOG.csv


echo chlamydomonas
echo 2 chlre
python $BASEDIR/scripts/combine_elution_group.py chlre virNOG Chlamydomonas_WWC_9-2016_raw_wide_elution_chlre_virNOG.csv OP_Chlamydomonas_SEC_raw_wide_elution_chlre_virNOG.csv



echo monocot
echo 4 traes 2 orysj
python $BASEDIR/scripts/combine_elution_group.py monocot virNOG wgSEC1_raw_wide_elution_traes_virNOG.csv wheatgermIEX_raw_wide_elution_traes_virNOG.csv WheatGermSEC_07-2015_raw_wide_elution_traes_virNOG.csv  wgIEF_raw_wide_elution_traes_virNOG.csv RiceL_IEX_raw_wide_elution_orysj_virNOG.csv Rice_201505_uniprot_raw_wide_elution_orysj_virNOG.csv


echo eudicot
echo 4 arath 3 braol
python $BASEDIR/scripts/combine_elution_group.py eudicot virNOG At_Col_0_indark_201505_raw_wide_elution_arath_virNOG.csv At_Col_0_indark_fraction_201504_raw_wide_elution_arath_virNOG.csv At_Col_0_leaf_fraction_2014_raw_wide_elution_arath_virNOG.csv At_Col_0_leaf_fraction_2015_raw_wide_elution_arath_virNOG.csv Broccolinuclei_6-2016_raw_wide_elution_braol_virNOG.csv BroccoliNE_WWC_raw_wide_elution_braol_virNOG.csv Broccolinuclei_IEF_9-2016_raw_wide_elution_braol_virNOG.csv



echo angiosperm
echo 4 traes 2 orysj  4 arath 3 braol

python $BASEDIR/scripts/combine_elution_group.py angiosperm virNOG At_Col_0_indark_201505_raw_wide_elution_arath_virNOG.csv At_Col_0_indark_fraction_201504_raw_wide_elution_arath_virNOG.csv At_Col_0_leaf_fraction_2014_raw_wide_elution_arath_virNOG.csv At_Col_0_leaf_fraction_2015_raw_wide_elution_arath_virNOG.csv wgSEC1_raw_wide_elution_traes_virNOG.csv wheatgermIEX_raw_wide_elution_traes_virNOG.csv WheatGermSEC_07-2015_raw_wide_elution_traes_virNOG.csv  wgIEF_raw_wide_elution_traes_virNOG.csv RiceL_IEX_raw_wide_elution_orysj_virNOG.csv Rice_201505_uniprot_raw_wide_elution_orysj_virNOG.csv Broccolinuclei_6-2016_raw_wide_elution_braol_virNOG.csv BroccoliNE_WWC_raw_wide_elution_braol_virNOG.csv Broccolinuclei_IEF_9-2016_raw_wide_elution_braol_virNOG.csv


echo vascular
echo 4 traes 2 orysj  4 arath 3 braol 2 selml
python $BASEDIR/scripts/combine_elution_group.py vascular virNOG At_Col_0_indark_201505_raw_wide_elution_arath_virNOG.csv At_Col_0_indark_fraction_201504_raw_wide_elution_arath_virNOG.csv At_Col_0_leaf_fraction_2014_raw_wide_elution_arath_virNOG.csv At_Col_0_leaf_fraction_2015_raw_wide_elution_arath_virNOG.csv wgSEC1_raw_wide_elution_traes_virNOG.csv wheatgermIEX_raw_wide_elution_traes_virNOG.csv WheatGermSEC_07-2015_raw_wide_elution_traes_virNOG.csv  wgIEF_raw_wide_elution_traes_virNOG.csv RiceL_IEX_raw_wide_elution_orysj_virNOG.csv Rice_201505_uniprot_raw_wide_elution_orysj_virNOG.csv Broccolinuclei_6-2016_raw_wide_elution_braol_virNOG.csv BroccoliNE_WWC_raw_wide_elution_braol_virNOG.csv Broccolinuclei_IEF_9-2016_raw_wide_elution_braol_virNOG.csv OP_SelaginellaSEC_20160309_raw_wide_elution_selml_virNOG.csv selaginella_WWC_raw_wide_elution_selml_virNOG.csv 

echo plants
echo 4 traes 2 orysj  4 arath 3 braol 2 selml 2 chlre
python $BASEDIR/scripts/combine_elution_group.py plants virNOG At_Col_0_indark_201505_raw_wide_elution_arath_virNOG.csv At_Col_0_indark_fraction_201504_raw_wide_elution_arath_virNOG.csv At_Col_0_leaf_fraction_2014_raw_wide_elution_arath_virNOG.csv At_Col_0_leaf_fraction_2015_raw_wide_elution_arath_virNOG.csv wgSEC1_raw_wide_elution_traes_virNOG.csv wheatgermIEX_raw_wide_elution_traes_virNOG.csv WheatGermSEC_07-2015_raw_wide_elution_traes_virNOG.csv  wgIEF_raw_wide_elution_traes_virNOG.csv RiceL_IEX_raw_wide_elution_orysj_virNOG.csv Rice_201505_uniprot_raw_wide_elution_orysj_virNOG.csv Broccolinuclei_6-2016_raw_wide_elution_braol_virNOG.csv BroccoliNE_WWC_raw_wide_elution_braol_virNOG.csv Broccolinuclei_IEF_9-2016_raw_wide_elution_braol_virNOG.csv OP_SelaginellaSEC_20160309_raw_wide_elution_selml_virNOG.csv selaginella_WWC_raw_wide_elution_selml_virNOG.csv Chlamydomonas_WWC_9-2016_raw_wide_elution_chlre_virNOG.csv OP_Chlamydomonas_SEC_raw_wide_elution_chlre_virNOG.csv





#Combine rice experiments
#echo "orysj"
#python $BASEDIR/scripts/combine_elution_group.py orysj virNOG RiceL_IEX_raw_wide_elution_orysj_virNOG.csv Rice_201505_uniprot_raw_wide_elution_orysj_virNOG.csv


#
#Combine all experiments
#echo "arathtraesorysjbraolselml"
#python $BASEDIR/scripts/combine_elution_group.py atobs virNOG At_Col_0_indark_201505_raw_wide_elution_arath_virNOG.csv At_Col_0_indark_fraction_201504_raw_wide_elution_arath_virNOG.csv At_Col_0_leaf_fraction_2014_raw_wide_elution_arath_virNOG.csv At_Col_0_leaf_fraction_2015_raw_wide_elution_arath_virNOG.csv wgSEC1_raw_wide_elution_traes_virNOG.csv wheatgermIEX_raw_wide_elution_traes_virNOG.csv WheatGermSEC_07-2015_raw_wide_elution_traes_virNOG.csv  wgIEF_raw_wide_elution_traes_virNOG.csv RiceL_IEX_raw_wide_elution_orysj_virNOG.csv Rice_201505_uniprot_raw_wide_elution_orysj_virNOG.csv Broccolinuclei_6-2016_raw_wide_elution_braol_virNOG.csv BroccoliNE_WWC_raw_wide_elution_braol_virNOG.csv OP_SelaginellaSEC_20160309_raw_wide_elution_selml_virNOG.csv selaginella_WWC_raw_wide_elution_selml_virNOG.csv 


#This needs to be run when the traes experiments process for virNOGs
#echo "arathtraesorysjbraolselml"
#python $BASEDIR/scripts/combine_elution_wide.py arathtraesorysjbraolselml virNOG At_Col_0_indark_201505_raw_wide_elution_arath_virNOG.csv At_Col_0_indark_fraction_201504_raw_wide_elution_arath_virNOG.csv At_Col_0_leaf_fraction_2014_raw_wide_elution_arath_virNOG.csv At_Col_0_leaf_fraction_2015_raw_wide_elution_arath_virNOG.csv wgSEC1_raw_wide_elution_traes_virNOG.csv wheatgermIEX_raw_wide_elution_traes_virNOG.csv WheatGermSEC_07-2015_raw_wide_elution_traes_virNOG.csv RiceL_IEX_raw_wide_elution_orysj_virNOG.csv Rice_201505_uniprot_raw_wide_elution_orysj_virNOG.csv Broccolinuclei_6-2016_raw_wide_elution_braol_virNOG.csv OP_SelaginellaSEC_20160309_raw_wide_elution_selml_virNOG.csv





#echo "arath virNOG concatenation"
#python $BASEDIR/scripts/combine_elution_virNOG.py arath virNOG At_Col_0_indark_201505_raw_wide_elution_arath_virNOG.csv At_Col_0_indark_fraction_201504_raw_wide_elution_arath_virNOG.csv At_Col_0_leaf_fraction_2014_raw_wide_elution_arath_virNOG.csv At_Col_0_leaf_fraction_2015_raw_wide_elution_arath_virNOG.cs

#echo "wheat virNOG concatenation"
#python $BASEDIR/scripts/combine_elution_group.py traes virNOG wgSEC1_raw_wide_elution_traes_virNOG.csv wheatgermIEX_raw_wide_elution_traes_virNOG.csv WheatGermSEC_07-2015_raw_wide_elution_traes_virNOG.csv wgIEF_raw_wide_elution_traes_virNOG.csv

#echo "selaginella virNOG concatenation"
#python $BASEDIR/scripts/combine_elution_group.py selml virNOG OP_SelaginellaSEC_20160309_raw_wide_elution_selml_virNOG.csv selaginella_WWC_raw_wide_elution_selml_virNOG.csv
#pwd
#cd arath/
#echo "arath virNOG concatenation"
#python $BASEDIR/scripts/combine_elution_multirow.py arathmultirow_virNOG_concat.csv At_Col_0_indark_201505_multirow_wide_elution_arath_virNOG.csv At_Col_0_indark_fraction_201504_multirow_wide_elution_arath_virNOG.csv At_Col_0_leaf_fraction_2014_multirow_wide_elution_arath_virNOG.csv At_Col_0_leaf_fraction_2015_multirow_wide_elution_arath_virNOG.csv

#cd ../traes

#echo "wheat virNOG concatenation"
#python $BASEDIR/scripts/combine_elution_multirow.py traesmultirow_virNOG_concat.csv wgSEC1_multirow_wide_elution_traes_virNOG.csv wheatgermIEX_multirow_wide_elution_traes_virNOG.csv WheatGermSEC_07-2015_multirow_wide_elution_traes_virNOG.csv


