BASEDIR=$( pwd )

cd $BASEDIR/correlation_elutions


#Data freeze 9/19/2016

echo 3 wheat
python $BASEDIR/scripts/combine_elution_group.py traes euNOG wgSEC1_raw_wide_elution_traes_euNOG.csv wheatgermIEX_raw_wide_elution_traes_euNOG.csv WheatGermSEC_07-2015_raw_wide_elution_traes_euNOG.csv wgIEF_raw_wide_elution_traes_euNOG.csv

echo 2 selaginella
python $BASEDIR/scripts/combine_elution_group.py selml euNOG OP_SelaginellaSEC_20160309_raw_wide_elution_selml_euNOG.csv selaginella_WWC_raw_wide_elution_selml_euNOG.csv


echo 4 arath
python $BASEDIR/scripts/combine_elution_group.py arath euNOG At_Col_0_indark_201505_raw_wide_elution_arath_euNOG.csv At_Col_0_indark_fraction_201504_raw_wide_elution_arath_euNOG.csv At_Col_0_leaf_fraction_2014_raw_wide_elution_arath_euNOG.csv At_Col_0_leaf_fraction_2015_raw_wide_elution_arath_euNOG.csv


echo orysj
echo 2 orysj
python $BASEDIR/scripts/combine_elution_group.py orysj euNOG RiceL_IEX_raw_wide_elution_orysj_euNOG.csv Rice_201505_uniprot_raw_wide_elution_orysj_euNOG.csv



echo broccoli euNOG
echo 3 braol
python $BASEDIR/scripts/combine_elution_group.py braol euNOG Broccolinuclei_6-2016_raw_wide_elution_braol_euNOG.csv BroccoliNE_WWC_raw_wide_elution_braol_euNOG.csv Broccolinuclei_IEF_9-2016_raw_wide_elution_braol_euNOG.csv


echo chlamydomonas
echo 2 chlre
python $BASEDIR/scripts/combine_elution_group.py chlre euNOG Chlamydomonas_WWC_9-2016_raw_wide_elution_chlre_euNOG.csv OP_Chlamydomonas_SEC_raw_wide_elution_chlre_euNOG.csv



echo monocot
echo 4 traes 2 orysj
python $BASEDIR/scripts/combine_elution_group.py monocot euNOG wgSEC1_raw_wide_elution_traes_euNOG.csv wheatgermIEX_raw_wide_elution_traes_euNOG.csv WheatGermSEC_07-2015_raw_wide_elution_traes_euNOG.csv  wgIEF_raw_wide_elution_traes_euNOG.csv RiceL_IEX_raw_wide_elution_orysj_euNOG.csv Rice_201505_uniprot_raw_wide_elution_orysj_euNOG.csv


echo eudicot
echo 4 arath 3 braol
python $BASEDIR/scripts/combine_elution_group.py eudicot euNOG At_Col_0_indark_201505_raw_wide_elution_arath_euNOG.csv At_Col_0_indark_fraction_201504_raw_wide_elution_arath_euNOG.csv At_Col_0_leaf_fraction_2014_raw_wide_elution_arath_euNOG.csv At_Col_0_leaf_fraction_2015_raw_wide_elution_arath_euNOG.csv Broccolinuclei_6-2016_raw_wide_elution_braol_euNOG.csv BroccoliNE_WWC_raw_wide_elution_braol_euNOG.csv Broccolinuclei_IEF_9-2016_raw_wide_elution_braol_euNOG.csv



echo angiosperm
echo 4 traes 2 orysj  4 arath 3 braol

python $BASEDIR/scripts/combine_elution_group.py angiosperm euNOG At_Col_0_indark_201505_raw_wide_elution_arath_euNOG.csv At_Col_0_indark_fraction_201504_raw_wide_elution_arath_euNOG.csv At_Col_0_leaf_fraction_2014_raw_wide_elution_arath_euNOG.csv At_Col_0_leaf_fraction_2015_raw_wide_elution_arath_euNOG.csv wgSEC1_raw_wide_elution_traes_euNOG.csv wheatgermIEX_raw_wide_elution_traes_euNOG.csv WheatGermSEC_07-2015_raw_wide_elution_traes_euNOG.csv  wgIEF_raw_wide_elution_traes_euNOG.csv RiceL_IEX_raw_wide_elution_orysj_euNOG.csv Rice_201505_uniprot_raw_wide_elution_orysj_euNOG.csv Broccolinuclei_6-2016_raw_wide_elution_braol_euNOG.csv BroccoliNE_WWC_raw_wide_elution_braol_euNOG.csv Broccolinuclei_IEF_9-2016_raw_wide_elution_braol_euNOG.csv


echo vascular
echo 4 traes 2 orysj  4 arath 3 braol 2 selml
python $BASEDIR/scripts/combine_elution_group.py vascular euNOG At_Col_0_indark_201505_raw_wide_elution_arath_euNOG.csv At_Col_0_indark_fraction_201504_raw_wide_elution_arath_euNOG.csv At_Col_0_leaf_fraction_2014_raw_wide_elution_arath_euNOG.csv At_Col_0_leaf_fraction_2015_raw_wide_elution_arath_euNOG.csv wgSEC1_raw_wide_elution_traes_euNOG.csv wheatgermIEX_raw_wide_elution_traes_euNOG.csv WheatGermSEC_07-2015_raw_wide_elution_traes_euNOG.csv  wgIEF_raw_wide_elution_traes_euNOG.csv RiceL_IEX_raw_wide_elution_orysj_euNOG.csv Rice_201505_uniprot_raw_wide_elution_orysj_euNOG.csv Broccolinuclei_6-2016_raw_wide_elution_braol_euNOG.csv BroccoliNE_WWC_raw_wide_elution_braol_euNOG.csv Broccolinuclei_IEF_9-2016_raw_wide_elution_braol_euNOG.csv OP_SelaginellaSEC_20160309_raw_wide_elution_selml_euNOG.csv selaginella_WWC_raw_wide_elution_selml_euNOG.csv 

echo plants
echo 4 traes 2 orysj  4 arath 3 braol 2 selml 2 chlre
python $BASEDIR/scripts/combine_elution_group.py plants euNOG At_Col_0_indark_201505_raw_wide_elution_arath_euNOG.csv At_Col_0_indark_fraction_201504_raw_wide_elution_arath_euNOG.csv At_Col_0_leaf_fraction_2014_raw_wide_elution_arath_euNOG.csv At_Col_0_leaf_fraction_2015_raw_wide_elution_arath_euNOG.csv wgSEC1_raw_wide_elution_traes_euNOG.csv wheatgermIEX_raw_wide_elution_traes_euNOG.csv WheatGermSEC_07-2015_raw_wide_elution_traes_euNOG.csv  wgIEF_raw_wide_elution_traes_euNOG.csv RiceL_IEX_raw_wide_elution_orysj_euNOG.csv Rice_201505_uniprot_raw_wide_elution_orysj_euNOG.csv Broccolinuclei_6-2016_raw_wide_elution_braol_euNOG.csv BroccoliNE_WWC_raw_wide_elution_braol_euNOG.csv Broccolinuclei_IEF_9-2016_raw_wide_elution_braol_euNOG.csv OP_SelaginellaSEC_20160309_raw_wide_elution_selml_euNOG.csv selaginella_WWC_raw_wide_elution_selml_euNOG.csv Chlamydomonas_WWC_9-2016_raw_wide_elution_chlre_euNOG.csv OP_Chlamydomonas_SEC_raw_wide_elution_chlre_euNOG.csv





#Combine rice experiments
#echo "orysj"
#python $BASEDIR/scripts/combine_elution_group.py orysj euNOG RiceL_IEX_raw_wide_elution_orysj_euNOG.csv Rice_201505_uniprot_raw_wide_elution_orysj_euNOG.csv


#
#Combine all experiments
#echo "arathtraesorysjbraolselml"
#python $BASEDIR/scripts/combine_elution_group.py atobs euNOG At_Col_0_indark_201505_raw_wide_elution_arath_euNOG.csv At_Col_0_indark_fraction_201504_raw_wide_elution_arath_euNOG.csv At_Col_0_leaf_fraction_2014_raw_wide_elution_arath_euNOG.csv At_Col_0_leaf_fraction_2015_raw_wide_elution_arath_euNOG.csv wgSEC1_raw_wide_elution_traes_euNOG.csv wheatgermIEX_raw_wide_elution_traes_euNOG.csv WheatGermSEC_07-2015_raw_wide_elution_traes_euNOG.csv  wgIEF_raw_wide_elution_traes_euNOG.csv RiceL_IEX_raw_wide_elution_orysj_euNOG.csv Rice_201505_uniprot_raw_wide_elution_orysj_euNOG.csv Broccolinuclei_6-2016_raw_wide_elution_braol_euNOG.csv BroccoliNE_WWC_raw_wide_elution_braol_euNOG.csv OP_SelaginellaSEC_20160309_raw_wide_elution_selml_euNOG.csv selaginella_WWC_raw_wide_elution_selml_euNOG.csv 


#This needs to be run when the traes experiments process for virNOGs
#echo "arathtraesorysjbraolselml"
#python $BASEDIR/scripts/combine_elution_wide.py arathtraesorysjbraolselml virNOG At_Col_0_indark_201505_raw_wide_elution_arath_virNOG.csv At_Col_0_indark_fraction_201504_raw_wide_elution_arath_virNOG.csv At_Col_0_leaf_fraction_2014_raw_wide_elution_arath_virNOG.csv At_Col_0_leaf_fraction_2015_raw_wide_elution_arath_virNOG.csv wgSEC1_raw_wide_elution_traes_virNOG.csv wheatgermIEX_raw_wide_elution_traes_virNOG.csv WheatGermSEC_07-2015_raw_wide_elution_traes_virNOG.csv RiceL_IEX_raw_wide_elution_orysj_virNOG.csv Rice_201505_uniprot_raw_wide_elution_orysj_virNOG.csv Broccolinuclei_6-2016_raw_wide_elution_braol_virNOG.csv OP_SelaginellaSEC_20160309_raw_wide_elution_selml_virNOG.csv





#echo "arath euNOG concatenation"
#python $BASEDIR/scripts/combine_elution_euNOG.py arath euNOG At_Col_0_indark_201505_raw_wide_elution_arath_euNOG.csv At_Col_0_indark_fraction_201504_raw_wide_elution_arath_euNOG.csv At_Col_0_leaf_fraction_2014_raw_wide_elution_arath_euNOG.csv At_Col_0_leaf_fraction_2015_raw_wide_elution_arath_euNOG.cs

#echo "wheat euNOG concatenation"
#python $BASEDIR/scripts/combine_elution_group.py traes euNOG wgSEC1_raw_wide_elution_traes_euNOG.csv wheatgermIEX_raw_wide_elution_traes_euNOG.csv WheatGermSEC_07-2015_raw_wide_elution_traes_euNOG.csv wgIEF_raw_wide_elution_traes_euNOG.csv

#echo "selaginella euNOG concatenation"
#python $BASEDIR/scripts/combine_elution_group.py selml euNOG OP_SelaginellaSEC_20160309_raw_wide_elution_selml_euNOG.csv selaginella_WWC_raw_wide_elution_selml_euNOG.csv
#pwd
#cd arath/
#echo "arath euNOG concatenation"
#python $BASEDIR/scripts/combine_elution_multirow.py arathmultirow_euNOG_concat.csv At_Col_0_indark_201505_multirow_wide_elution_arath_euNOG.csv At_Col_0_indark_fraction_201504_multirow_wide_elution_arath_euNOG.csv At_Col_0_leaf_fraction_2014_multirow_wide_elution_arath_euNOG.csv At_Col_0_leaf_fraction_2015_multirow_wide_elution_arath_euNOG.csv

#cd ../traes

#echo "wheat euNOG concatenation"
#python $BASEDIR/scripts/combine_elution_multirow.py traesmultirow_euNOG_concat.csv wgSEC1_multirow_wide_elution_traes_euNOG.csv wheatgermIEX_multirow_wide_elution_traes_euNOG.csv WheatGermSEC_07-2015_multirow_wide_elution_traes_euNOG.csv


