BASEDIR=$( pwd )

cd $BASEDIR/protein_elutions


#Data freeze 9/19/2016

echo 5 wheat
python $BASEDIR/scripts/combine_elution_protein.py traes proteins wgSEC1_raw_wide_elution_traes_protein.csv wheatgermIEX_raw_wide_elution_traes_protein.csv WheatGermSEC_07-2015_raw_wide_elution_traes_protein.csv wgIEF_raw_wide_elution_traes_protein.csv OP_WheatGrassSEC_20170202_raw_wide_elution_traes_protein.csv

echo 2 selaginella
python $BASEDIR/scripts/combine_elution_protein.py selml proteins OP_SelaginellaSEC_20160309_raw_wide_elution_selml_protein.csv selaginella_WWC_raw_wide_elution_selml_protein.csv


echo 7 arath
python $BASEDIR/scripts/combine_elution_protein.py arath proteins At_Col_0_indark_201505_raw_wide_elution_arath_protein.csv At_Col_0_indark_fraction_201504_raw_wide_elution_arath_protein.csv At_Col_0_leaf_fraction_2014_raw_wide_elution_arath_protein.csv At_Col_0_leaf_fraction_2015_raw_wide_elution_arath_protein.csv OP_Arabidopsis_sproutsSEC_02102017_raw_wide_elution_arath_protein.csv Arabidopsis_sprouts_WWC_2017_raw_wide_elution_arath_protein.csv OP_Arabidopsis_mutantseed_20170323_raw_wide_elution_arath_protein.csv 






echo orysj
echo 2 orysj
python $BASEDIR/scripts/combine_elution_protein.py orysj proteins RiceL_IEX_raw_wide_elution_orysj_protein.csv Rice_201505_uniprot_raw_wide_elution_orysj_protein.csv RiceLeaf_SEC_04292016_raw_wide_elution_orysj_protein.csv



echo broccoli proteins
echo 4 braol
python $BASEDIR/scripts/combine_elution_protein.py braol proteins Broccolinuclei_6-2016_raw_wide_elution_braol_protein.csv BroccoliNE_WWC_raw_wide_elution_braol_protein.csv Broccolinuclei_IEF_9-2016_raw_wide_elution_braol_protein.csv OP_Broccoli_leaf_IEX2_20170317_raw_wide_elution_braol_protein.csv


echo chlamydomonas
echo 2 chlre
python $BASEDIR/scripts/combine_elution_protein.py chlre proteins Chlamydomonas_WWC_9-2016_raw_wide_elution_chlre_protein.csv OP_Chlamydomonas_SEC_raw_wide_elution_chlre_protein.csv



