sed -i 's/: /:0 /g' libsvm_xaa_labeled_u30full_0
sed -i 's/: /:0 /g' libsvm_xab_labeled_u30full_0
sed -i 's/: /:0 /g' libsvm_xac_labeled_u30full_0
sed -i 's/: /:0 /g' libsvm_xad_labeled_u30full_0
sed -i 's/: /:0 /g' libsvm_xae_labeled_u30full_0
sed -i 's/: /:0 /g' libsvm_xaf_labeled_u30full_0
sed -i 's/: /:0 /g' libsvm_xag_labeled_u30full_0
sed -i 's/: /:0 /g' libsvm_xah_labeled_u30full_0
sed -i 's/: /:0 /g' libsvm_xai_labeled_u30full_0
sed -i 's/: /:0 /g' libsvm_xaj_labeled_u30full_0
sed -i 's/: /:0 /g' libsvm_xak_labeled_u30full_0
sed -i 's/: /:0 /g' libsvm_xal_labeled_u30full_0
sed -i 's/: /:0 /g' libsvm_xam_labeled_u30full_0
sed -i 's/: /:0 /g' libsvm_xan_labeled_u30full_0
sed -i 's/: /:0 /g' libsvm_xao_labeled_u30full_0
sed -i 's/: /:0 /g' libsvm_xap_labeled_u30full_0
sed -i 's/: /:0 /g' libsvm_xaq_labeled_u30full_0
sed -i 's/: /:0 /g' libsvm_xar_labeled_u30full_0
sed -i 's/: /:0 /g' libsvm_xas_labeled_u30full_0
sed -i 's/: /:0 /g' libsvm_xat_labeled_u30full_0
sed -i 's/: /:0 /g' libsvm_xau_labeled_u30full_0
sed -i 's/: /:0 /g' libsvm_xav_labeled_u30full_0
sed -i 's/: /:0 /g' libsvm_xaw_labeled_u30full_0
sed -i 's/: /:0 /g' libsvm_xax_labeled_u30full_0
sed -i 's/: /:0 /g' libsvm_xay_labeled_u30full_0
sed -i 's/: /:0 /g' libsvm_xaz_labeled_u30full_0
sed -i 's/: /:0 /g' libsvm_xba_labeled_u30full_0
sed -i 's/: /:0 /g' libsvm_xbb_labeled_u30full_0
sed -i 's/: /:0 /g' libsvm_xbc_labeled_u30full_0
sed -i 's/: /:0 /g' libsvm_xbd_labeled_u30full_0
sed -i 's/: /:0 /g' libsvm_xbe_labeled_u30full_0
sed -i 's/: /:0 /g' libsvm_xbf_labeled_u30full_0
sed -i 's/: /:0 /g' libsvm_xbg_labeled_u30full_0
sed -i 's/: /:0 /g' libsvm_xbh_labeled_u30full_0
sed -i 's/: /:0 /g' libsvm_xbi_labeled_u30full_0
sed -i 's/: /:0 /g' libsvm_xbj_labeled_u30full_0
sed -i 's/: /:0 /g' libsvm_xbk_labeled_u30full_0
sed -i 's/: /:0 /g' libsvm_xbl_labeled_u30full_0
sed -i 's/: /:0 /g' libsvm_xbm_labeled_u30full_0
sed -i 's/: /:0 /g' libsvm_xbn_labeled_u30full_0
sed -i 's/: /:0 /g' libsvm_xbo_labeled_u30full_0
sed -i 's/: /:0 /g' libsvm_xbp_labeled_u30full_0
sed -i 's/: /:0 /g' libsvm_xbq_labeled_u30full_0
sed -i 's/: /:0 /g' libsvm_xbr_labeled_u30full_0
sed -i 's/: /:0 /g' libsvm_xbs_labeled_u30full_0
sed -i 's/: /:0 /g' libsvm_xbt_labeled_u30full_0
sed -i 's/: /:0 /g' libsvm_xbu_labeled_u30full_0
sed -i 's/: /:0 /g' libsvm_xbv_labeled_u30full_0
sed -i 's/: /:0 /g' libsvm_xbw_labeled_u30full_0
sed -i 's/: /:0 /g' libsvm_xbx_labeled_u30full_0
sed -i 's/: /:0 /g' libsvm_xby_labeled_u30full_0
sed -i 's/: /:0 /g' libsvm_xbz_labeled_u30full_0
sed -i 's/: /:0 /g' libsvm_xca_labeled_u30full_0
sed -i 's/: /:0 /g' libsvm_xcb_labeled_u30full_0
sed -i 's/: /:0 /g' libsvm_xcc_labeled_u30full_0
sed -i 's/: /:0 /g' libsvm_xcd_labeled_u30full_0
sed -i 's/: /:0 /g' libsvm_xce_labeled_u30full_0
sed -i 's/: /:0 /g' libsvm_xcf_labeled_u30full_0
sed -i 's/: /:0 /g' libsvm_xcg_labeled_u30full_0
sed -i 's/: /:0 /g' libsvm_xch_labeled_u30full_0
sed -i 's/: /:0 /g' libsvm_xci_labeled_u30full_0
sed -i 's/: /:0 /g' libsvm_xcj_labeled_u30full_0
sed -i 's/: /:0 /g' libsvm_xck_labeled_u30full_0
sed -i 's/: /:0 /g' libsvm_xcl_labeled_u30full_0
sed -i 's/: /:0 /g' libsvm_xcm_labeled_u30full_0
sed -i 's/: /:0 /g' libsvm_xcn_labeled_u30full_0
sed -i 's/: /:0 /g' libsvm_xco_labeled_u30full_0
sed -i 's/: /:0 /g' libsvm_xcp_labeled_u30full_0
sed -i 's/: /:0 /g' libsvm_xcq_labeled_u30full_0
sed -i 's/: /:0 /g' libsvm_xcr_labeled_u30full_0
sed -i 's/: /:0 /g' libsvm_xcs_labeled_u30full_0
sed -i 's/: /:0 /g' libsvm_xct_labeled_u30full_0
sed -i 's/: /:0 /g' libsvm_xcu_labeled_u30full_0
sed -i 's/: /:0 /g' libsvm_xcv_labeled_u30full_0
sed -i 's/: /:0 /g' libsvm_xcw_labeled_u30full_0
sed -i 's/: /:0 /g' libsvm_xcx_labeled_u30full_0
sed -i 's/: /:0 /g' libsvm_xcy_labeled_u30full_0
sed -i 's/: /:0 /g' libsvm_xcz_labeled_u30full_0
sed -i 's/: /:0 /g' libsvm_xda_labeled_u30full_0
sed -i 's/: /:0 /g' libsvm_xdb_labeled_u30full_0
sed -i 's/: /:0 /g' libsvm_xdc_labeled_u30full_0
sed -i 's/: /:0 /g' libsvm_xdd_labeled_u30full_0
sed -i 's/: /:0 /g' libsvm_xde_labeled_u30full_0
sed -i 's/: /:0 /g' libsvm_xdf_labeled_u30full_0
sed -i 's/: /:0 /g' libsvm_xdg_labeled_u30full_0
sed -i 's/: /:0 /g' libsvm_xdh_labeled_u30full_0
sed -i 's/: /:0 /g' libsvm_xdi_labeled_u30full_0
sed -i 's/: /:0 /g' libsvm_xdj_labeled_u30full_0
sed -i 's/: /:0 /g' libsvm_xdk_labeled_u30full_0
sed -i 's/: /:0 /g' libsvm_xdl_labeled_u30full_0
sed -i 's/: /:0 /g' libsvm_xdm_labeled_u30full_0
sed -i 's/: /:0 /g' libsvm_xdn_labeled_u30full_0
sed -i 's/: /:0 /g' libsvm_xdo_labeled_u30full_0
sed -i 's/: /:0 /g' libsvm_xdp_labeled_u30full_0
sed -i 's/: /:0 /g' libsvm_xdq_labeled_u30full_0
sed -i 's/: /:0 /g' libsvm_xdr_labeled_u30full_0
sed -i 's/: /:0 /g' libsvm_xds_labeled_u30full_0
sed -i 's/: /:0 /g' libsvm_xdt_labeled_u30full_0
sed -i 's/: /:0 /g' libsvm_xdu_labeled_u30full_0
sed -i 's/: /:0 /g' libsvm_xdv_labeled_u30full_0
sed -i 's/: /:0 /g' libsvm_xdw_labeled_u30full_0
sed -i 's/: /:0 /g' libsvm_xdx_labeled_u30full_0
sed -i 's/: /:0 /g' libsvm_xdy_labeled_u30full_0
sed -i 's/: /:0 /g' libsvm_xdz_labeled_u30full_0
sed -i 's/: /:0 /g' libsvm_xea_labeled_u30full_0
sed -i 's/: /:0 /g' libsvm_xeb_labeled_u30full_0
sed -i 's/: /:0 /g' libsvm_xec_labeled_u30full_0
sed -i 's/: /:0 /g' libsvm_xed_labeled_u30full_0
sed -i 's/: /:0 /g' libsvm_xee_labeled_u30full_0
sed -i 's/: /:0 /g' libsvm_xef_labeled_u30full_0
sed -i 's/: /:0 /g' libsvm_xeg_labeled_u30full_0
sed -i 's/: /:0 /g' libsvm_xeh_labeled_u30full_0
sed -i 's/: /:0 /g' libsvm_xei_labeled_u30full_0
sed -i 's/: /:0 /g' libsvm_xej_labeled_u30full_0
sed -i 's/: /:0 /g' libsvm_xek_labeled_u30full_0
sed -i 's/: /:0 /g' libsvm_xel_labeled_u30full_0
sed -i 's/: /:0 /g' libsvm_xem_labeled_u30full_0
sed -i 's/: /:0 /g' libsvm_xen_labeled_u30full_0
sed -i 's/: /:0 /g' libsvm_xeo_labeled_u30full_0
sed -i 's/: /:0 /g' libsvm_xep_labeled_u30full_0
sed -i 's/: /:0 /g' libsvm_xeq_labeled_u30full_0
sed -i 's/: /:0 /g' libsvm_xer_labeled_u30full_0
sed -i 's/: /:0 /g' libsvm_xes_labeled_u30full_0
sed -i 's/: /:0 /g' libsvm_xet_labeled_u30full_0
sed -i 's/: /:0 /g' libsvm_xeu_labeled_u30full_0
sed -i 's/: /:0 /g' libsvm_xev_labeled_u30full_0
sed -i 's/: /:0 /g' libsvm_xew_labeled_u30full_0
sed -i 's/: /:0 /g' libsvm_xex_labeled_u30full_0
sed -i 's/: /:0 /g' libsvm_xey_labeled_u30full_0
sed -i 's/: /:0 /g' libsvm_xez_labeled_u30full_0
sed -i 's/: /:0 /g' libsvm_xfa_labeled_u30full_0
sed -i 's/: /:0 /g' libsvm_xfb_labeled_u30full_0
sed -i 's/: /:0 /g' libsvm_xfc_labeled_u30full_0
sed -i 's/: /:0 /g' libsvm_xfd_labeled_u30full_0
sed -i 's/: /:0 /g' libsvm_xfe_labeled_u30full_0
sed -i 's/: /:0 /g' libsvm_xff_labeled_u30full_0
sed -i 's/: /:0 /g' libsvm_xfg_labeled_u30full_0
sed -i 's/: /:0 /g' libsvm_xfh_labeled_u30full_0
sed -i 's/: /:0 /g' libsvm_xfi_labeled_u30full_0
sed -i 's/: /:0 /g' libsvm_xfj_labeled_u30full_0
sed -i 's/: /:0 /g' libsvm_xfk_labeled_u30full_0
sed -i 's/: /:0 /g' libsvm_xfl_labeled_u30full_0
sed -i 's/: /:0 /g' libsvm_xfm_labeled_u30full_0
sed -i 's/: /:0 /g' libsvm_xfn_labeled_u30full_0
sed -i 's/: /:0 /g' libsvm_xfo_labeled_u30full_0
sed -i 's/: /:0 /g' libsvm_xfp_labeled_u30full_0
sed -i 's/: /:0 /g' libsvm_xfq_labeled_u30full_0
sed -i 's/: /:0 /g' libsvm_xfr_labeled_u30full_0
sed -i 's/: /:0 /g' libsvm_xfs_labeled_u30full_0
sed -i 's/: /:0 /g' libsvm_xft_labeled_u30full_0
sed -i 's/: /:0 /g' libsvm_xfu_labeled_u30full_0
sed -i 's/: /:0 /g' libsvm_xfv_labeled_u30full_0
sed -i 's/: /:0 /g' libsvm_xfw_labeled_u30full_0
sed -i 's/: /:0 /g' libsvm_xfx_labeled_u30full_0
sed -i 's/: /:0 /g' libsvm_xfy_labeled_u30full_0
sed -i 's/: /:0 /g' libsvm_xfz_labeled_u30full_0
sed -i 's/: /:0 /g' libsvm_xga_labeled_u30full_0
sed -i 's/: /:0 /g' libsvm_xgb_labeled_u30full_0
sed -i 's/: /:0 /g' libsvm_xgc_labeled_u30full_0
sed -i 's/: /:0 /g' libsvm_xgd_labeled_u30full_0
sed -i 's/: /:0 /g' libsvm_xge_labeled_u30full_0
sed -i 's/: /:0 /g' libsvm_xgf_labeled_u30full_0
sed -i 's/: /:0 /g' libsvm_xgg_labeled_u30full_0
sed -i 's/: /:0 /g' libsvm_xgh_labeled_u30full_0
sed -i 's/: /:0 /g' libsvm_xgi_labeled_u30full_0
sed -i 's/: /:0 /g' libsvm_xgj_labeled_u30full_0
sed -i 's/: /:0 /g' libsvm_xgk_labeled_u30full_0
sed -i 's/: /:0 /g' libsvm_xgl_labeled_u30full_0
sed -i 's/: /:0 /g' libsvm_xgm_labeled_u30full_0
sed -i 's/: /:0 /g' libsvm_xgn_labeled_u30full_0
sed -i 's/: /:0 /g' libsvm_xgo_labeled_u30full_0
sed -i 's/: /:0 /g' libsvm_xgp_labeled_u30full_0
sed -i 's/: /:0 /g' libsvm_xgq_labeled_u30full_0
sed -i 's/: /:0 /g' libsvm_xgr_labeled_u30full_0
sed -i 's/: /:0 /g' libsvm_xgs_labeled_u30full_0
sed -i 's/: /:0 /g' libsvm_xgt_labeled_u30full_0
sed -i 's/: /:0 /g' libsvm_xgu_labeled_u30full_0
sed -i 's/: /:0 /g' libsvm_xgv_labeled_u30full_0
sed -i 's/: /:0 /g' libsvm_xgw_labeled_u30full_0
sed -i 's/: /:0 /g' libsvm_xgx_labeled_u30full_0
sed -i 's/: /:0 /g' libsvm_xgy_labeled_u30full_0
sed -i 's/: /:0 /g' libsvm_xgz_labeled_u30full_0
sed -i 's/: /:0 /g' libsvm_xha_labeled_u30full_0
sed -i 's/: /:0 /g' libsvm_xhb_labeled_u30full_0
sed -i 's/: /:0 /g' libsvm_xhc_labeled_u30full_0
sed -i 's/: /:0 /g' libsvm_xhd_labeled_u30full_0
sed -i 's/: /:0 /g' libsvm_xhe_labeled_u30full_0
sed -i 's/: /:0 /g' libsvm_xhf_labeled_u30full_0
sed -i 's/: /:0 /g' libsvm_xhg_labeled_u30full_0
sed -i 's/: /:0 /g' libsvm_xhh_labeled_u30full_0
sed -i 's/: /:0 /g' libsvm_xhi_labeled_u30full_0
sed -i 's/: /:0 /g' libsvm_xhj_labeled_u30full_0
sed -i 's/: /:0 /g' libsvm_xhk_labeled_u30full_0
sed -i 's/: /:0 /g' libsvm_xhl_labeled_u30full_0
sed -i 's/: /:0 /g' libsvm_xhm_labeled_u30full_0
sed -i 's/: /:0 /g' libsvm_xhn_labeled_u30full_0
sed -i 's/: /:0 /g' libsvm_xho_labeled_u30full_0
sed -i 's/: /:0 /g' libsvm_xhp_labeled_u30full_0
sed -i 's/: /:0 /g' libsvm_xhq_labeled_u30full_0
sed -i 's/: /:0 /g' libsvm_xhr_labeled_u30full_0
sed -i 's/: /:0 /g' libsvm_xhs_labeled_u30full_0
sed -i 's/: /:0 /g' libsvm_xht_labeled_u30full_0
sed -i 's/: /:0 /g' libsvm_xaa_labeled_u30test_0
sed -i 's/: /:0 /g' libsvm_xab_labeled_u30test_0
sed -i 's/: /:0 /g' libsvm_xac_labeled_u30test_0
sed -i 's/: /:0 /g' libsvm_xad_labeled_u30test_0
sed -i 's/: /:0 /g' libsvm_xae_labeled_u30test_0
sed -i 's/: /:0 /g' libsvm_xaf_labeled_u30test_0
sed -i 's/: /:0 /g' libsvm_xag_labeled_u30test_0
sed -i 's/: /:0 /g' libsvm_xah_labeled_u30test_0
sed -i 's/: /:0 /g' libsvm_xai_labeled_u30test_0
sed -i 's/: /:0 /g' libsvm_xaj_labeled_u30test_0
sed -i 's/: /:0 /g' libsvm_xak_labeled_u30test_0
sed -i 's/: /:0 /g' libsvm_xal_labeled_u30test_0
sed -i 's/: /:0 /g' libsvm_xam_labeled_u30test_0
sed -i 's/: /:0 /g' libsvm_xan_labeled_u30test_0
sed -i 's/: /:0 /g' libsvm_xao_labeled_u30test_0
sed -i 's/: /:0 /g' libsvm_xap_labeled_u30test_0
sed -i 's/: /:0 /g' libsvm_xaq_labeled_u30test_0
sed -i 's/: /:0 /g' libsvm_xar_labeled_u30test_0
sed -i 's/: /:0 /g' libsvm_xas_labeled_u30test_0
sed -i 's/: /:0 /g' libsvm_xat_labeled_u30test_0
sed -i 's/: /:0 /g' libsvm_xau_labeled_u30test_0
sed -i 's/: /:0 /g' libsvm_xav_labeled_u30test_0
sed -i 's/: /:0 /g' libsvm_xaw_labeled_u30test_0
sed -i 's/: /:0 /g' libsvm_xax_labeled_u30test_0
sed -i 's/: /:0 /g' libsvm_xay_labeled_u30test_0
sed -i 's/: /:0 /g' libsvm_xaz_labeled_u30test_0
sed -i 's/: /:0 /g' libsvm_xba_labeled_u30test_0
sed -i 's/: /:0 /g' libsvm_xbb_labeled_u30test_0
sed -i 's/: /:0 /g' libsvm_xbc_labeled_u30test_0
sed -i 's/: /:0 /g' libsvm_xbd_labeled_u30test_0
sed -i 's/: /:0 /g' libsvm_xbe_labeled_u30test_0
sed -i 's/: /:0 /g' libsvm_xbf_labeled_u30test_0
sed -i 's/: /:0 /g' libsvm_xbg_labeled_u30test_0
sed -i 's/: /:0 /g' libsvm_xbh_labeled_u30test_0
sed -i 's/: /:0 /g' libsvm_xbi_labeled_u30test_0
sed -i 's/: /:0 /g' libsvm_xbj_labeled_u30test_0
sed -i 's/: /:0 /g' libsvm_xbk_labeled_u30test_0
sed -i 's/: /:0 /g' libsvm_xbl_labeled_u30test_0
sed -i 's/: /:0 /g' libsvm_xbm_labeled_u30test_0
sed -i 's/: /:0 /g' libsvm_xbn_labeled_u30test_0
sed -i 's/: /:0 /g' libsvm_xbo_labeled_u30test_0
sed -i 's/: /:0 /g' libsvm_xbp_labeled_u30test_0
sed -i 's/: /:0 /g' libsvm_xbq_labeled_u30test_0
sed -i 's/: /:0 /g' libsvm_xbr_labeled_u30test_0
sed -i 's/: /:0 /g' libsvm_xbs_labeled_u30test_0
sed -i 's/: /:0 /g' libsvm_xbt_labeled_u30test_0
sed -i 's/: /:0 /g' libsvm_xbu_labeled_u30test_0
sed -i 's/: /:0 /g' libsvm_xbv_labeled_u30test_0
sed -i 's/: /:0 /g' libsvm_xbw_labeled_u30test_0
sed -i 's/: /:0 /g' libsvm_xbx_labeled_u30test_0
sed -i 's/: /:0 /g' libsvm_xby_labeled_u30test_0
sed -i 's/: /:0 /g' libsvm_xbz_labeled_u30test_0
sed -i 's/: /:0 /g' libsvm_xca_labeled_u30test_0
sed -i 's/: /:0 /g' libsvm_xcb_labeled_u30test_0
sed -i 's/: /:0 /g' libsvm_xcc_labeled_u30test_0
sed -i 's/: /:0 /g' libsvm_xcd_labeled_u30test_0
sed -i 's/: /:0 /g' libsvm_xce_labeled_u30test_0
sed -i 's/: /:0 /g' libsvm_xcf_labeled_u30test_0
sed -i 's/: /:0 /g' libsvm_xcg_labeled_u30test_0
sed -i 's/: /:0 /g' libsvm_xch_labeled_u30test_0
sed -i 's/: /:0 /g' libsvm_xci_labeled_u30test_0
sed -i 's/: /:0 /g' libsvm_xcj_labeled_u30test_0
sed -i 's/: /:0 /g' libsvm_xck_labeled_u30test_0
sed -i 's/: /:0 /g' libsvm_xcl_labeled_u30test_0
sed -i 's/: /:0 /g' libsvm_xcm_labeled_u30test_0
sed -i 's/: /:0 /g' libsvm_xcn_labeled_u30test_0
sed -i 's/: /:0 /g' libsvm_xco_labeled_u30test_0
sed -i 's/: /:0 /g' libsvm_xcp_labeled_u30test_0
sed -i 's/: /:0 /g' libsvm_xcq_labeled_u30test_0
sed -i 's/: /:0 /g' libsvm_xcr_labeled_u30test_0
sed -i 's/: /:0 /g' libsvm_xcs_labeled_u30test_0
sed -i 's/: /:0 /g' libsvm_xct_labeled_u30test_0
sed -i 's/: /:0 /g' libsvm_xcu_labeled_u30test_0
sed -i 's/: /:0 /g' libsvm_xcv_labeled_u30test_0
sed -i 's/: /:0 /g' libsvm_xcw_labeled_u30test_0
sed -i 's/: /:0 /g' libsvm_xcx_labeled_u30test_0
sed -i 's/: /:0 /g' libsvm_xcy_labeled_u30test_0
sed -i 's/: /:0 /g' libsvm_xcz_labeled_u30test_0
sed -i 's/: /:0 /g' libsvm_xda_labeled_u30test_0
sed -i 's/: /:0 /g' libsvm_xdb_labeled_u30test_0
sed -i 's/: /:0 /g' libsvm_xdc_labeled_u30test_0
sed -i 's/: /:0 /g' libsvm_xdd_labeled_u30test_0
sed -i 's/: /:0 /g' libsvm_xde_labeled_u30test_0
sed -i 's/: /:0 /g' libsvm_xdf_labeled_u30test_0
sed -i 's/: /:0 /g' libsvm_xdg_labeled_u30test_0
sed -i 's/: /:0 /g' libsvm_xdh_labeled_u30test_0
sed -i 's/: /:0 /g' libsvm_xdi_labeled_u30test_0
sed -i 's/: /:0 /g' libsvm_xdj_labeled_u30test_0
sed -i 's/: /:0 /g' libsvm_xdk_labeled_u30test_0
sed -i 's/: /:0 /g' libsvm_xdl_labeled_u30test_0
sed -i 's/: /:0 /g' libsvm_xdm_labeled_u30test_0
sed -i 's/: /:0 /g' libsvm_xdn_labeled_u30test_0
sed -i 's/: /:0 /g' libsvm_xdo_labeled_u30test_0
sed -i 's/: /:0 /g' libsvm_xdp_labeled_u30test_0
sed -i 's/: /:0 /g' libsvm_xdq_labeled_u30test_0
sed -i 's/: /:0 /g' libsvm_xdr_labeled_u30test_0
sed -i 's/: /:0 /g' libsvm_xds_labeled_u30test_0
sed -i 's/: /:0 /g' libsvm_xdt_labeled_u30test_0
sed -i 's/: /:0 /g' libsvm_xdu_labeled_u30test_0
sed -i 's/: /:0 /g' libsvm_xdv_labeled_u30test_0
sed -i 's/: /:0 /g' libsvm_xdw_labeled_u30test_0
sed -i 's/: /:0 /g' libsvm_xdx_labeled_u30test_0
sed -i 's/: /:0 /g' libsvm_xdy_labeled_u30test_0
sed -i 's/: /:0 /g' libsvm_xdz_labeled_u30test_0
sed -i 's/: /:0 /g' libsvm_xea_labeled_u30test_0
sed -i 's/: /:0 /g' libsvm_xeb_labeled_u30test_0
sed -i 's/: /:0 /g' libsvm_xec_labeled_u30test_0
sed -i 's/: /:0 /g' libsvm_xed_labeled_u30test_0
sed -i 's/: /:0 /g' libsvm_xee_labeled_u30test_0
sed -i 's/: /:0 /g' libsvm_xef_labeled_u30test_0
sed -i 's/: /:0 /g' libsvm_xeg_labeled_u30test_0
sed -i 's/: /:0 /g' libsvm_xeh_labeled_u30test_0
sed -i 's/: /:0 /g' libsvm_xei_labeled_u30test_0
sed -i 's/: /:0 /g' libsvm_xej_labeled_u30test_0
sed -i 's/: /:0 /g' libsvm_xek_labeled_u30test_0
sed -i 's/: /:0 /g' libsvm_xel_labeled_u30test_0
sed -i 's/: /:0 /g' libsvm_xem_labeled_u30test_0
sed -i 's/: /:0 /g' libsvm_xen_labeled_u30test_0
sed -i 's/: /:0 /g' libsvm_xeo_labeled_u30test_0
sed -i 's/: /:0 /g' libsvm_xep_labeled_u30test_0
sed -i 's/: /:0 /g' libsvm_xeq_labeled_u30test_0
sed -i 's/: /:0 /g' libsvm_xer_labeled_u30test_0
sed -i 's/: /:0 /g' libsvm_xes_labeled_u30test_0
sed -i 's/: /:0 /g' libsvm_xet_labeled_u30test_0
sed -i 's/: /:0 /g' libsvm_xeu_labeled_u30test_0
sed -i 's/: /:0 /g' libsvm_xev_labeled_u30test_0
sed -i 's/: /:0 /g' libsvm_xew_labeled_u30test_0
sed -i 's/: /:0 /g' libsvm_xex_labeled_u30test_0
sed -i 's/: /:0 /g' libsvm_xey_labeled_u30test_0
sed -i 's/: /:0 /g' libsvm_xez_labeled_u30test_0
sed -i 's/: /:0 /g' libsvm_xfa_labeled_u30test_0
sed -i 's/: /:0 /g' libsvm_xfb_labeled_u30test_0
sed -i 's/: /:0 /g' libsvm_xfc_labeled_u30test_0
sed -i 's/: /:0 /g' libsvm_xfd_labeled_u30test_0
sed -i 's/: /:0 /g' libsvm_xfe_labeled_u30test_0
sed -i 's/: /:0 /g' libsvm_xff_labeled_u30test_0
sed -i 's/: /:0 /g' libsvm_xfg_labeled_u30test_0
sed -i 's/: /:0 /g' libsvm_xfh_labeled_u30test_0
sed -i 's/: /:0 /g' libsvm_xfi_labeled_u30test_0
sed -i 's/: /:0 /g' libsvm_xfj_labeled_u30test_0
sed -i 's/: /:0 /g' libsvm_xfk_labeled_u30test_0
sed -i 's/: /:0 /g' libsvm_xfl_labeled_u30test_0
sed -i 's/: /:0 /g' libsvm_xfm_labeled_u30test_0
sed -i 's/: /:0 /g' libsvm_xfn_labeled_u30test_0
sed -i 's/: /:0 /g' libsvm_xfo_labeled_u30test_0
sed -i 's/: /:0 /g' libsvm_xfp_labeled_u30test_0
sed -i 's/: /:0 /g' libsvm_xfq_labeled_u30test_0
sed -i 's/: /:0 /g' libsvm_xfr_labeled_u30test_0
sed -i 's/: /:0 /g' libsvm_xfs_labeled_u30test_0
sed -i 's/: /:0 /g' libsvm_xft_labeled_u30test_0
sed -i 's/: /:0 /g' libsvm_xfu_labeled_u30test_0
sed -i 's/: /:0 /g' libsvm_xfv_labeled_u30test_0
sed -i 's/: /:0 /g' libsvm_xfw_labeled_u30test_0
sed -i 's/: /:0 /g' libsvm_xfx_labeled_u30test_0
sed -i 's/: /:0 /g' libsvm_xfy_labeled_u30test_0
sed -i 's/: /:0 /g' libsvm_xfz_labeled_u30test_0
sed -i 's/: /:0 /g' libsvm_xga_labeled_u30test_0
sed -i 's/: /:0 /g' libsvm_xgb_labeled_u30test_0
sed -i 's/: /:0 /g' libsvm_xgc_labeled_u30test_0
sed -i 's/: /:0 /g' libsvm_xgd_labeled_u30test_0
sed -i 's/: /:0 /g' libsvm_xge_labeled_u30test_0
sed -i 's/: /:0 /g' libsvm_xgf_labeled_u30test_0
sed -i 's/: /:0 /g' libsvm_xgg_labeled_u30test_0
sed -i 's/: /:0 /g' libsvm_xgh_labeled_u30test_0
sed -i 's/: /:0 /g' libsvm_xgi_labeled_u30test_0
sed -i 's/: /:0 /g' libsvm_xgj_labeled_u30test_0
sed -i 's/: /:0 /g' libsvm_xgk_labeled_u30test_0
sed -i 's/: /:0 /g' libsvm_xgl_labeled_u30test_0
sed -i 's/: /:0 /g' libsvm_xgm_labeled_u30test_0
sed -i 's/: /:0 /g' libsvm_xgn_labeled_u30test_0
sed -i 's/: /:0 /g' libsvm_xgo_labeled_u30test_0
sed -i 's/: /:0 /g' libsvm_xgp_labeled_u30test_0
sed -i 's/: /:0 /g' libsvm_xgq_labeled_u30test_0
sed -i 's/: /:0 /g' libsvm_xgr_labeled_u30test_0
sed -i 's/: /:0 /g' libsvm_xgs_labeled_u30test_0
sed -i 's/: /:0 /g' libsvm_xgt_labeled_u30test_0
sed -i 's/: /:0 /g' libsvm_xgu_labeled_u30test_0
sed -i 's/: /:0 /g' libsvm_xgv_labeled_u30test_0
sed -i 's/: /:0 /g' libsvm_xgw_labeled_u30test_0
sed -i 's/: /:0 /g' libsvm_xgx_labeled_u30test_0
sed -i 's/: /:0 /g' libsvm_xgy_labeled_u30test_0
sed -i 's/: /:0 /g' libsvm_xgz_labeled_u30test_0
sed -i 's/: /:0 /g' libsvm_xha_labeled_u30test_0
sed -i 's/: /:0 /g' libsvm_xhb_labeled_u30test_0
sed -i 's/: /:0 /g' libsvm_xhc_labeled_u30test_0
sed -i 's/: /:0 /g' libsvm_xhd_labeled_u30test_0
sed -i 's/: /:0 /g' libsvm_xhe_labeled_u30test_0
sed -i 's/: /:0 /g' libsvm_xhf_labeled_u30test_0
sed -i 's/: /:0 /g' libsvm_xhg_labeled_u30test_0
sed -i 's/: /:0 /g' libsvm_xhh_labeled_u30test_0
sed -i 's/: /:0 /g' libsvm_xhi_labeled_u30test_0
sed -i 's/: /:0 /g' libsvm_xhj_labeled_u30test_0
sed -i 's/: /:0 /g' libsvm_xhk_labeled_u30test_0
sed -i 's/: /:0 /g' libsvm_xhl_labeled_u30test_0
sed -i 's/: /:0 /g' libsvm_xhm_labeled_u30test_0
sed -i 's/: /:0 /g' libsvm_xhn_labeled_u30test_0
sed -i 's/: /:0 /g' libsvm_xho_labeled_u30test_0
sed -i 's/: /:0 /g' libsvm_xhp_labeled_u30test_0
sed -i 's/: /:0 /g' libsvm_xhq_labeled_u30test_0
sed -i 's/: /:0 /g' libsvm_xhr_labeled_u30test_0
sed -i 's/: /:0 /g' libsvm_xhs_labeled_u30test_0
sed -i 's/: /:0 /g' libsvm_xht_labeled_u30test_0
sed -i 's/: /:0 /g' libsvm_xaa_labeled_u30full_1
sed -i 's/: /:0 /g' libsvm_xab_labeled_u30full_1
sed -i 's/: /:0 /g' libsvm_xac_labeled_u30full_1
sed -i 's/: /:0 /g' libsvm_xad_labeled_u30full_1
sed -i 's/: /:0 /g' libsvm_xae_labeled_u30full_1
sed -i 's/: /:0 /g' libsvm_xaf_labeled_u30full_1
sed -i 's/: /:0 /g' libsvm_xag_labeled_u30full_1
sed -i 's/: /:0 /g' libsvm_xah_labeled_u30full_1
sed -i 's/: /:0 /g' libsvm_xai_labeled_u30full_1
sed -i 's/: /:0 /g' libsvm_xaj_labeled_u30full_1
sed -i 's/: /:0 /g' libsvm_xak_labeled_u30full_1
sed -i 's/: /:0 /g' libsvm_xal_labeled_u30full_1
sed -i 's/: /:0 /g' libsvm_xam_labeled_u30full_1
sed -i 's/: /:0 /g' libsvm_xan_labeled_u30full_1
sed -i 's/: /:0 /g' libsvm_xao_labeled_u30full_1
sed -i 's/: /:0 /g' libsvm_xap_labeled_u30full_1
sed -i 's/: /:0 /g' libsvm_xaq_labeled_u30full_1
sed -i 's/: /:0 /g' libsvm_xar_labeled_u30full_1
sed -i 's/: /:0 /g' libsvm_xas_labeled_u30full_1
sed -i 's/: /:0 /g' libsvm_xat_labeled_u30full_1
sed -i 's/: /:0 /g' libsvm_xau_labeled_u30full_1
sed -i 's/: /:0 /g' libsvm_xav_labeled_u30full_1
sed -i 's/: /:0 /g' libsvm_xaw_labeled_u30full_1
sed -i 's/: /:0 /g' libsvm_xax_labeled_u30full_1
sed -i 's/: /:0 /g' libsvm_xay_labeled_u30full_1
sed -i 's/: /:0 /g' libsvm_xaz_labeled_u30full_1
sed -i 's/: /:0 /g' libsvm_xba_labeled_u30full_1
sed -i 's/: /:0 /g' libsvm_xbb_labeled_u30full_1
sed -i 's/: /:0 /g' libsvm_xbc_labeled_u30full_1
sed -i 's/: /:0 /g' libsvm_xbd_labeled_u30full_1
sed -i 's/: /:0 /g' libsvm_xbe_labeled_u30full_1
sed -i 's/: /:0 /g' libsvm_xbf_labeled_u30full_1
sed -i 's/: /:0 /g' libsvm_xbg_labeled_u30full_1
sed -i 's/: /:0 /g' libsvm_xbh_labeled_u30full_1
sed -i 's/: /:0 /g' libsvm_xbi_labeled_u30full_1
sed -i 's/: /:0 /g' libsvm_xbj_labeled_u30full_1
sed -i 's/: /:0 /g' libsvm_xbk_labeled_u30full_1
sed -i 's/: /:0 /g' libsvm_xbl_labeled_u30full_1
sed -i 's/: /:0 /g' libsvm_xbm_labeled_u30full_1
sed -i 's/: /:0 /g' libsvm_xbn_labeled_u30full_1
sed -i 's/: /:0 /g' libsvm_xbo_labeled_u30full_1
sed -i 's/: /:0 /g' libsvm_xbp_labeled_u30full_1
sed -i 's/: /:0 /g' libsvm_xbq_labeled_u30full_1
sed -i 's/: /:0 /g' libsvm_xbr_labeled_u30full_1
sed -i 's/: /:0 /g' libsvm_xbs_labeled_u30full_1
sed -i 's/: /:0 /g' libsvm_xbt_labeled_u30full_1
sed -i 's/: /:0 /g' libsvm_xbu_labeled_u30full_1
sed -i 's/: /:0 /g' libsvm_xbv_labeled_u30full_1
sed -i 's/: /:0 /g' libsvm_xbw_labeled_u30full_1
sed -i 's/: /:0 /g' libsvm_xbx_labeled_u30full_1
sed -i 's/: /:0 /g' libsvm_xby_labeled_u30full_1
sed -i 's/: /:0 /g' libsvm_xbz_labeled_u30full_1
sed -i 's/: /:0 /g' libsvm_xca_labeled_u30full_1
sed -i 's/: /:0 /g' libsvm_xcb_labeled_u30full_1
sed -i 's/: /:0 /g' libsvm_xcc_labeled_u30full_1
sed -i 's/: /:0 /g' libsvm_xcd_labeled_u30full_1
sed -i 's/: /:0 /g' libsvm_xce_labeled_u30full_1
sed -i 's/: /:0 /g' libsvm_xcf_labeled_u30full_1
sed -i 's/: /:0 /g' libsvm_xcg_labeled_u30full_1
sed -i 's/: /:0 /g' libsvm_xch_labeled_u30full_1
sed -i 's/: /:0 /g' libsvm_xci_labeled_u30full_1
sed -i 's/: /:0 /g' libsvm_xcj_labeled_u30full_1
sed -i 's/: /:0 /g' libsvm_xck_labeled_u30full_1
sed -i 's/: /:0 /g' libsvm_xcl_labeled_u30full_1
sed -i 's/: /:0 /g' libsvm_xcm_labeled_u30full_1
sed -i 's/: /:0 /g' libsvm_xcn_labeled_u30full_1
sed -i 's/: /:0 /g' libsvm_xco_labeled_u30full_1
sed -i 's/: /:0 /g' libsvm_xcp_labeled_u30full_1
sed -i 's/: /:0 /g' libsvm_xcq_labeled_u30full_1
sed -i 's/: /:0 /g' libsvm_xcr_labeled_u30full_1
sed -i 's/: /:0 /g' libsvm_xcs_labeled_u30full_1
sed -i 's/: /:0 /g' libsvm_xct_labeled_u30full_1
sed -i 's/: /:0 /g' libsvm_xcu_labeled_u30full_1
sed -i 's/: /:0 /g' libsvm_xcv_labeled_u30full_1
sed -i 's/: /:0 /g' libsvm_xcw_labeled_u30full_1
sed -i 's/: /:0 /g' libsvm_xcx_labeled_u30full_1
sed -i 's/: /:0 /g' libsvm_xcy_labeled_u30full_1
sed -i 's/: /:0 /g' libsvm_xcz_labeled_u30full_1
sed -i 's/: /:0 /g' libsvm_xda_labeled_u30full_1
sed -i 's/: /:0 /g' libsvm_xdb_labeled_u30full_1
sed -i 's/: /:0 /g' libsvm_xdc_labeled_u30full_1
sed -i 's/: /:0 /g' libsvm_xdd_labeled_u30full_1
sed -i 's/: /:0 /g' libsvm_xde_labeled_u30full_1
sed -i 's/: /:0 /g' libsvm_xdf_labeled_u30full_1
sed -i 's/: /:0 /g' libsvm_xdg_labeled_u30full_1
sed -i 's/: /:0 /g' libsvm_xdh_labeled_u30full_1
sed -i 's/: /:0 /g' libsvm_xdi_labeled_u30full_1
sed -i 's/: /:0 /g' libsvm_xdj_labeled_u30full_1
sed -i 's/: /:0 /g' libsvm_xdk_labeled_u30full_1
sed -i 's/: /:0 /g' libsvm_xdl_labeled_u30full_1
sed -i 's/: /:0 /g' libsvm_xdm_labeled_u30full_1
sed -i 's/: /:0 /g' libsvm_xdn_labeled_u30full_1
sed -i 's/: /:0 /g' libsvm_xdo_labeled_u30full_1
sed -i 's/: /:0 /g' libsvm_xdp_labeled_u30full_1
sed -i 's/: /:0 /g' libsvm_xdq_labeled_u30full_1
sed -i 's/: /:0 /g' libsvm_xdr_labeled_u30full_1
sed -i 's/: /:0 /g' libsvm_xds_labeled_u30full_1
sed -i 's/: /:0 /g' libsvm_xdt_labeled_u30full_1
sed -i 's/: /:0 /g' libsvm_xdu_labeled_u30full_1
sed -i 's/: /:0 /g' libsvm_xdv_labeled_u30full_1
sed -i 's/: /:0 /g' libsvm_xdw_labeled_u30full_1
sed -i 's/: /:0 /g' libsvm_xdx_labeled_u30full_1
sed -i 's/: /:0 /g' libsvm_xdy_labeled_u30full_1
sed -i 's/: /:0 /g' libsvm_xdz_labeled_u30full_1
sed -i 's/: /:0 /g' libsvm_xea_labeled_u30full_1
sed -i 's/: /:0 /g' libsvm_xeb_labeled_u30full_1
sed -i 's/: /:0 /g' libsvm_xec_labeled_u30full_1
sed -i 's/: /:0 /g' libsvm_xed_labeled_u30full_1
sed -i 's/: /:0 /g' libsvm_xee_labeled_u30full_1
sed -i 's/: /:0 /g' libsvm_xef_labeled_u30full_1
sed -i 's/: /:0 /g' libsvm_xeg_labeled_u30full_1
sed -i 's/: /:0 /g' libsvm_xeh_labeled_u30full_1
sed -i 's/: /:0 /g' libsvm_xei_labeled_u30full_1
sed -i 's/: /:0 /g' libsvm_xej_labeled_u30full_1
sed -i 's/: /:0 /g' libsvm_xek_labeled_u30full_1
sed -i 's/: /:0 /g' libsvm_xel_labeled_u30full_1
sed -i 's/: /:0 /g' libsvm_xem_labeled_u30full_1
sed -i 's/: /:0 /g' libsvm_xen_labeled_u30full_1
sed -i 's/: /:0 /g' libsvm_xeo_labeled_u30full_1
sed -i 's/: /:0 /g' libsvm_xep_labeled_u30full_1
sed -i 's/: /:0 /g' libsvm_xeq_labeled_u30full_1
sed -i 's/: /:0 /g' libsvm_xer_labeled_u30full_1
sed -i 's/: /:0 /g' libsvm_xes_labeled_u30full_1
sed -i 's/: /:0 /g' libsvm_xet_labeled_u30full_1
sed -i 's/: /:0 /g' libsvm_xeu_labeled_u30full_1
sed -i 's/: /:0 /g' libsvm_xev_labeled_u30full_1
sed -i 's/: /:0 /g' libsvm_xew_labeled_u30full_1
sed -i 's/: /:0 /g' libsvm_xex_labeled_u30full_1
sed -i 's/: /:0 /g' libsvm_xey_labeled_u30full_1
sed -i 's/: /:0 /g' libsvm_xez_labeled_u30full_1
sed -i 's/: /:0 /g' libsvm_xfa_labeled_u30full_1
sed -i 's/: /:0 /g' libsvm_xfb_labeled_u30full_1
sed -i 's/: /:0 /g' libsvm_xfc_labeled_u30full_1
sed -i 's/: /:0 /g' libsvm_xfd_labeled_u30full_1
sed -i 's/: /:0 /g' libsvm_xfe_labeled_u30full_1
sed -i 's/: /:0 /g' libsvm_xff_labeled_u30full_1
sed -i 's/: /:0 /g' libsvm_xfg_labeled_u30full_1
sed -i 's/: /:0 /g' libsvm_xfh_labeled_u30full_1
sed -i 's/: /:0 /g' libsvm_xfi_labeled_u30full_1
sed -i 's/: /:0 /g' libsvm_xfj_labeled_u30full_1
sed -i 's/: /:0 /g' libsvm_xfk_labeled_u30full_1
sed -i 's/: /:0 /g' libsvm_xfl_labeled_u30full_1
sed -i 's/: /:0 /g' libsvm_xfm_labeled_u30full_1
sed -i 's/: /:0 /g' libsvm_xfn_labeled_u30full_1
sed -i 's/: /:0 /g' libsvm_xfo_labeled_u30full_1
sed -i 's/: /:0 /g' libsvm_xfp_labeled_u30full_1
sed -i 's/: /:0 /g' libsvm_xfq_labeled_u30full_1
sed -i 's/: /:0 /g' libsvm_xfr_labeled_u30full_1
sed -i 's/: /:0 /g' libsvm_xfs_labeled_u30full_1
sed -i 's/: /:0 /g' libsvm_xft_labeled_u30full_1
sed -i 's/: /:0 /g' libsvm_xfu_labeled_u30full_1
sed -i 's/: /:0 /g' libsvm_xfv_labeled_u30full_1
sed -i 's/: /:0 /g' libsvm_xfw_labeled_u30full_1
sed -i 's/: /:0 /g' libsvm_xfx_labeled_u30full_1
sed -i 's/: /:0 /g' libsvm_xfy_labeled_u30full_1
sed -i 's/: /:0 /g' libsvm_xfz_labeled_u30full_1
sed -i 's/: /:0 /g' libsvm_xga_labeled_u30full_1
sed -i 's/: /:0 /g' libsvm_xgb_labeled_u30full_1
sed -i 's/: /:0 /g' libsvm_xgc_labeled_u30full_1
sed -i 's/: /:0 /g' libsvm_xgd_labeled_u30full_1
sed -i 's/: /:0 /g' libsvm_xge_labeled_u30full_1
sed -i 's/: /:0 /g' libsvm_xgf_labeled_u30full_1
sed -i 's/: /:0 /g' libsvm_xgg_labeled_u30full_1
sed -i 's/: /:0 /g' libsvm_xgh_labeled_u30full_1
sed -i 's/: /:0 /g' libsvm_xgi_labeled_u30full_1
sed -i 's/: /:0 /g' libsvm_xgj_labeled_u30full_1
sed -i 's/: /:0 /g' libsvm_xgk_labeled_u30full_1
sed -i 's/: /:0 /g' libsvm_xgl_labeled_u30full_1
sed -i 's/: /:0 /g' libsvm_xgm_labeled_u30full_1
sed -i 's/: /:0 /g' libsvm_xgn_labeled_u30full_1
sed -i 's/: /:0 /g' libsvm_xgo_labeled_u30full_1
sed -i 's/: /:0 /g' libsvm_xgp_labeled_u30full_1
sed -i 's/: /:0 /g' libsvm_xgq_labeled_u30full_1
sed -i 's/: /:0 /g' libsvm_xgr_labeled_u30full_1
sed -i 's/: /:0 /g' libsvm_xgs_labeled_u30full_1
sed -i 's/: /:0 /g' libsvm_xgt_labeled_u30full_1
sed -i 's/: /:0 /g' libsvm_xgu_labeled_u30full_1
sed -i 's/: /:0 /g' libsvm_xgv_labeled_u30full_1
sed -i 's/: /:0 /g' libsvm_xgw_labeled_u30full_1
sed -i 's/: /:0 /g' libsvm_xgx_labeled_u30full_1
sed -i 's/: /:0 /g' libsvm_xgy_labeled_u30full_1
sed -i 's/: /:0 /g' libsvm_xgz_labeled_u30full_1
sed -i 's/: /:0 /g' libsvm_xha_labeled_u30full_1
sed -i 's/: /:0 /g' libsvm_xhb_labeled_u30full_1
sed -i 's/: /:0 /g' libsvm_xhc_labeled_u30full_1
sed -i 's/: /:0 /g' libsvm_xhd_labeled_u30full_1
sed -i 's/: /:0 /g' libsvm_xhe_labeled_u30full_1
sed -i 's/: /:0 /g' libsvm_xhf_labeled_u30full_1
sed -i 's/: /:0 /g' libsvm_xhg_labeled_u30full_1
sed -i 's/: /:0 /g' libsvm_xhh_labeled_u30full_1
sed -i 's/: /:0 /g' libsvm_xhi_labeled_u30full_1
sed -i 's/: /:0 /g' libsvm_xhj_labeled_u30full_1
sed -i 's/: /:0 /g' libsvm_xhk_labeled_u30full_1
sed -i 's/: /:0 /g' libsvm_xhl_labeled_u30full_1
sed -i 's/: /:0 /g' libsvm_xhm_labeled_u30full_1
sed -i 's/: /:0 /g' libsvm_xhn_labeled_u30full_1
sed -i 's/: /:0 /g' libsvm_xho_labeled_u30full_1
sed -i 's/: /:0 /g' libsvm_xhp_labeled_u30full_1
sed -i 's/: /:0 /g' libsvm_xhq_labeled_u30full_1
sed -i 's/: /:0 /g' libsvm_xhr_labeled_u30full_1
sed -i 's/: /:0 /g' libsvm_xhs_labeled_u30full_1
sed -i 's/: /:0 /g' libsvm_xht_labeled_u30full_1
sed -i 's/: /:0 /g' libsvm_xaa_labeled_u30test_1
sed -i 's/: /:0 /g' libsvm_xab_labeled_u30test_1
sed -i 's/: /:0 /g' libsvm_xac_labeled_u30test_1
sed -i 's/: /:0 /g' libsvm_xad_labeled_u30test_1
sed -i 's/: /:0 /g' libsvm_xae_labeled_u30test_1
sed -i 's/: /:0 /g' libsvm_xaf_labeled_u30test_1
sed -i 's/: /:0 /g' libsvm_xag_labeled_u30test_1
sed -i 's/: /:0 /g' libsvm_xah_labeled_u30test_1
sed -i 's/: /:0 /g' libsvm_xai_labeled_u30test_1
sed -i 's/: /:0 /g' libsvm_xaj_labeled_u30test_1
sed -i 's/: /:0 /g' libsvm_xak_labeled_u30test_1
sed -i 's/: /:0 /g' libsvm_xal_labeled_u30test_1
sed -i 's/: /:0 /g' libsvm_xam_labeled_u30test_1
sed -i 's/: /:0 /g' libsvm_xan_labeled_u30test_1
sed -i 's/: /:0 /g' libsvm_xao_labeled_u30test_1
sed -i 's/: /:0 /g' libsvm_xap_labeled_u30test_1
sed -i 's/: /:0 /g' libsvm_xaq_labeled_u30test_1
sed -i 's/: /:0 /g' libsvm_xar_labeled_u30test_1
sed -i 's/: /:0 /g' libsvm_xas_labeled_u30test_1
sed -i 's/: /:0 /g' libsvm_xat_labeled_u30test_1
sed -i 's/: /:0 /g' libsvm_xau_labeled_u30test_1
sed -i 's/: /:0 /g' libsvm_xav_labeled_u30test_1
sed -i 's/: /:0 /g' libsvm_xaw_labeled_u30test_1
sed -i 's/: /:0 /g' libsvm_xax_labeled_u30test_1
sed -i 's/: /:0 /g' libsvm_xay_labeled_u30test_1
sed -i 's/: /:0 /g' libsvm_xaz_labeled_u30test_1
sed -i 's/: /:0 /g' libsvm_xba_labeled_u30test_1
sed -i 's/: /:0 /g' libsvm_xbb_labeled_u30test_1
sed -i 's/: /:0 /g' libsvm_xbc_labeled_u30test_1
sed -i 's/: /:0 /g' libsvm_xbd_labeled_u30test_1
sed -i 's/: /:0 /g' libsvm_xbe_labeled_u30test_1
sed -i 's/: /:0 /g' libsvm_xbf_labeled_u30test_1
sed -i 's/: /:0 /g' libsvm_xbg_labeled_u30test_1
sed -i 's/: /:0 /g' libsvm_xbh_labeled_u30test_1
sed -i 's/: /:0 /g' libsvm_xbi_labeled_u30test_1
sed -i 's/: /:0 /g' libsvm_xbj_labeled_u30test_1
sed -i 's/: /:0 /g' libsvm_xbk_labeled_u30test_1
sed -i 's/: /:0 /g' libsvm_xbl_labeled_u30test_1
sed -i 's/: /:0 /g' libsvm_xbm_labeled_u30test_1
sed -i 's/: /:0 /g' libsvm_xbn_labeled_u30test_1
sed -i 's/: /:0 /g' libsvm_xbo_labeled_u30test_1
sed -i 's/: /:0 /g' libsvm_xbp_labeled_u30test_1
sed -i 's/: /:0 /g' libsvm_xbq_labeled_u30test_1
sed -i 's/: /:0 /g' libsvm_xbr_labeled_u30test_1
sed -i 's/: /:0 /g' libsvm_xbs_labeled_u30test_1
sed -i 's/: /:0 /g' libsvm_xbt_labeled_u30test_1
sed -i 's/: /:0 /g' libsvm_xbu_labeled_u30test_1
sed -i 's/: /:0 /g' libsvm_xbv_labeled_u30test_1
sed -i 's/: /:0 /g' libsvm_xbw_labeled_u30test_1
sed -i 's/: /:0 /g' libsvm_xbx_labeled_u30test_1
sed -i 's/: /:0 /g' libsvm_xby_labeled_u30test_1
sed -i 's/: /:0 /g' libsvm_xbz_labeled_u30test_1
sed -i 's/: /:0 /g' libsvm_xca_labeled_u30test_1
sed -i 's/: /:0 /g' libsvm_xcb_labeled_u30test_1
sed -i 's/: /:0 /g' libsvm_xcc_labeled_u30test_1
sed -i 's/: /:0 /g' libsvm_xcd_labeled_u30test_1
sed -i 's/: /:0 /g' libsvm_xce_labeled_u30test_1
sed -i 's/: /:0 /g' libsvm_xcf_labeled_u30test_1
sed -i 's/: /:0 /g' libsvm_xcg_labeled_u30test_1
sed -i 's/: /:0 /g' libsvm_xch_labeled_u30test_1
sed -i 's/: /:0 /g' libsvm_xci_labeled_u30test_1
sed -i 's/: /:0 /g' libsvm_xcj_labeled_u30test_1
sed -i 's/: /:0 /g' libsvm_xck_labeled_u30test_1
sed -i 's/: /:0 /g' libsvm_xcl_labeled_u30test_1
sed -i 's/: /:0 /g' libsvm_xcm_labeled_u30test_1
sed -i 's/: /:0 /g' libsvm_xcn_labeled_u30test_1
sed -i 's/: /:0 /g' libsvm_xco_labeled_u30test_1
sed -i 's/: /:0 /g' libsvm_xcp_labeled_u30test_1
sed -i 's/: /:0 /g' libsvm_xcq_labeled_u30test_1
sed -i 's/: /:0 /g' libsvm_xcr_labeled_u30test_1
sed -i 's/: /:0 /g' libsvm_xcs_labeled_u30test_1
sed -i 's/: /:0 /g' libsvm_xct_labeled_u30test_1
sed -i 's/: /:0 /g' libsvm_xcu_labeled_u30test_1
sed -i 's/: /:0 /g' libsvm_xcv_labeled_u30test_1
sed -i 's/: /:0 /g' libsvm_xcw_labeled_u30test_1
sed -i 's/: /:0 /g' libsvm_xcx_labeled_u30test_1
sed -i 's/: /:0 /g' libsvm_xcy_labeled_u30test_1
sed -i 's/: /:0 /g' libsvm_xcz_labeled_u30test_1
sed -i 's/: /:0 /g' libsvm_xda_labeled_u30test_1
sed -i 's/: /:0 /g' libsvm_xdb_labeled_u30test_1
sed -i 's/: /:0 /g' libsvm_xdc_labeled_u30test_1
sed -i 's/: /:0 /g' libsvm_xdd_labeled_u30test_1
sed -i 's/: /:0 /g' libsvm_xde_labeled_u30test_1
sed -i 's/: /:0 /g' libsvm_xdf_labeled_u30test_1
sed -i 's/: /:0 /g' libsvm_xdg_labeled_u30test_1
sed -i 's/: /:0 /g' libsvm_xdh_labeled_u30test_1
sed -i 's/: /:0 /g' libsvm_xdi_labeled_u30test_1
sed -i 's/: /:0 /g' libsvm_xdj_labeled_u30test_1
sed -i 's/: /:0 /g' libsvm_xdk_labeled_u30test_1
sed -i 's/: /:0 /g' libsvm_xdl_labeled_u30test_1
sed -i 's/: /:0 /g' libsvm_xdm_labeled_u30test_1
sed -i 's/: /:0 /g' libsvm_xdn_labeled_u30test_1
sed -i 's/: /:0 /g' libsvm_xdo_labeled_u30test_1
sed -i 's/: /:0 /g' libsvm_xdp_labeled_u30test_1
sed -i 's/: /:0 /g' libsvm_xdq_labeled_u30test_1
sed -i 's/: /:0 /g' libsvm_xdr_labeled_u30test_1
sed -i 's/: /:0 /g' libsvm_xds_labeled_u30test_1
sed -i 's/: /:0 /g' libsvm_xdt_labeled_u30test_1
sed -i 's/: /:0 /g' libsvm_xdu_labeled_u30test_1
sed -i 's/: /:0 /g' libsvm_xdv_labeled_u30test_1
sed -i 's/: /:0 /g' libsvm_xdw_labeled_u30test_1
sed -i 's/: /:0 /g' libsvm_xdx_labeled_u30test_1
sed -i 's/: /:0 /g' libsvm_xdy_labeled_u30test_1
sed -i 's/: /:0 /g' libsvm_xdz_labeled_u30test_1
sed -i 's/: /:0 /g' libsvm_xea_labeled_u30test_1
sed -i 's/: /:0 /g' libsvm_xeb_labeled_u30test_1
sed -i 's/: /:0 /g' libsvm_xec_labeled_u30test_1
sed -i 's/: /:0 /g' libsvm_xed_labeled_u30test_1
sed -i 's/: /:0 /g' libsvm_xee_labeled_u30test_1
sed -i 's/: /:0 /g' libsvm_xef_labeled_u30test_1
sed -i 's/: /:0 /g' libsvm_xeg_labeled_u30test_1
sed -i 's/: /:0 /g' libsvm_xeh_labeled_u30test_1
sed -i 's/: /:0 /g' libsvm_xei_labeled_u30test_1
sed -i 's/: /:0 /g' libsvm_xej_labeled_u30test_1
sed -i 's/: /:0 /g' libsvm_xek_labeled_u30test_1
sed -i 's/: /:0 /g' libsvm_xel_labeled_u30test_1
sed -i 's/: /:0 /g' libsvm_xem_labeled_u30test_1
sed -i 's/: /:0 /g' libsvm_xen_labeled_u30test_1
sed -i 's/: /:0 /g' libsvm_xeo_labeled_u30test_1
sed -i 's/: /:0 /g' libsvm_xep_labeled_u30test_1
sed -i 's/: /:0 /g' libsvm_xeq_labeled_u30test_1
sed -i 's/: /:0 /g' libsvm_xer_labeled_u30test_1
sed -i 's/: /:0 /g' libsvm_xes_labeled_u30test_1
sed -i 's/: /:0 /g' libsvm_xet_labeled_u30test_1
sed -i 's/: /:0 /g' libsvm_xeu_labeled_u30test_1
sed -i 's/: /:0 /g' libsvm_xev_labeled_u30test_1
sed -i 's/: /:0 /g' libsvm_xew_labeled_u30test_1
sed -i 's/: /:0 /g' libsvm_xex_labeled_u30test_1
sed -i 's/: /:0 /g' libsvm_xey_labeled_u30test_1
sed -i 's/: /:0 /g' libsvm_xez_labeled_u30test_1
sed -i 's/: /:0 /g' libsvm_xfa_labeled_u30test_1
sed -i 's/: /:0 /g' libsvm_xfb_labeled_u30test_1
sed -i 's/: /:0 /g' libsvm_xfc_labeled_u30test_1
sed -i 's/: /:0 /g' libsvm_xfd_labeled_u30test_1
sed -i 's/: /:0 /g' libsvm_xfe_labeled_u30test_1
sed -i 's/: /:0 /g' libsvm_xff_labeled_u30test_1
sed -i 's/: /:0 /g' libsvm_xfg_labeled_u30test_1
sed -i 's/: /:0 /g' libsvm_xfh_labeled_u30test_1
sed -i 's/: /:0 /g' libsvm_xfi_labeled_u30test_1
sed -i 's/: /:0 /g' libsvm_xfj_labeled_u30test_1
sed -i 's/: /:0 /g' libsvm_xfk_labeled_u30test_1
sed -i 's/: /:0 /g' libsvm_xfl_labeled_u30test_1
sed -i 's/: /:0 /g' libsvm_xfm_labeled_u30test_1
sed -i 's/: /:0 /g' libsvm_xfn_labeled_u30test_1
sed -i 's/: /:0 /g' libsvm_xfo_labeled_u30test_1
sed -i 's/: /:0 /g' libsvm_xfp_labeled_u30test_1
sed -i 's/: /:0 /g' libsvm_xfq_labeled_u30test_1
sed -i 's/: /:0 /g' libsvm_xfr_labeled_u30test_1
sed -i 's/: /:0 /g' libsvm_xfs_labeled_u30test_1
sed -i 's/: /:0 /g' libsvm_xft_labeled_u30test_1
sed -i 's/: /:0 /g' libsvm_xfu_labeled_u30test_1
sed -i 's/: /:0 /g' libsvm_xfv_labeled_u30test_1
sed -i 's/: /:0 /g' libsvm_xfw_labeled_u30test_1
sed -i 's/: /:0 /g' libsvm_xfx_labeled_u30test_1
sed -i 's/: /:0 /g' libsvm_xfy_labeled_u30test_1
sed -i 's/: /:0 /g' libsvm_xfz_labeled_u30test_1
sed -i 's/: /:0 /g' libsvm_xga_labeled_u30test_1
sed -i 's/: /:0 /g' libsvm_xgb_labeled_u30test_1
sed -i 's/: /:0 /g' libsvm_xgc_labeled_u30test_1
sed -i 's/: /:0 /g' libsvm_xgd_labeled_u30test_1
sed -i 's/: /:0 /g' libsvm_xge_labeled_u30test_1
sed -i 's/: /:0 /g' libsvm_xgf_labeled_u30test_1
sed -i 's/: /:0 /g' libsvm_xgg_labeled_u30test_1
sed -i 's/: /:0 /g' libsvm_xgh_labeled_u30test_1
sed -i 's/: /:0 /g' libsvm_xgi_labeled_u30test_1
sed -i 's/: /:0 /g' libsvm_xgj_labeled_u30test_1
sed -i 's/: /:0 /g' libsvm_xgk_labeled_u30test_1
sed -i 's/: /:0 /g' libsvm_xgl_labeled_u30test_1
sed -i 's/: /:0 /g' libsvm_xgm_labeled_u30test_1
sed -i 's/: /:0 /g' libsvm_xgn_labeled_u30test_1
sed -i 's/: /:0 /g' libsvm_xgo_labeled_u30test_1
sed -i 's/: /:0 /g' libsvm_xgp_labeled_u30test_1
sed -i 's/: /:0 /g' libsvm_xgq_labeled_u30test_1
sed -i 's/: /:0 /g' libsvm_xgr_labeled_u30test_1
sed -i 's/: /:0 /g' libsvm_xgs_labeled_u30test_1
sed -i 's/: /:0 /g' libsvm_xgt_labeled_u30test_1
sed -i 's/: /:0 /g' libsvm_xgu_labeled_u30test_1
sed -i 's/: /:0 /g' libsvm_xgv_labeled_u30test_1
sed -i 's/: /:0 /g' libsvm_xgw_labeled_u30test_1
sed -i 's/: /:0 /g' libsvm_xgx_labeled_u30test_1
sed -i 's/: /:0 /g' libsvm_xgy_labeled_u30test_1
sed -i 's/: /:0 /g' libsvm_xgz_labeled_u30test_1
sed -i 's/: /:0 /g' libsvm_xha_labeled_u30test_1
sed -i 's/: /:0 /g' libsvm_xhb_labeled_u30test_1
sed -i 's/: /:0 /g' libsvm_xhc_labeled_u30test_1
sed -i 's/: /:0 /g' libsvm_xhd_labeled_u30test_1
sed -i 's/: /:0 /g' libsvm_xhe_labeled_u30test_1
sed -i 's/: /:0 /g' libsvm_xhf_labeled_u30test_1
sed -i 's/: /:0 /g' libsvm_xhg_labeled_u30test_1
sed -i 's/: /:0 /g' libsvm_xhh_labeled_u30test_1
sed -i 's/: /:0 /g' libsvm_xhi_labeled_u30test_1
sed -i 's/: /:0 /g' libsvm_xhj_labeled_u30test_1
sed -i 's/: /:0 /g' libsvm_xhk_labeled_u30test_1
sed -i 's/: /:0 /g' libsvm_xhl_labeled_u30test_1
sed -i 's/: /:0 /g' libsvm_xhm_labeled_u30test_1
sed -i 's/: /:0 /g' libsvm_xhn_labeled_u30test_1
sed -i 's/: /:0 /g' libsvm_xho_labeled_u30test_1
sed -i 's/: /:0 /g' libsvm_xhp_labeled_u30test_1
sed -i 's/: /:0 /g' libsvm_xhq_labeled_u30test_1
sed -i 's/: /:0 /g' libsvm_xhr_labeled_u30test_1
sed -i 's/: /:0 /g' libsvm_xhs_labeled_u30test_1
sed -i 's/: /:0 /g' libsvm_xht_labeled_u30test_1
