/home1/03491/cmcwhite/libsvm/svm-scale -r atobsc3_full.libsvm1.scale_parameters libsvm_xaa_labeled_test_1 > libsvm_xaa_labeled_test_1_scaleByTrain
/home1/03491/cmcwhite/libsvm/svm-scale -r atobsc3_full.libsvm1.scale_parameters libsvm_xab_labeled_test_1 > libsvm_xab_labeled_test_1_scaleByTrain
/home1/03491/cmcwhite/libsvm/svm-scale -r atobsc3_full.libsvm1.scale_parameters libsvm_xac_labeled_test_1 > libsvm_xac_labeled_test_1_scaleByTrain
/home1/03491/cmcwhite/libsvm/svm-scale -r atobsc3_full.libsvm1.scale_parameters libsvm_xad_labeled_test_1 > libsvm_xad_labeled_test_1_scaleByTrain
/home1/03491/cmcwhite/libsvm/svm-scale -r atobsc3_full.libsvm1.scale_parameters libsvm_xae_labeled_test_1 > libsvm_xae_labeled_test_1_scaleByTrain
/home1/03491/cmcwhite/libsvm/svm-scale -r atobsc3_full.libsvm1.scale_parameters libsvm_xaf_labeled_test_1 > libsvm_xaf_labeled_test_1_scaleByTrain
/home1/03491/cmcwhite/libsvm/svm-scale -r atobsc3_full.libsvm1.scale_parameters libsvm_xag_labeled_test_1 > libsvm_xag_labeled_test_1_scaleByTrain
/home1/03491/cmcwhite/libsvm/svm-scale -r atobsc3_full.libsvm1.scale_parameters libsvm_xah_labeled_test_1 > libsvm_xah_labeled_test_1_scaleByTrain
/home1/03491/cmcwhite/libsvm/svm-scale -r atobsc3_full.libsvm1.scale_parameters libsvm_xai_labeled_test_1 > libsvm_xai_labeled_test_1_scaleByTrain
/home1/03491/cmcwhite/libsvm/svm-scale -r atobsc3_full.libsvm1.scale_parameters libsvm_xaj_labeled_test_1 > libsvm_xaj_labeled_test_1_scaleByTrain
/home1/03491/cmcwhite/libsvm/svm-scale -r atobsc3_full.libsvm1.scale_parameters libsvm_xak_labeled_test_1 > libsvm_xak_labeled_test_1_scaleByTrain
/home1/03491/cmcwhite/libsvm/svm-scale -r atobsc3_full.libsvm1.scale_parameters libsvm_xal_labeled_test_1 > libsvm_xal_labeled_test_1_scaleByTrain
/home1/03491/cmcwhite/libsvm/svm-scale -r atobsc3_full.libsvm1.scale_parameters libsvm_xam_labeled_test_1 > libsvm_xam_labeled_test_1_scaleByTrain
/home1/03491/cmcwhite/libsvm/svm-scale -r atobsc3_full.libsvm1.scale_parameters libsvm_xan_labeled_test_1 > libsvm_xan_labeled_test_1_scaleByTrain
/home1/03491/cmcwhite/libsvm/svm-scale -r atobsc3_full.libsvm1.scale_parameters libsvm_xao_labeled_test_1 > libsvm_xao_labeled_test_1_scaleByTrain
/home1/03491/cmcwhite/libsvm/svm-scale -r atobsc3_full.libsvm1.scale_parameters libsvm_xap_labeled_test_1 > libsvm_xap_labeled_test_1_scaleByTrain
/home1/03491/cmcwhite/libsvm/svm-scale -r atobsc3_full.libsvm1.scale_parameters libsvm_xaq_labeled_test_1 > libsvm_xaq_labeled_test_1_scaleByTrain
/home1/03491/cmcwhite/libsvm/svm-scale -r atobsc3_full.libsvm1.scale_parameters libsvm_xar_labeled_test_1 > libsvm_xar_labeled_test_1_scaleByTrain
/home1/03491/cmcwhite/libsvm/svm-scale -r atobsc3_full.libsvm1.scale_parameters libsvm_xas_labeled_test_1 > libsvm_xas_labeled_test_1_scaleByTrain
/home1/03491/cmcwhite/libsvm/svm-scale -r atobsc3_full.libsvm1.scale_parameters libsvm_xat_labeled_test_1 > libsvm_xat_labeled_test_1_scaleByTrain
/home1/03491/cmcwhite/libsvm/svm-scale -r atobsc3_full.libsvm1.scale_parameters libsvm_xau_labeled_test_1 > libsvm_xau_labeled_test_1_scaleByTrain
/home1/03491/cmcwhite/libsvm/svm-scale -r atobsc3_full.libsvm1.scale_parameters libsvm_xav_labeled_test_1 > libsvm_xav_labeled_test_1_scaleByTrain
/home1/03491/cmcwhite/libsvm/svm-scale -r atobsc3_full.libsvm1.scale_parameters libsvm_xaw_labeled_test_1 > libsvm_xaw_labeled_test_1_scaleByTrain
/home1/03491/cmcwhite/libsvm/svm-scale -r atobsc3_full.libsvm1.scale_parameters libsvm_xax_labeled_test_1 > libsvm_xax_labeled_test_1_scaleByTrain
/home1/03491/cmcwhite/libsvm/svm-scale -r atobsc3_full.libsvm1.scale_parameters libsvm_xay_labeled_test_1 > libsvm_xay_labeled_test_1_scaleByTrain
/home1/03491/cmcwhite/libsvm/svm-scale -r atobsc3_full.libsvm1.scale_parameters libsvm_xaz_labeled_test_1 > libsvm_xaz_labeled_test_1_scaleByTrain
/home1/03491/cmcwhite/libsvm/svm-scale -r atobsc3_full.libsvm1.scale_parameters libsvm_xba_labeled_test_1 > libsvm_xba_labeled_test_1_scaleByTrain
/home1/03491/cmcwhite/libsvm/svm-scale -r atobsc3_full.libsvm1.scale_parameters libsvm_xbb_labeled_test_1 > libsvm_xbb_labeled_test_1_scaleByTrain
/home1/03491/cmcwhite/libsvm/svm-scale -r atobsc3_full.libsvm1.scale_parameters libsvm_xbc_labeled_test_1 > libsvm_xbc_labeled_test_1_scaleByTrain
/home1/03491/cmcwhite/libsvm/svm-scale -r atobsc3_full.libsvm1.scale_parameters libsvm_xbd_labeled_test_1 > libsvm_xbd_labeled_test_1_scaleByTrain
/home1/03491/cmcwhite/libsvm/svm-scale -r atobsc3_full.libsvm1.scale_parameters libsvm_xbe_labeled_test_1 > libsvm_xbe_labeled_test_1_scaleByTrain
/home1/03491/cmcwhite/libsvm/svm-scale -r atobsc3_full.libsvm1.scale_parameters libsvm_xbf_labeled_test_1 > libsvm_xbf_labeled_test_1_scaleByTrain
/home1/03491/cmcwhite/libsvm/svm-scale -r atobsc3_full.libsvm1.scale_parameters libsvm_xbg_labeled_test_1 > libsvm_xbg_labeled_test_1_scaleByTrain
/home1/03491/cmcwhite/libsvm/svm-scale -r atobsc3_full.libsvm1.scale_parameters libsvm_xbh_labeled_test_1 > libsvm_xbh_labeled_test_1_scaleByTrain
/home1/03491/cmcwhite/libsvm/svm-scale -r atobsc3_full.libsvm1.scale_parameters libsvm_xbi_labeled_test_1 > libsvm_xbi_labeled_test_1_scaleByTrain
/home1/03491/cmcwhite/libsvm/svm-scale -r atobsc3_full.libsvm1.scale_parameters libsvm_xbj_labeled_test_1 > libsvm_xbj_labeled_test_1_scaleByTrain
/home1/03491/cmcwhite/libsvm/svm-scale -r atobsc3_full.libsvm1.scale_parameters libsvm_xbk_labeled_test_1 > libsvm_xbk_labeled_test_1_scaleByTrain
/home1/03491/cmcwhite/libsvm/svm-scale -r atobsc3_full.libsvm1.scale_parameters libsvm_xbl_labeled_test_1 > libsvm_xbl_labeled_test_1_scaleByTrain
/home1/03491/cmcwhite/libsvm/svm-scale -r atobsc3_full.libsvm1.scale_parameters libsvm_xbm_labeled_test_1 > libsvm_xbm_labeled_test_1_scaleByTrain
/home1/03491/cmcwhite/libsvm/svm-scale -r atobsc3_full.libsvm1.scale_parameters libsvm_xbn_labeled_test_1 > libsvm_xbn_labeled_test_1_scaleByTrain
/home1/03491/cmcwhite/libsvm/svm-scale -r atobsc3_full.libsvm1.scale_parameters libsvm_xbo_labeled_test_1 > libsvm_xbo_labeled_test_1_scaleByTrain
/home1/03491/cmcwhite/libsvm/svm-scale -r atobsc3_full.libsvm1.scale_parameters libsvm_xbp_labeled_test_1 > libsvm_xbp_labeled_test_1_scaleByTrain
/home1/03491/cmcwhite/libsvm/svm-scale -r atobsc3_full.libsvm1.scale_parameters libsvm_xbq_labeled_test_1 > libsvm_xbq_labeled_test_1_scaleByTrain
/home1/03491/cmcwhite/libsvm/svm-scale -r atobsc3_full.libsvm1.scale_parameters libsvm_xbr_labeled_test_1 > libsvm_xbr_labeled_test_1_scaleByTrain
/home1/03491/cmcwhite/libsvm/svm-scale -r atobsc3_full.libsvm1.scale_parameters libsvm_xbs_labeled_test_1 > libsvm_xbs_labeled_test_1_scaleByTrain
/home1/03491/cmcwhite/libsvm/svm-scale -r atobsc3_full.libsvm1.scale_parameters libsvm_xbt_labeled_test_1 > libsvm_xbt_labeled_test_1_scaleByTrain
/home1/03491/cmcwhite/libsvm/svm-scale -r atobsc3_full.libsvm1.scale_parameters libsvm_xbu_labeled_test_1 > libsvm_xbu_labeled_test_1_scaleByTrain
/home1/03491/cmcwhite/libsvm/svm-scale -r atobsc3_full.libsvm1.scale_parameters libsvm_xbv_labeled_test_1 > libsvm_xbv_labeled_test_1_scaleByTrain
/home1/03491/cmcwhite/libsvm/svm-scale -r atobsc3_full.libsvm1.scale_parameters libsvm_xbw_labeled_test_1 > libsvm_xbw_labeled_test_1_scaleByTrain
/home1/03491/cmcwhite/libsvm/svm-scale -r atobsc3_full.libsvm1.scale_parameters libsvm_xbx_labeled_test_1 > libsvm_xbx_labeled_test_1_scaleByTrain
/home1/03491/cmcwhite/libsvm/svm-scale -r atobsc3_full.libsvm1.scale_parameters libsvm_xby_labeled_test_1 > libsvm_xby_labeled_test_1_scaleByTrain
/home1/03491/cmcwhite/libsvm/svm-scale -r atobsc3_full.libsvm1.scale_parameters libsvm_xbz_labeled_test_1 > libsvm_xbz_labeled_test_1_scaleByTrain
/home1/03491/cmcwhite/libsvm/svm-scale -r atobsc3_full.libsvm1.scale_parameters libsvm_xca_labeled_test_1 > libsvm_xca_labeled_test_1_scaleByTrain
/home1/03491/cmcwhite/libsvm/svm-scale -r atobsc3_full.libsvm1.scale_parameters libsvm_xcb_labeled_test_1 > libsvm_xcb_labeled_test_1_scaleByTrain
/home1/03491/cmcwhite/libsvm/svm-scale -r atobsc3_full.libsvm1.scale_parameters libsvm_xcc_labeled_test_1 > libsvm_xcc_labeled_test_1_scaleByTrain
/home1/03491/cmcwhite/libsvm/svm-scale -r atobsc3_full.libsvm1.scale_parameters libsvm_xcd_labeled_test_1 > libsvm_xcd_labeled_test_1_scaleByTrain
/home1/03491/cmcwhite/libsvm/svm-scale -r atobsc3_full.libsvm1.scale_parameters libsvm_xce_labeled_test_1 > libsvm_xce_labeled_test_1_scaleByTrain
/home1/03491/cmcwhite/libsvm/svm-scale -r atobsc3_full.libsvm1.scale_parameters libsvm_xcf_labeled_test_1 > libsvm_xcf_labeled_test_1_scaleByTrain
/home1/03491/cmcwhite/libsvm/svm-scale -r atobsc3_full.libsvm1.scale_parameters libsvm_xcg_labeled_test_1 > libsvm_xcg_labeled_test_1_scaleByTrain
/home1/03491/cmcwhite/libsvm/svm-scale -r atobsc3_full.libsvm1.scale_parameters libsvm_xch_labeled_test_1 > libsvm_xch_labeled_test_1_scaleByTrain
/home1/03491/cmcwhite/libsvm/svm-scale -r atobsc3_full.libsvm1.scale_parameters libsvm_xci_labeled_test_1 > libsvm_xci_labeled_test_1_scaleByTrain
/home1/03491/cmcwhite/libsvm/svm-scale -r atobsc3_full.libsvm1.scale_parameters libsvm_xcj_labeled_test_1 > libsvm_xcj_labeled_test_1_scaleByTrain
/home1/03491/cmcwhite/libsvm/svm-scale -r atobsc3_full.libsvm1.scale_parameters libsvm_xck_labeled_test_1 > libsvm_xck_labeled_test_1_scaleByTrain
/home1/03491/cmcwhite/libsvm/svm-scale -r atobsc3_full.libsvm1.scale_parameters libsvm_xcl_labeled_test_1 > libsvm_xcl_labeled_test_1_scaleByTrain
/home1/03491/cmcwhite/libsvm/svm-scale -r atobsc3_full.libsvm1.scale_parameters libsvm_xcm_labeled_test_1 > libsvm_xcm_labeled_test_1_scaleByTrain
/home1/03491/cmcwhite/libsvm/svm-scale -r atobsc3_full.libsvm1.scale_parameters libsvm_xcn_labeled_test_1 > libsvm_xcn_labeled_test_1_scaleByTrain
/home1/03491/cmcwhite/libsvm/svm-scale -r atobsc3_full.libsvm1.scale_parameters libsvm_xco_labeled_test_1 > libsvm_xco_labeled_test_1_scaleByTrain
/home1/03491/cmcwhite/libsvm/svm-scale -r atobsc3_full.libsvm1.scale_parameters libsvm_xcp_labeled_test_1 > libsvm_xcp_labeled_test_1_scaleByTrain
/home1/03491/cmcwhite/libsvm/svm-scale -r atobsc3_full.libsvm1.scale_parameters libsvm_xcq_labeled_test_1 > libsvm_xcq_labeled_test_1_scaleByTrain
/home1/03491/cmcwhite/libsvm/svm-scale -r atobsc3_full.libsvm1.scale_parameters libsvm_xcr_labeled_test_1 > libsvm_xcr_labeled_test_1_scaleByTrain
/home1/03491/cmcwhite/libsvm/svm-scale -r atobsc3_full.libsvm1.scale_parameters libsvm_xcs_labeled_test_1 > libsvm_xcs_labeled_test_1_scaleByTrain
/home1/03491/cmcwhite/libsvm/svm-scale -r atobsc3_full.libsvm1.scale_parameters libsvm_xct_labeled_test_1 > libsvm_xct_labeled_test_1_scaleByTrain
/home1/03491/cmcwhite/libsvm/svm-scale -r atobsc3_full.libsvm1.scale_parameters libsvm_xcu_labeled_test_1 > libsvm_xcu_labeled_test_1_scaleByTrain
/home1/03491/cmcwhite/libsvm/svm-scale -r atobsc3_full.libsvm1.scale_parameters libsvm_xcv_labeled_test_1 > libsvm_xcv_labeled_test_1_scaleByTrain
/home1/03491/cmcwhite/libsvm/svm-scale -r atobsc3_full.libsvm1.scale_parameters libsvm_xcw_labeled_test_1 > libsvm_xcw_labeled_test_1_scaleByTrain
/home1/03491/cmcwhite/libsvm/svm-scale -r atobsc3_full.libsvm1.scale_parameters libsvm_xcx_labeled_test_1 > libsvm_xcx_labeled_test_1_scaleByTrain
/home1/03491/cmcwhite/libsvm/svm-scale -r atobsc3_full.libsvm1.scale_parameters libsvm_xcy_labeled_test_1 > libsvm_xcy_labeled_test_1_scaleByTrain
/home1/03491/cmcwhite/libsvm/svm-scale -r atobsc3_full.libsvm1.scale_parameters libsvm_xcz_labeled_test_1 > libsvm_xcz_labeled_test_1_scaleByTrain
/home1/03491/cmcwhite/libsvm/svm-scale -r atobsc3_full.libsvm1.scale_parameters libsvm_xda_labeled_test_1 > libsvm_xda_labeled_test_1_scaleByTrain
/home1/03491/cmcwhite/libsvm/svm-scale -r atobsc3_full.libsvm1.scale_parameters libsvm_xdb_labeled_test_1 > libsvm_xdb_labeled_test_1_scaleByTrain
/home1/03491/cmcwhite/libsvm/svm-scale -r atobsc3_full.libsvm1.scale_parameters libsvm_xdc_labeled_test_1 > libsvm_xdc_labeled_test_1_scaleByTrain
/home1/03491/cmcwhite/libsvm/svm-scale -r atobsc3_full.libsvm1.scale_parameters libsvm_xdd_labeled_test_1 > libsvm_xdd_labeled_test_1_scaleByTrain
/home1/03491/cmcwhite/libsvm/svm-scale -r atobsc3_full.libsvm1.scale_parameters libsvm_xde_labeled_test_1 > libsvm_xde_labeled_test_1_scaleByTrain
/home1/03491/cmcwhite/libsvm/svm-scale -r atobsc3_full.libsvm1.scale_parameters libsvm_xdf_labeled_test_1 > libsvm_xdf_labeled_test_1_scaleByTrain
/home1/03491/cmcwhite/libsvm/svm-scale -r atobsc3_full.libsvm1.scale_parameters libsvm_xdg_labeled_test_1 > libsvm_xdg_labeled_test_1_scaleByTrain
/home1/03491/cmcwhite/libsvm/svm-scale -r atobsc3_full.libsvm1.scale_parameters libsvm_xdh_labeled_test_1 > libsvm_xdh_labeled_test_1_scaleByTrain
/home1/03491/cmcwhite/libsvm/svm-scale -r atobsc3_full.libsvm1.scale_parameters libsvm_xdi_labeled_test_1 > libsvm_xdi_labeled_test_1_scaleByTrain
/home1/03491/cmcwhite/libsvm/svm-scale -r atobsc3_full.libsvm1.scale_parameters libsvm_xdj_labeled_test_1 > libsvm_xdj_labeled_test_1_scaleByTrain
/home1/03491/cmcwhite/libsvm/svm-scale -r atobsc3_full.libsvm1.scale_parameters libsvm_xdk_labeled_test_1 > libsvm_xdk_labeled_test_1_scaleByTrain
/home1/03491/cmcwhite/libsvm/svm-scale -r atobsc3_full.libsvm1.scale_parameters libsvm_xdl_labeled_test_1 > libsvm_xdl_labeled_test_1_scaleByTrain
/home1/03491/cmcwhite/libsvm/svm-scale -r atobsc3_full.libsvm1.scale_parameters libsvm_xdm_labeled_test_1 > libsvm_xdm_labeled_test_1_scaleByTrain
/home1/03491/cmcwhite/libsvm/svm-scale -r atobsc3_full.libsvm1.scale_parameters libsvm_xdn_labeled_test_1 > libsvm_xdn_labeled_test_1_scaleByTrain
/home1/03491/cmcwhite/libsvm/svm-scale -r atobsc3_full.libsvm1.scale_parameters libsvm_xdo_labeled_test_1 > libsvm_xdo_labeled_test_1_scaleByTrain
/home1/03491/cmcwhite/libsvm/svm-scale -r atobsc3_full.libsvm1.scale_parameters libsvm_xdp_labeled_test_1 > libsvm_xdp_labeled_test_1_scaleByTrain
/home1/03491/cmcwhite/libsvm/svm-scale -r atobsc3_full.libsvm1.scale_parameters libsvm_xdq_labeled_test_1 > libsvm_xdq_labeled_test_1_scaleByTrain
/home1/03491/cmcwhite/libsvm/svm-scale -r atobsc3_full.libsvm1.scale_parameters libsvm_xdr_labeled_test_1 > libsvm_xdr_labeled_test_1_scaleByTrain
/home1/03491/cmcwhite/libsvm/svm-scale -r atobsc3_full.libsvm1.scale_parameters libsvm_xds_labeled_test_1 > libsvm_xds_labeled_test_1_scaleByTrain
/home1/03491/cmcwhite/libsvm/svm-scale -r atobsc3_full.libsvm1.scale_parameters libsvm_xdt_labeled_test_1 > libsvm_xdt_labeled_test_1_scaleByTrain
/home1/03491/cmcwhite/libsvm/svm-scale -r atobsc3_full.libsvm1.scale_parameters libsvm_xdu_labeled_test_1 > libsvm_xdu_labeled_test_1_scaleByTrain
/home1/03491/cmcwhite/libsvm/svm-scale -r atobsc3_full.libsvm1.scale_parameters libsvm_xdv_labeled_test_1 > libsvm_xdv_labeled_test_1_scaleByTrain
/home1/03491/cmcwhite/libsvm/svm-scale -r atobsc3_full.libsvm1.scale_parameters libsvm_xdw_labeled_test_1 > libsvm_xdw_labeled_test_1_scaleByTrain
/home1/03491/cmcwhite/libsvm/svm-scale -r atobsc3_full.libsvm1.scale_parameters libsvm_xdx_labeled_test_1 > libsvm_xdx_labeled_test_1_scaleByTrain
/home1/03491/cmcwhite/libsvm/svm-scale -r atobsc3_full.libsvm1.scale_parameters libsvm_xdy_labeled_test_1 > libsvm_xdy_labeled_test_1_scaleByTrain
/home1/03491/cmcwhite/libsvm/svm-scale -r atobsc3_full.libsvm1.scale_parameters libsvm_xdz_labeled_test_1 > libsvm_xdz_labeled_test_1_scaleByTrain
/home1/03491/cmcwhite/libsvm/svm-scale -r atobsc3_full.libsvm1.scale_parameters libsvm_xea_labeled_test_1 > libsvm_xea_labeled_test_1_scaleByTrain
/home1/03491/cmcwhite/libsvm/svm-scale -r atobsc3_full.libsvm1.scale_parameters libsvm_xeb_labeled_test_1 > libsvm_xeb_labeled_test_1_scaleByTrain
/home1/03491/cmcwhite/libsvm/svm-scale -r atobsc3_full.libsvm1.scale_parameters libsvm_xec_labeled_test_1 > libsvm_xec_labeled_test_1_scaleByTrain
/home1/03491/cmcwhite/libsvm/svm-scale -r atobsc3_full.libsvm1.scale_parameters libsvm_xed_labeled_test_1 > libsvm_xed_labeled_test_1_scaleByTrain
/home1/03491/cmcwhite/libsvm/svm-scale -r atobsc3_full.libsvm1.scale_parameters libsvm_xee_labeled_test_1 > libsvm_xee_labeled_test_1_scaleByTrain
/home1/03491/cmcwhite/libsvm/svm-scale -r atobsc3_full.libsvm1.scale_parameters libsvm_xef_labeled_test_1 > libsvm_xef_labeled_test_1_scaleByTrain
/home1/03491/cmcwhite/libsvm/svm-scale -r atobsc3_full.libsvm1.scale_parameters libsvm_xeg_labeled_test_1 > libsvm_xeg_labeled_test_1_scaleByTrain
/home1/03491/cmcwhite/libsvm/svm-scale -r atobsc3_full.libsvm1.scale_parameters libsvm_xeh_labeled_test_1 > libsvm_xeh_labeled_test_1_scaleByTrain
/home1/03491/cmcwhite/libsvm/svm-scale -r atobsc3_full.libsvm1.scale_parameters libsvm_xei_labeled_test_1 > libsvm_xei_labeled_test_1_scaleByTrain
/home1/03491/cmcwhite/libsvm/svm-scale -r atobsc3_full.libsvm1.scale_parameters libsvm_xej_labeled_test_1 > libsvm_xej_labeled_test_1_scaleByTrain
/home1/03491/cmcwhite/libsvm/svm-scale -r atobsc3_full.libsvm1.scale_parameters libsvm_xek_labeled_test_1 > libsvm_xek_labeled_test_1_scaleByTrain
/home1/03491/cmcwhite/libsvm/svm-scale -r atobsc3_full.libsvm1.scale_parameters libsvm_xel_labeled_test_1 > libsvm_xel_labeled_test_1_scaleByTrain
/home1/03491/cmcwhite/libsvm/svm-scale -r atobsc3_full.libsvm1.scale_parameters libsvm_xem_labeled_test_1 > libsvm_xem_labeled_test_1_scaleByTrain
/home1/03491/cmcwhite/libsvm/svm-scale -r atobsc3_full.libsvm1.scale_parameters libsvm_xen_labeled_test_1 > libsvm_xen_labeled_test_1_scaleByTrain
/home1/03491/cmcwhite/libsvm/svm-scale -r atobsc3_full.libsvm1.scale_parameters libsvm_xeo_labeled_test_1 > libsvm_xeo_labeled_test_1_scaleByTrain
/home1/03491/cmcwhite/libsvm/svm-scale -r atobsc3_full.libsvm1.scale_parameters libsvm_xep_labeled_test_1 > libsvm_xep_labeled_test_1_scaleByTrain
/home1/03491/cmcwhite/libsvm/svm-scale -r atobsc3_full.libsvm1.scale_parameters libsvm_xeq_labeled_test_1 > libsvm_xeq_labeled_test_1_scaleByTrain
/home1/03491/cmcwhite/libsvm/svm-scale -r atobsc3_full.libsvm1.scale_parameters libsvm_xer_labeled_test_1 > libsvm_xer_labeled_test_1_scaleByTrain
/home1/03491/cmcwhite/libsvm/svm-scale -r atobsc3_full.libsvm1.scale_parameters libsvm_xes_labeled_test_1 > libsvm_xes_labeled_test_1_scaleByTrain
/home1/03491/cmcwhite/libsvm/svm-scale -r atobsc3_full.libsvm1.scale_parameters libsvm_xet_labeled_test_1 > libsvm_xet_labeled_test_1_scaleByTrain
/home1/03491/cmcwhite/libsvm/svm-scale -r atobsc3_full.libsvm1.scale_parameters libsvm_xeu_labeled_test_1 > libsvm_xeu_labeled_test_1_scaleByTrain
/home1/03491/cmcwhite/libsvm/svm-scale -r atobsc3_full.libsvm1.scale_parameters libsvm_xev_labeled_test_1 > libsvm_xev_labeled_test_1_scaleByTrain
/home1/03491/cmcwhite/libsvm/svm-scale -r atobsc3_full.libsvm1.scale_parameters libsvm_xew_labeled_test_1 > libsvm_xew_labeled_test_1_scaleByTrain
/home1/03491/cmcwhite/libsvm/svm-scale -r atobsc3_full.libsvm1.scale_parameters libsvm_xex_labeled_test_1 > libsvm_xex_labeled_test_1_scaleByTrain
/home1/03491/cmcwhite/libsvm/svm-scale -r atobsc3_full.libsvm1.scale_parameters libsvm_xey_labeled_test_1 > libsvm_xey_labeled_test_1_scaleByTrain
/home1/03491/cmcwhite/libsvm/svm-scale -r atobsc3_full.libsvm1.scale_parameters libsvm_xez_labeled_test_1 > libsvm_xez_labeled_test_1_scaleByTrain
/home1/03491/cmcwhite/libsvm/svm-scale -r atobsc3_full.libsvm1.scale_parameters libsvm_xfa_labeled_test_1 > libsvm_xfa_labeled_test_1_scaleByTrain
/home1/03491/cmcwhite/libsvm/svm-scale -r atobsc3_full.libsvm1.scale_parameters libsvm_xfb_labeled_test_1 > libsvm_xfb_labeled_test_1_scaleByTrain
/home1/03491/cmcwhite/libsvm/svm-scale -r atobsc3_full.libsvm1.scale_parameters libsvm_xfc_labeled_test_1 > libsvm_xfc_labeled_test_1_scaleByTrain
/home1/03491/cmcwhite/libsvm/svm-scale -r atobsc3_full.libsvm1.scale_parameters libsvm_xfd_labeled_test_1 > libsvm_xfd_labeled_test_1_scaleByTrain
/home1/03491/cmcwhite/libsvm/svm-scale -r atobsc3_full.libsvm1.scale_parameters libsvm_xfe_labeled_test_1 > libsvm_xfe_labeled_test_1_scaleByTrain
/home1/03491/cmcwhite/libsvm/svm-scale -r atobsc3_full.libsvm1.scale_parameters libsvm_xff_labeled_test_1 > libsvm_xff_labeled_test_1_scaleByTrain
/home1/03491/cmcwhite/libsvm/svm-scale -r atobsc3_full.libsvm1.scale_parameters libsvm_xfg_labeled_test_1 > libsvm_xfg_labeled_test_1_scaleByTrain
/home1/03491/cmcwhite/libsvm/svm-scale -r atobsc3_full.libsvm1.scale_parameters libsvm_xfh_labeled_test_1 > libsvm_xfh_labeled_test_1_scaleByTrain
/home1/03491/cmcwhite/libsvm/svm-scale -r atobsc3_full.libsvm1.scale_parameters libsvm_xfi_labeled_test_1 > libsvm_xfi_labeled_test_1_scaleByTrain
/home1/03491/cmcwhite/libsvm/svm-scale -r atobsc3_full.libsvm1.scale_parameters libsvm_xfj_labeled_test_1 > libsvm_xfj_labeled_test_1_scaleByTrain
/home1/03491/cmcwhite/libsvm/svm-scale -r atobsc3_full.libsvm1.scale_parameters libsvm_xfk_labeled_test_1 > libsvm_xfk_labeled_test_1_scaleByTrain
/home1/03491/cmcwhite/libsvm/svm-scale -r atobsc3_full.libsvm1.scale_parameters libsvm_xfl_labeled_test_1 > libsvm_xfl_labeled_test_1_scaleByTrain
/home1/03491/cmcwhite/libsvm/svm-scale -r atobsc3_full.libsvm1.scale_parameters libsvm_xfm_labeled_test_1 > libsvm_xfm_labeled_test_1_scaleByTrain
/home1/03491/cmcwhite/libsvm/svm-scale -r atobsc3_full.libsvm1.scale_parameters libsvm_xfn_labeled_test_1 > libsvm_xfn_labeled_test_1_scaleByTrain
/home1/03491/cmcwhite/libsvm/svm-scale -r atobsc3_full.libsvm1.scale_parameters libsvm_xfo_labeled_test_1 > libsvm_xfo_labeled_test_1_scaleByTrain
/home1/03491/cmcwhite/libsvm/svm-scale -r atobsc3_full.libsvm1.scale_parameters libsvm_xfp_labeled_test_1 > libsvm_xfp_labeled_test_1_scaleByTrain
/home1/03491/cmcwhite/libsvm/svm-scale -r atobsc3_full.libsvm1.scale_parameters libsvm_xfq_labeled_test_1 > libsvm_xfq_labeled_test_1_scaleByTrain
/home1/03491/cmcwhite/libsvm/svm-scale -r atobsc3_full.libsvm1.scale_parameters libsvm_xfr_labeled_test_1 > libsvm_xfr_labeled_test_1_scaleByTrain
/home1/03491/cmcwhite/libsvm/svm-scale -r atobsc3_full.libsvm1.scale_parameters libsvm_xfs_labeled_test_1 > libsvm_xfs_labeled_test_1_scaleByTrain
/home1/03491/cmcwhite/libsvm/svm-scale -r atobsc3_full.libsvm1.scale_parameters libsvm_xft_labeled_test_1 > libsvm_xft_labeled_test_1_scaleByTrain
/home1/03491/cmcwhite/libsvm/svm-scale -r atobsc3_full.libsvm1.scale_parameters libsvm_xfu_labeled_test_1 > libsvm_xfu_labeled_test_1_scaleByTrain
/home1/03491/cmcwhite/libsvm/svm-scale -r atobsc3_full.libsvm1.scale_parameters libsvm_xfv_labeled_test_1 > libsvm_xfv_labeled_test_1_scaleByTrain
/home1/03491/cmcwhite/libsvm/svm-scale -r atobsc3_full.libsvm1.scale_parameters libsvm_xfw_labeled_test_1 > libsvm_xfw_labeled_test_1_scaleByTrain
/home1/03491/cmcwhite/libsvm/svm-scale -r atobsc3_full.libsvm1.scale_parameters libsvm_xfx_labeled_test_1 > libsvm_xfx_labeled_test_1_scaleByTrain
/home1/03491/cmcwhite/libsvm/svm-scale -r atobsc3_full.libsvm1.scale_parameters libsvm_xfy_labeled_test_1 > libsvm_xfy_labeled_test_1_scaleByTrain
/home1/03491/cmcwhite/libsvm/svm-scale -r atobsc3_full.libsvm1.scale_parameters libsvm_xfz_labeled_test_1 > libsvm_xfz_labeled_test_1_scaleByTrain
/home1/03491/cmcwhite/libsvm/svm-scale -r atobsc3_full.libsvm1.scale_parameters libsvm_xga_labeled_test_1 > libsvm_xga_labeled_test_1_scaleByTrain
/home1/03491/cmcwhite/libsvm/svm-scale -r atobsc3_full.libsvm1.scale_parameters libsvm_xgb_labeled_test_1 > libsvm_xgb_labeled_test_1_scaleByTrain
/home1/03491/cmcwhite/libsvm/svm-scale -r atobsc3_full.libsvm1.scale_parameters libsvm_xgc_labeled_test_1 > libsvm_xgc_labeled_test_1_scaleByTrain
/home1/03491/cmcwhite/libsvm/svm-scale -r atobsc3_full.libsvm1.scale_parameters libsvm_xgd_labeled_test_1 > libsvm_xgd_labeled_test_1_scaleByTrain
/home1/03491/cmcwhite/libsvm/svm-scale -r atobsc3_full.libsvm1.scale_parameters libsvm_xge_labeled_test_1 > libsvm_xge_labeled_test_1_scaleByTrain
/home1/03491/cmcwhite/libsvm/svm-scale -r atobsc3_full.libsvm1.scale_parameters libsvm_xgf_labeled_test_1 > libsvm_xgf_labeled_test_1_scaleByTrain
/home1/03491/cmcwhite/libsvm/svm-scale -r atobsc3_full.libsvm1.scale_parameters libsvm_xgg_labeled_test_1 > libsvm_xgg_labeled_test_1_scaleByTrain
/home1/03491/cmcwhite/libsvm/svm-scale -r atobsc3_full.libsvm1.scale_parameters libsvm_xgh_labeled_test_1 > libsvm_xgh_labeled_test_1_scaleByTrain
/home1/03491/cmcwhite/libsvm/svm-scale -r atobsc3_full.libsvm1.scale_parameters libsvm_xgi_labeled_test_1 > libsvm_xgi_labeled_test_1_scaleByTrain
/home1/03491/cmcwhite/libsvm/svm-scale -r atobsc3_full.libsvm1.scale_parameters libsvm_xgj_labeled_test_1 > libsvm_xgj_labeled_test_1_scaleByTrain
/home1/03491/cmcwhite/libsvm/svm-scale -r atobsc3_full.libsvm1.scale_parameters libsvm_xgk_labeled_test_1 > libsvm_xgk_labeled_test_1_scaleByTrain
/home1/03491/cmcwhite/libsvm/svm-scale -r atobsc3_full.libsvm1.scale_parameters libsvm_xgl_labeled_test_1 > libsvm_xgl_labeled_test_1_scaleByTrain
/home1/03491/cmcwhite/libsvm/svm-scale -r atobsc3_full.libsvm1.scale_parameters libsvm_xgm_labeled_test_1 > libsvm_xgm_labeled_test_1_scaleByTrain
/home1/03491/cmcwhite/libsvm/svm-scale -r atobsc3_full.libsvm1.scale_parameters libsvm_xgn_labeled_test_1 > libsvm_xgn_labeled_test_1_scaleByTrain
/home1/03491/cmcwhite/libsvm/svm-scale -r atobsc3_full.libsvm1.scale_parameters libsvm_xgo_labeled_test_1 > libsvm_xgo_labeled_test_1_scaleByTrain
/home1/03491/cmcwhite/libsvm/svm-scale -r atobsc3_full.libsvm1.scale_parameters libsvm_xgp_labeled_test_1 > libsvm_xgp_labeled_test_1_scaleByTrain
/home1/03491/cmcwhite/libsvm/svm-scale -r atobsc3_full.libsvm1.scale_parameters libsvm_xgq_labeled_test_1 > libsvm_xgq_labeled_test_1_scaleByTrain
/home1/03491/cmcwhite/libsvm/svm-scale -r atobsc3_full.libsvm1.scale_parameters libsvm_xgr_labeled_test_1 > libsvm_xgr_labeled_test_1_scaleByTrain
/home1/03491/cmcwhite/libsvm/svm-scale -r atobsc3_full.libsvm1.scale_parameters libsvm_xgs_labeled_test_1 > libsvm_xgs_labeled_test_1_scaleByTrain
/home1/03491/cmcwhite/libsvm/svm-scale -r atobsc3_full.libsvm1.scale_parameters libsvm_xgt_labeled_test_1 > libsvm_xgt_labeled_test_1_scaleByTrain
/home1/03491/cmcwhite/libsvm/svm-scale -r atobsc3_full.libsvm1.scale_parameters libsvm_xgu_labeled_test_1 > libsvm_xgu_labeled_test_1_scaleByTrain
/home1/03491/cmcwhite/libsvm/svm-scale -r atobsc3_full.libsvm1.scale_parameters libsvm_xgv_labeled_test_1 > libsvm_xgv_labeled_test_1_scaleByTrain
/home1/03491/cmcwhite/libsvm/svm-scale -r atobsc3_full.libsvm1.scale_parameters libsvm_xgw_labeled_test_1 > libsvm_xgw_labeled_test_1_scaleByTrain
/home1/03491/cmcwhite/libsvm/svm-scale -r atobsc3_full.libsvm1.scale_parameters libsvm_xgx_labeled_test_1 > libsvm_xgx_labeled_test_1_scaleByTrain
/home1/03491/cmcwhite/libsvm/svm-scale -r atobsc3_full.libsvm1.scale_parameters libsvm_xgy_labeled_test_1 > libsvm_xgy_labeled_test_1_scaleByTrain
/home1/03491/cmcwhite/libsvm/svm-scale -r atobsc3_full.libsvm1.scale_parameters libsvm_xgz_labeled_test_1 > libsvm_xgz_labeled_test_1_scaleByTrain
/home1/03491/cmcwhite/libsvm/svm-scale -r atobsc3_full.libsvm1.scale_parameters libsvm_xha_labeled_test_1 > libsvm_xha_labeled_test_1_scaleByTrain
/home1/03491/cmcwhite/libsvm/svm-scale -r atobsc3_full.libsvm1.scale_parameters libsvm_xhb_labeled_test_1 > libsvm_xhb_labeled_test_1_scaleByTrain
/home1/03491/cmcwhite/libsvm/svm-scale -r atobsc3_full.libsvm1.scale_parameters libsvm_xhc_labeled_test_1 > libsvm_xhc_labeled_test_1_scaleByTrain
/home1/03491/cmcwhite/libsvm/svm-scale -r atobsc3_full.libsvm1.scale_parameters libsvm_xhd_labeled_test_1 > libsvm_xhd_labeled_test_1_scaleByTrain
/home1/03491/cmcwhite/libsvm/svm-scale -r atobsc3_full.libsvm1.scale_parameters libsvm_xhe_labeled_test_1 > libsvm_xhe_labeled_test_1_scaleByTrain
/home1/03491/cmcwhite/libsvm/svm-scale -r atobsc3_full.libsvm1.scale_parameters libsvm_xhf_labeled_test_1 > libsvm_xhf_labeled_test_1_scaleByTrain
/home1/03491/cmcwhite/libsvm/svm-scale -r atobsc3_full.libsvm1.scale_parameters libsvm_xhg_labeled_test_1 > libsvm_xhg_labeled_test_1_scaleByTrain
/home1/03491/cmcwhite/libsvm/svm-scale -r atobsc3_full.libsvm1.scale_parameters libsvm_xhh_labeled_test_1 > libsvm_xhh_labeled_test_1_scaleByTrain
/home1/03491/cmcwhite/libsvm/svm-scale -r atobsc3_full.libsvm1.scale_parameters libsvm_xhi_labeled_test_1 > libsvm_xhi_labeled_test_1_scaleByTrain
/home1/03491/cmcwhite/libsvm/svm-scale -r atobsc3_full.libsvm1.scale_parameters libsvm_xhj_labeled_test_1 > libsvm_xhj_labeled_test_1_scaleByTrain
/home1/03491/cmcwhite/libsvm/svm-scale -r atobsc3_full.libsvm1.scale_parameters libsvm_xhk_labeled_test_1 > libsvm_xhk_labeled_test_1_scaleByTrain
/home1/03491/cmcwhite/libsvm/svm-scale -r atobsc3_full.libsvm1.scale_parameters libsvm_xhl_labeled_test_1 > libsvm_xhl_labeled_test_1_scaleByTrain
/home1/03491/cmcwhite/libsvm/svm-scale -r atobsc3_full.libsvm1.scale_parameters libsvm_xhm_labeled_test_1 > libsvm_xhm_labeled_test_1_scaleByTrain
/home1/03491/cmcwhite/libsvm/svm-scale -r atobsc3_full.libsvm1.scale_parameters libsvm_xhn_labeled_test_1 > libsvm_xhn_labeled_test_1_scaleByTrain
/home1/03491/cmcwhite/libsvm/svm-scale -r atobsc3_full.libsvm1.scale_parameters libsvm_xho_labeled_test_1 > libsvm_xho_labeled_test_1_scaleByTrain
/home1/03491/cmcwhite/libsvm/svm-scale -r atobsc3_full.libsvm1.scale_parameters libsvm_xhp_labeled_test_1 > libsvm_xhp_labeled_test_1_scaleByTrain
/home1/03491/cmcwhite/libsvm/svm-scale -r atobsc3_full.libsvm1.scale_parameters libsvm_xhq_labeled_test_1 > libsvm_xhq_labeled_test_1_scaleByTrain
/home1/03491/cmcwhite/libsvm/svm-scale -r atobsc3_full.libsvm1.scale_parameters libsvm_xhr_labeled_test_1 > libsvm_xhr_labeled_test_1_scaleByTrain
/home1/03491/cmcwhite/libsvm/svm-scale -r atobsc3_full.libsvm1.scale_parameters libsvm_xhs_labeled_test_1 > libsvm_xhs_labeled_test_1_scaleByTrain
/home1/03491/cmcwhite/libsvm/svm-scale -r atobsc3_full.libsvm1.scale_parameters libsvm_xht_labeled_test_1 > libsvm_xht_labeled_test_1_scaleByTrain
