grep -e ",0.0$" xaa_labeled_test > xaa_labeled_test_0
grep -e ",0.0$" xab_labeled_test > xab_labeled_test_0
grep -e ",0.0$" xac_labeled_test > xac_labeled_test_0
grep -e ",0.0$" xad_labeled_test > xad_labeled_test_0
grep -e ",0.0$" xae_labeled_test > xae_labeled_test_0
grep -e ",0.0$" xaf_labeled_test > xaf_labeled_test_0
grep -e ",0.0$" xag_labeled_test > xag_labeled_test_0
grep -e ",0.0$" xah_labeled_test > xah_labeled_test_0
grep -e ",0.0$" xai_labeled_test > xai_labeled_test_0
grep -e ",0.0$" xaj_labeled_test > xaj_labeled_test_0
grep -e ",0.0$" xak_labeled_test > xak_labeled_test_0
grep -e ",0.0$" xal_labeled_test > xal_labeled_test_0
grep -e ",0.0$" xam_labeled_test > xam_labeled_test_0
grep -e ",0.0$" xan_labeled_test > xan_labeled_test_0
grep -e ",0.0$" xao_labeled_test > xao_labeled_test_0
grep -e ",0.0$" xap_labeled_test > xap_labeled_test_0
grep -e ",0.0$" xaq_labeled_test > xaq_labeled_test_0
grep -e ",0.0$" xar_labeled_test > xar_labeled_test_0
grep -e ",0.0$" xas_labeled_test > xas_labeled_test_0
grep -e ",0.0$" xat_labeled_test > xat_labeled_test_0
grep -e ",0.0$" xau_labeled_test > xau_labeled_test_0
grep -e ",0.0$" xav_labeled_test > xav_labeled_test_0
grep -e ",0.0$" xaw_labeled_test > xaw_labeled_test_0
grep -e ",0.0$" xax_labeled_test > xax_labeled_test_0
grep -e ",0.0$" xay_labeled_test > xay_labeled_test_0
grep -e ",0.0$" xaz_labeled_test > xaz_labeled_test_0
grep -e ",0.0$" xba_labeled_test > xba_labeled_test_0
grep -e ",0.0$" xbb_labeled_test > xbb_labeled_test_0
grep -e ",0.0$" xbc_labeled_test > xbc_labeled_test_0
grep -e ",0.0$" xbd_labeled_test > xbd_labeled_test_0
grep -e ",0.0$" xbe_labeled_test > xbe_labeled_test_0
grep -e ",0.0$" xbf_labeled_test > xbf_labeled_test_0
grep -e ",0.0$" xbg_labeled_test > xbg_labeled_test_0
grep -e ",0.0$" xbh_labeled_test > xbh_labeled_test_0
grep -e ",0.0$" xbi_labeled_test > xbi_labeled_test_0
grep -e ",0.0$" xbj_labeled_test > xbj_labeled_test_0
grep -e ",0.0$" xbk_labeled_test > xbk_labeled_test_0
grep -e ",0.0$" xbl_labeled_test > xbl_labeled_test_0
grep -e ",0.0$" xbm_labeled_test > xbm_labeled_test_0
grep -e ",0.0$" xbn_labeled_test > xbn_labeled_test_0
grep -e ",0.0$" xbo_labeled_test > xbo_labeled_test_0
grep -e ",0.0$" xbp_labeled_test > xbp_labeled_test_0
grep -e ",0.0$" xbq_labeled_test > xbq_labeled_test_0
grep -e ",0.0$" xbr_labeled_test > xbr_labeled_test_0
grep -e ",0.0$" xbs_labeled_test > xbs_labeled_test_0
grep -e ",0.0$" xbt_labeled_test > xbt_labeled_test_0
grep -e ",0.0$" xbu_labeled_test > xbu_labeled_test_0
grep -e ",0.0$" xbv_labeled_test > xbv_labeled_test_0
grep -e ",0.0$" xbw_labeled_test > xbw_labeled_test_0
grep -e ",0.0$" xbx_labeled_test > xbx_labeled_test_0
grep -e ",0.0$" xby_labeled_test > xby_labeled_test_0
grep -e ",0.0$" xbz_labeled_test > xbz_labeled_test_0
grep -e ",0.0$" xca_labeled_test > xca_labeled_test_0
grep -e ",0.0$" xcb_labeled_test > xcb_labeled_test_0
grep -e ",0.0$" xcc_labeled_test > xcc_labeled_test_0
grep -e ",0.0$" xcd_labeled_test > xcd_labeled_test_0
grep -e ",0.0$" xce_labeled_test > xce_labeled_test_0
grep -e ",0.0$" xcf_labeled_test > xcf_labeled_test_0
grep -e ",0.0$" xcg_labeled_test > xcg_labeled_test_0
grep -e ",0.0$" xch_labeled_test > xch_labeled_test_0
grep -e ",0.0$" xci_labeled_test > xci_labeled_test_0
grep -e ",0.0$" xcj_labeled_test > xcj_labeled_test_0
grep -e ",0.0$" xck_labeled_test > xck_labeled_test_0
grep -e ",0.0$" xcl_labeled_test > xcl_labeled_test_0
grep -e ",0.0$" xcm_labeled_test > xcm_labeled_test_0
grep -e ",0.0$" xcn_labeled_test > xcn_labeled_test_0
grep -e ",0.0$" xco_labeled_test > xco_labeled_test_0
grep -e ",0.0$" xcp_labeled_test > xcp_labeled_test_0
grep -e ",0.0$" xcq_labeled_test > xcq_labeled_test_0
grep -e ",0.0$" xcr_labeled_test > xcr_labeled_test_0
grep -e ",0.0$" xcs_labeled_test > xcs_labeled_test_0
grep -e ",0.0$" xct_labeled_test > xct_labeled_test_0
grep -e ",0.0$" xcu_labeled_test > xcu_labeled_test_0
grep -e ",0.0$" xcv_labeled_test > xcv_labeled_test_0
grep -e ",0.0$" xcw_labeled_test > xcw_labeled_test_0
grep -e ",0.0$" xcx_labeled_test > xcx_labeled_test_0
grep -e ",0.0$" xcy_labeled_test > xcy_labeled_test_0
grep -e ",0.0$" xcz_labeled_test > xcz_labeled_test_0
grep -e ",0.0$" xda_labeled_test > xda_labeled_test_0
grep -e ",0.0$" xdb_labeled_test > xdb_labeled_test_0
grep -e ",0.0$" xdc_labeled_test > xdc_labeled_test_0
grep -e ",0.0$" xdd_labeled_test > xdd_labeled_test_0
grep -e ",0.0$" xde_labeled_test > xde_labeled_test_0
grep -e ",0.0$" xdf_labeled_test > xdf_labeled_test_0
grep -e ",0.0$" xdg_labeled_test > xdg_labeled_test_0
grep -e ",0.0$" xdh_labeled_test > xdh_labeled_test_0
grep -e ",0.0$" xdi_labeled_test > xdi_labeled_test_0
grep -e ",0.0$" xdj_labeled_test > xdj_labeled_test_0
grep -e ",0.0$" xdk_labeled_test > xdk_labeled_test_0
grep -e ",0.0$" xdl_labeled_test > xdl_labeled_test_0
grep -e ",0.0$" xdm_labeled_test > xdm_labeled_test_0
grep -e ",0.0$" xdn_labeled_test > xdn_labeled_test_0
grep -e ",0.0$" xdo_labeled_test > xdo_labeled_test_0
grep -e ",0.0$" xdp_labeled_test > xdp_labeled_test_0
grep -e ",0.0$" xdq_labeled_test > xdq_labeled_test_0
grep -e ",0.0$" xdr_labeled_test > xdr_labeled_test_0
grep -e ",0.0$" xds_labeled_test > xds_labeled_test_0
grep -e ",0.0$" xdt_labeled_test > xdt_labeled_test_0
grep -e ",0.0$" xdu_labeled_test > xdu_labeled_test_0
grep -e ",0.0$" xdv_labeled_test > xdv_labeled_test_0
grep -e ",0.0$" xdw_labeled_test > xdw_labeled_test_0
grep -e ",0.0$" xdx_labeled_test > xdx_labeled_test_0
grep -e ",0.0$" xdy_labeled_test > xdy_labeled_test_0
grep -e ",0.0$" xdz_labeled_test > xdz_labeled_test_0
grep -e ",0.0$" xea_labeled_test > xea_labeled_test_0
grep -e ",0.0$" xeb_labeled_test > xeb_labeled_test_0
grep -e ",0.0$" xec_labeled_test > xec_labeled_test_0
grep -e ",0.0$" xed_labeled_test > xed_labeled_test_0
grep -e ",0.0$" xee_labeled_test > xee_labeled_test_0
grep -e ",0.0$" xef_labeled_test > xef_labeled_test_0
grep -e ",0.0$" xeg_labeled_test > xeg_labeled_test_0
grep -e ",0.0$" xeh_labeled_test > xeh_labeled_test_0
grep -e ",0.0$" xei_labeled_test > xei_labeled_test_0
grep -e ",0.0$" xej_labeled_test > xej_labeled_test_0
grep -e ",0.0$" xek_labeled_test > xek_labeled_test_0
grep -e ",0.0$" xel_labeled_test > xel_labeled_test_0
grep -e ",0.0$" xem_labeled_test > xem_labeled_test_0
grep -e ",0.0$" xen_labeled_test > xen_labeled_test_0
grep -e ",0.0$" xeo_labeled_test > xeo_labeled_test_0
grep -e ",0.0$" xep_labeled_test > xep_labeled_test_0
grep -e ",0.0$" xeq_labeled_test > xeq_labeled_test_0
grep -e ",0.0$" xer_labeled_test > xer_labeled_test_0
grep -e ",0.0$" xes_labeled_test > xes_labeled_test_0
grep -e ",0.0$" xet_labeled_test > xet_labeled_test_0
grep -e ",0.0$" xeu_labeled_test > xeu_labeled_test_0
grep -e ",0.0$" xev_labeled_test > xev_labeled_test_0
grep -e ",0.0$" xew_labeled_test > xew_labeled_test_0
grep -e ",0.0$" xex_labeled_test > xex_labeled_test_0
grep -e ",0.0$" xey_labeled_test > xey_labeled_test_0
grep -e ",0.0$" xez_labeled_test > xez_labeled_test_0
grep -e ",0.0$" xfa_labeled_test > xfa_labeled_test_0
grep -e ",0.0$" xfb_labeled_test > xfb_labeled_test_0
grep -e ",0.0$" xfc_labeled_test > xfc_labeled_test_0
grep -e ",0.0$" xfd_labeled_test > xfd_labeled_test_0
grep -e ",0.0$" xfe_labeled_test > xfe_labeled_test_0
grep -e ",0.0$" xff_labeled_test > xff_labeled_test_0
grep -e ",0.0$" xfg_labeled_test > xfg_labeled_test_0
grep -e ",0.0$" xfh_labeled_test > xfh_labeled_test_0
grep -e ",0.0$" xfi_labeled_test > xfi_labeled_test_0
grep -e ",0.0$" xfj_labeled_test > xfj_labeled_test_0
grep -e ",0.0$" xfk_labeled_test > xfk_labeled_test_0
grep -e ",0.0$" xfl_labeled_test > xfl_labeled_test_0
grep -e ",0.0$" xfm_labeled_test > xfm_labeled_test_0
grep -e ",0.0$" xfn_labeled_test > xfn_labeled_test_0
grep -e ",0.0$" xfo_labeled_test > xfo_labeled_test_0
grep -e ",0.0$" xfp_labeled_test > xfp_labeled_test_0
grep -e ",0.0$" xfq_labeled_test > xfq_labeled_test_0
grep -e ",0.0$" xfr_labeled_test > xfr_labeled_test_0
grep -e ",0.0$" xfs_labeled_test > xfs_labeled_test_0
grep -e ",0.0$" xft_labeled_test > xft_labeled_test_0
grep -e ",0.0$" xfu_labeled_test > xfu_labeled_test_0
grep -e ",0.0$" xfv_labeled_test > xfv_labeled_test_0
grep -e ",0.0$" xfw_labeled_test > xfw_labeled_test_0
grep -e ",0.0$" xfx_labeled_test > xfx_labeled_test_0
grep -e ",0.0$" xfy_labeled_test > xfy_labeled_test_0
grep -e ",0.0$" xfz_labeled_test > xfz_labeled_test_0
grep -e ",0.0$" xga_labeled_test > xga_labeled_test_0
grep -e ",0.0$" xgb_labeled_test > xgb_labeled_test_0
grep -e ",0.0$" xgc_labeled_test > xgc_labeled_test_0
grep -e ",0.0$" xgd_labeled_test > xgd_labeled_test_0
grep -e ",0.0$" xge_labeled_test > xge_labeled_test_0
grep -e ",0.0$" xgf_labeled_test > xgf_labeled_test_0
grep -e ",0.0$" xgg_labeled_test > xgg_labeled_test_0
grep -e ",0.0$" xgh_labeled_test > xgh_labeled_test_0
grep -e ",0.0$" xgi_labeled_test > xgi_labeled_test_0
grep -e ",0.0$" xgj_labeled_test > xgj_labeled_test_0
grep -e ",0.0$" xgk_labeled_test > xgk_labeled_test_0
grep -e ",0.0$" xgl_labeled_test > xgl_labeled_test_0
grep -e ",0.0$" xgm_labeled_test > xgm_labeled_test_0
grep -e ",0.0$" xgn_labeled_test > xgn_labeled_test_0
grep -e ",0.0$" xgo_labeled_test > xgo_labeled_test_0
grep -e ",0.0$" xgp_labeled_test > xgp_labeled_test_0
grep -e ",0.0$" xgq_labeled_test > xgq_labeled_test_0
grep -e ",0.0$" xgr_labeled_test > xgr_labeled_test_0
grep -e ",0.0$" xgs_labeled_test > xgs_labeled_test_0
grep -e ",0.0$" xgt_labeled_test > xgt_labeled_test_0
grep -e ",0.0$" xgu_labeled_test > xgu_labeled_test_0
grep -e ",0.0$" xgv_labeled_test > xgv_labeled_test_0
grep -e ",0.0$" xgw_labeled_test > xgw_labeled_test_0
grep -e ",0.0$" xgx_labeled_test > xgx_labeled_test_0
grep -e ",0.0$" xgy_labeled_test > xgy_labeled_test_0
grep -e ",0.0$" xgz_labeled_test > xgz_labeled_test_0
grep -e ",0.0$" xha_labeled_test > xha_labeled_test_0
grep -e ",0.0$" xhb_labeled_test > xhb_labeled_test_0
grep -e ",0.0$" xhc_labeled_test > xhc_labeled_test_0
grep -e ",0.0$" xhd_labeled_test > xhd_labeled_test_0
grep -e ",0.0$" xhe_labeled_test > xhe_labeled_test_0
grep -e ",0.0$" xhf_labeled_test > xhf_labeled_test_0
grep -e ",0.0$" xhg_labeled_test > xhg_labeled_test_0
grep -e ",0.0$" xhh_labeled_test > xhh_labeled_test_0
grep -e ",0.0$" xhi_labeled_test > xhi_labeled_test_0
grep -e ",0.0$" xhj_labeled_test > xhj_labeled_test_0
grep -e ",0.0$" xhk_labeled_test > xhk_labeled_test_0
grep -e ",0.0$" xhl_labeled_test > xhl_labeled_test_0
grep -e ",0.0$" xhm_labeled_test > xhm_labeled_test_0
grep -e ",0.0$" xhn_labeled_test > xhn_labeled_test_0
grep -e ",0.0$" xho_labeled_test > xho_labeled_test_0
grep -e ",0.0$" xhp_labeled_test > xhp_labeled_test_0
grep -e ",0.0$" xhq_labeled_test > xhq_labeled_test_0
grep -e ",0.0$" xhr_labeled_test > xhr_labeled_test_0
grep -e ",0.0$" xhs_labeled_test > xhs_labeled_test_0
grep -e ",0.0$" xht_labeled_test > xht_labeled_test_0
