bash ../../features/convert_feature2libsvm.sh xaa_labeled_u30test_1
bash ../../features/convert_feature2libsvm.sh xab_labeled_u30test_1
bash ../../features/convert_feature2libsvm.sh xac_labeled_u30test_1
bash ../../features/convert_feature2libsvm.sh xad_labeled_u30test_1
bash ../../features/convert_feature2libsvm.sh xae_labeled_u30test_1
bash ../../features/convert_feature2libsvm.sh xaf_labeled_u30test_1
bash ../../features/convert_feature2libsvm.sh xag_labeled_u30test_1
bash ../../features/convert_feature2libsvm.sh xah_labeled_u30test_1
bash ../../features/convert_feature2libsvm.sh xai_labeled_u30test_1
bash ../../features/convert_feature2libsvm.sh xaj_labeled_u30test_1
bash ../../features/convert_feature2libsvm.sh xak_labeled_u30test_1
bash ../../features/convert_feature2libsvm.sh xal_labeled_u30test_1
bash ../../features/convert_feature2libsvm.sh xam_labeled_u30test_1
bash ../../features/convert_feature2libsvm.sh xan_labeled_u30test_1
bash ../../features/convert_feature2libsvm.sh xao_labeled_u30test_1
bash ../../features/convert_feature2libsvm.sh xap_labeled_u30test_1
bash ../../features/convert_feature2libsvm.sh xaq_labeled_u30test_1
bash ../../features/convert_feature2libsvm.sh xar_labeled_u30test_1
bash ../../features/convert_feature2libsvm.sh xas_labeled_u30test_1
bash ../../features/convert_feature2libsvm.sh xat_labeled_u30test_1
bash ../../features/convert_feature2libsvm.sh xau_labeled_u30test_1
bash ../../features/convert_feature2libsvm.sh xav_labeled_u30test_1
bash ../../features/convert_feature2libsvm.sh xaw_labeled_u30test_1
bash ../../features/convert_feature2libsvm.sh xax_labeled_u30test_1
bash ../../features/convert_feature2libsvm.sh xay_labeled_u30test_1
bash ../../features/convert_feature2libsvm.sh xaz_labeled_u30test_1
bash ../../features/convert_feature2libsvm.sh xba_labeled_u30test_1
bash ../../features/convert_feature2libsvm.sh xbb_labeled_u30test_1
bash ../../features/convert_feature2libsvm.sh xbc_labeled_u30test_1
bash ../../features/convert_feature2libsvm.sh xbd_labeled_u30test_1
bash ../../features/convert_feature2libsvm.sh xbe_labeled_u30test_1
bash ../../features/convert_feature2libsvm.sh xbf_labeled_u30test_1
bash ../../features/convert_feature2libsvm.sh xbg_labeled_u30test_1
bash ../../features/convert_feature2libsvm.sh xbh_labeled_u30test_1
bash ../../features/convert_feature2libsvm.sh xbi_labeled_u30test_1
bash ../../features/convert_feature2libsvm.sh xbj_labeled_u30test_1
bash ../../features/convert_feature2libsvm.sh xbk_labeled_u30test_1
bash ../../features/convert_feature2libsvm.sh xbl_labeled_u30test_1
bash ../../features/convert_feature2libsvm.sh xbm_labeled_u30test_1
bash ../../features/convert_feature2libsvm.sh xbn_labeled_u30test_1
bash ../../features/convert_feature2libsvm.sh xbo_labeled_u30test_1
bash ../../features/convert_feature2libsvm.sh xbp_labeled_u30test_1
bash ../../features/convert_feature2libsvm.sh xbq_labeled_u30test_1
bash ../../features/convert_feature2libsvm.sh xbr_labeled_u30test_1
bash ../../features/convert_feature2libsvm.sh xbs_labeled_u30test_1
bash ../../features/convert_feature2libsvm.sh xbt_labeled_u30test_1
bash ../../features/convert_feature2libsvm.sh xbu_labeled_u30test_1
bash ../../features/convert_feature2libsvm.sh xbv_labeled_u30test_1
bash ../../features/convert_feature2libsvm.sh xbw_labeled_u30test_1
bash ../../features/convert_feature2libsvm.sh xbx_labeled_u30test_1
bash ../../features/convert_feature2libsvm.sh xby_labeled_u30test_1
bash ../../features/convert_feature2libsvm.sh xbz_labeled_u30test_1
bash ../../features/convert_feature2libsvm.sh xca_labeled_u30test_1
bash ../../features/convert_feature2libsvm.sh xcb_labeled_u30test_1
bash ../../features/convert_feature2libsvm.sh xcc_labeled_u30test_1
bash ../../features/convert_feature2libsvm.sh xcd_labeled_u30test_1
bash ../../features/convert_feature2libsvm.sh xce_labeled_u30test_1
bash ../../features/convert_feature2libsvm.sh xcf_labeled_u30test_1
bash ../../features/convert_feature2libsvm.sh xcg_labeled_u30test_1
bash ../../features/convert_feature2libsvm.sh xch_labeled_u30test_1
bash ../../features/convert_feature2libsvm.sh xci_labeled_u30test_1
bash ../../features/convert_feature2libsvm.sh xcj_labeled_u30test_1
bash ../../features/convert_feature2libsvm.sh xck_labeled_u30test_1
bash ../../features/convert_feature2libsvm.sh xcl_labeled_u30test_1
bash ../../features/convert_feature2libsvm.sh xcm_labeled_u30test_1
bash ../../features/convert_feature2libsvm.sh xcn_labeled_u30test_1
bash ../../features/convert_feature2libsvm.sh xco_labeled_u30test_1
bash ../../features/convert_feature2libsvm.sh xcp_labeled_u30test_1
bash ../../features/convert_feature2libsvm.sh xcq_labeled_u30test_1
bash ../../features/convert_feature2libsvm.sh xcr_labeled_u30test_1
bash ../../features/convert_feature2libsvm.sh xcs_labeled_u30test_1
bash ../../features/convert_feature2libsvm.sh xct_labeled_u30test_1
bash ../../features/convert_feature2libsvm.sh xcu_labeled_u30test_1
bash ../../features/convert_feature2libsvm.sh xcv_labeled_u30test_1
bash ../../features/convert_feature2libsvm.sh xcw_labeled_u30test_1
bash ../../features/convert_feature2libsvm.sh xcx_labeled_u30test_1
bash ../../features/convert_feature2libsvm.sh xcy_labeled_u30test_1
bash ../../features/convert_feature2libsvm.sh xcz_labeled_u30test_1
bash ../../features/convert_feature2libsvm.sh xda_labeled_u30test_1
bash ../../features/convert_feature2libsvm.sh xdb_labeled_u30test_1
bash ../../features/convert_feature2libsvm.sh xdc_labeled_u30test_1
bash ../../features/convert_feature2libsvm.sh xdd_labeled_u30test_1
bash ../../features/convert_feature2libsvm.sh xde_labeled_u30test_1
bash ../../features/convert_feature2libsvm.sh xdf_labeled_u30test_1
bash ../../features/convert_feature2libsvm.sh xdg_labeled_u30test_1
bash ../../features/convert_feature2libsvm.sh xdh_labeled_u30test_1
bash ../../features/convert_feature2libsvm.sh xdi_labeled_u30test_1
bash ../../features/convert_feature2libsvm.sh xdj_labeled_u30test_1
bash ../../features/convert_feature2libsvm.sh xdk_labeled_u30test_1
bash ../../features/convert_feature2libsvm.sh xdl_labeled_u30test_1
bash ../../features/convert_feature2libsvm.sh xdm_labeled_u30test_1
bash ../../features/convert_feature2libsvm.sh xdn_labeled_u30test_1
bash ../../features/convert_feature2libsvm.sh xdo_labeled_u30test_1
bash ../../features/convert_feature2libsvm.sh xdp_labeled_u30test_1
bash ../../features/convert_feature2libsvm.sh xdq_labeled_u30test_1
bash ../../features/convert_feature2libsvm.sh xdr_labeled_u30test_1
bash ../../features/convert_feature2libsvm.sh xds_labeled_u30test_1
bash ../../features/convert_feature2libsvm.sh xdt_labeled_u30test_1
bash ../../features/convert_feature2libsvm.sh xdu_labeled_u30test_1
bash ../../features/convert_feature2libsvm.sh xdv_labeled_u30test_1
bash ../../features/convert_feature2libsvm.sh xdw_labeled_u30test_1
bash ../../features/convert_feature2libsvm.sh xdx_labeled_u30test_1
bash ../../features/convert_feature2libsvm.sh xdy_labeled_u30test_1
bash ../../features/convert_feature2libsvm.sh xdz_labeled_u30test_1
bash ../../features/convert_feature2libsvm.sh xea_labeled_u30test_1
bash ../../features/convert_feature2libsvm.sh xeb_labeled_u30test_1
bash ../../features/convert_feature2libsvm.sh xec_labeled_u30test_1
bash ../../features/convert_feature2libsvm.sh xed_labeled_u30test_1
bash ../../features/convert_feature2libsvm.sh xee_labeled_u30test_1
bash ../../features/convert_feature2libsvm.sh xef_labeled_u30test_1
bash ../../features/convert_feature2libsvm.sh xeg_labeled_u30test_1
bash ../../features/convert_feature2libsvm.sh xeh_labeled_u30test_1
bash ../../features/convert_feature2libsvm.sh xei_labeled_u30test_1
bash ../../features/convert_feature2libsvm.sh xej_labeled_u30test_1
bash ../../features/convert_feature2libsvm.sh xek_labeled_u30test_1
bash ../../features/convert_feature2libsvm.sh xel_labeled_u30test_1
bash ../../features/convert_feature2libsvm.sh xem_labeled_u30test_1
bash ../../features/convert_feature2libsvm.sh xen_labeled_u30test_1
bash ../../features/convert_feature2libsvm.sh xeo_labeled_u30test_1
bash ../../features/convert_feature2libsvm.sh xep_labeled_u30test_1
bash ../../features/convert_feature2libsvm.sh xeq_labeled_u30test_1
bash ../../features/convert_feature2libsvm.sh xer_labeled_u30test_1
bash ../../features/convert_feature2libsvm.sh xes_labeled_u30test_1
bash ../../features/convert_feature2libsvm.sh xet_labeled_u30test_1
bash ../../features/convert_feature2libsvm.sh xeu_labeled_u30test_1
bash ../../features/convert_feature2libsvm.sh xev_labeled_u30test_1
bash ../../features/convert_feature2libsvm.sh xew_labeled_u30test_1
bash ../../features/convert_feature2libsvm.sh xex_labeled_u30test_1
bash ../../features/convert_feature2libsvm.sh xey_labeled_u30test_1
bash ../../features/convert_feature2libsvm.sh xez_labeled_u30test_1
bash ../../features/convert_feature2libsvm.sh xfa_labeled_u30test_1
bash ../../features/convert_feature2libsvm.sh xfb_labeled_u30test_1
bash ../../features/convert_feature2libsvm.sh xfc_labeled_u30test_1
bash ../../features/convert_feature2libsvm.sh xfd_labeled_u30test_1
bash ../../features/convert_feature2libsvm.sh xfe_labeled_u30test_1
bash ../../features/convert_feature2libsvm.sh xff_labeled_u30test_1
bash ../../features/convert_feature2libsvm.sh xfg_labeled_u30test_1
bash ../../features/convert_feature2libsvm.sh xfh_labeled_u30test_1
bash ../../features/convert_feature2libsvm.sh xfi_labeled_u30test_1
bash ../../features/convert_feature2libsvm.sh xfj_labeled_u30test_1
bash ../../features/convert_feature2libsvm.sh xfk_labeled_u30test_1
bash ../../features/convert_feature2libsvm.sh xfl_labeled_u30test_1
bash ../../features/convert_feature2libsvm.sh xfm_labeled_u30test_1
bash ../../features/convert_feature2libsvm.sh xfn_labeled_u30test_1
bash ../../features/convert_feature2libsvm.sh xfo_labeled_u30test_1
bash ../../features/convert_feature2libsvm.sh xfp_labeled_u30test_1
bash ../../features/convert_feature2libsvm.sh xfq_labeled_u30test_1
bash ../../features/convert_feature2libsvm.sh xfr_labeled_u30test_1
bash ../../features/convert_feature2libsvm.sh xfs_labeled_u30test_1
bash ../../features/convert_feature2libsvm.sh xft_labeled_u30test_1
bash ../../features/convert_feature2libsvm.sh xfu_labeled_u30test_1
bash ../../features/convert_feature2libsvm.sh xfv_labeled_u30test_1
bash ../../features/convert_feature2libsvm.sh xfw_labeled_u30test_1
bash ../../features/convert_feature2libsvm.sh xfx_labeled_u30test_1
bash ../../features/convert_feature2libsvm.sh xfy_labeled_u30test_1
bash ../../features/convert_feature2libsvm.sh xfz_labeled_u30test_1
bash ../../features/convert_feature2libsvm.sh xga_labeled_u30test_1
bash ../../features/convert_feature2libsvm.sh xgb_labeled_u30test_1
bash ../../features/convert_feature2libsvm.sh xgc_labeled_u30test_1
bash ../../features/convert_feature2libsvm.sh xgd_labeled_u30test_1
bash ../../features/convert_feature2libsvm.sh xge_labeled_u30test_1
bash ../../features/convert_feature2libsvm.sh xgf_labeled_u30test_1
bash ../../features/convert_feature2libsvm.sh xgg_labeled_u30test_1
bash ../../features/convert_feature2libsvm.sh xgh_labeled_u30test_1
bash ../../features/convert_feature2libsvm.sh xgi_labeled_u30test_1
bash ../../features/convert_feature2libsvm.sh xgj_labeled_u30test_1
bash ../../features/convert_feature2libsvm.sh xgk_labeled_u30test_1
bash ../../features/convert_feature2libsvm.sh xgl_labeled_u30test_1
bash ../../features/convert_feature2libsvm.sh xgm_labeled_u30test_1
bash ../../features/convert_feature2libsvm.sh xgn_labeled_u30test_1
bash ../../features/convert_feature2libsvm.sh xgo_labeled_u30test_1
bash ../../features/convert_feature2libsvm.sh xgp_labeled_u30test_1
bash ../../features/convert_feature2libsvm.sh xgq_labeled_u30test_1
bash ../../features/convert_feature2libsvm.sh xgr_labeled_u30test_1
bash ../../features/convert_feature2libsvm.sh xgs_labeled_u30test_1
bash ../../features/convert_feature2libsvm.sh xgt_labeled_u30test_1
bash ../../features/convert_feature2libsvm.sh xgu_labeled_u30test_1
bash ../../features/convert_feature2libsvm.sh xgv_labeled_u30test_1
bash ../../features/convert_feature2libsvm.sh xgw_labeled_u30test_1
bash ../../features/convert_feature2libsvm.sh xgx_labeled_u30test_1
bash ../../features/convert_feature2libsvm.sh xgy_labeled_u30test_1
bash ../../features/convert_feature2libsvm.sh xgz_labeled_u30test_1
bash ../../features/convert_feature2libsvm.sh xha_labeled_u30test_1
bash ../../features/convert_feature2libsvm.sh xhb_labeled_u30test_1
bash ../../features/convert_feature2libsvm.sh xhc_labeled_u30test_1
bash ../../features/convert_feature2libsvm.sh xhd_labeled_u30test_1
bash ../../features/convert_feature2libsvm.sh xhe_labeled_u30test_1
bash ../../features/convert_feature2libsvm.sh xhf_labeled_u30test_1
bash ../../features/convert_feature2libsvm.sh xhg_labeled_u30test_1
bash ../../features/convert_feature2libsvm.sh xhh_labeled_u30test_1
bash ../../features/convert_feature2libsvm.sh xhi_labeled_u30test_1
bash ../../features/convert_feature2libsvm.sh xhj_labeled_u30test_1
bash ../../features/convert_feature2libsvm.sh xhk_labeled_u30test_1
bash ../../features/convert_feature2libsvm.sh xhl_labeled_u30test_1
bash ../../features/convert_feature2libsvm.sh xhm_labeled_u30test_1
bash ../../features/convert_feature2libsvm.sh xhn_labeled_u30test_1
bash ../../features/convert_feature2libsvm.sh xho_labeled_u30test_1
bash ../../features/convert_feature2libsvm.sh xhp_labeled_u30test_1
bash ../../features/convert_feature2libsvm.sh xhq_labeled_u30test_1
bash ../../features/convert_feature2libsvm.sh xhr_labeled_u30test_1
bash ../../features/convert_feature2libsvm.sh xhs_labeled_u30test_1
bash ../../features/convert_feature2libsvm.sh xht_labeled_u30test_1
bash ../../features/convert_feature2libsvm.sh xaa_labeled_u30test_0
bash ../../features/convert_feature2libsvm.sh xab_labeled_u30test_0
bash ../../features/convert_feature2libsvm.sh xac_labeled_u30test_0
bash ../../features/convert_feature2libsvm.sh xad_labeled_u30test_0
bash ../../features/convert_feature2libsvm.sh xae_labeled_u30test_0
bash ../../features/convert_feature2libsvm.sh xaf_labeled_u30test_0
bash ../../features/convert_feature2libsvm.sh xag_labeled_u30test_0
bash ../../features/convert_feature2libsvm.sh xah_labeled_u30test_0
bash ../../features/convert_feature2libsvm.sh xai_labeled_u30test_0
bash ../../features/convert_feature2libsvm.sh xaj_labeled_u30test_0
bash ../../features/convert_feature2libsvm.sh xak_labeled_u30test_0
bash ../../features/convert_feature2libsvm.sh xal_labeled_u30test_0
bash ../../features/convert_feature2libsvm.sh xam_labeled_u30test_0
bash ../../features/convert_feature2libsvm.sh xan_labeled_u30test_0
bash ../../features/convert_feature2libsvm.sh xao_labeled_u30test_0
bash ../../features/convert_feature2libsvm.sh xap_labeled_u30test_0
bash ../../features/convert_feature2libsvm.sh xaq_labeled_u30test_0
bash ../../features/convert_feature2libsvm.sh xar_labeled_u30test_0
bash ../../features/convert_feature2libsvm.sh xas_labeled_u30test_0
bash ../../features/convert_feature2libsvm.sh xat_labeled_u30test_0
bash ../../features/convert_feature2libsvm.sh xau_labeled_u30test_0
bash ../../features/convert_feature2libsvm.sh xav_labeled_u30test_0
bash ../../features/convert_feature2libsvm.sh xaw_labeled_u30test_0
bash ../../features/convert_feature2libsvm.sh xax_labeled_u30test_0
bash ../../features/convert_feature2libsvm.sh xay_labeled_u30test_0
bash ../../features/convert_feature2libsvm.sh xaz_labeled_u30test_0
bash ../../features/convert_feature2libsvm.sh xba_labeled_u30test_0
bash ../../features/convert_feature2libsvm.sh xbb_labeled_u30test_0
bash ../../features/convert_feature2libsvm.sh xbc_labeled_u30test_0
bash ../../features/convert_feature2libsvm.sh xbd_labeled_u30test_0
bash ../../features/convert_feature2libsvm.sh xbe_labeled_u30test_0
bash ../../features/convert_feature2libsvm.sh xbf_labeled_u30test_0
bash ../../features/convert_feature2libsvm.sh xbg_labeled_u30test_0
bash ../../features/convert_feature2libsvm.sh xbh_labeled_u30test_0
bash ../../features/convert_feature2libsvm.sh xbi_labeled_u30test_0
bash ../../features/convert_feature2libsvm.sh xbj_labeled_u30test_0
bash ../../features/convert_feature2libsvm.sh xbk_labeled_u30test_0
bash ../../features/convert_feature2libsvm.sh xbl_labeled_u30test_0
bash ../../features/convert_feature2libsvm.sh xbm_labeled_u30test_0
bash ../../features/convert_feature2libsvm.sh xbn_labeled_u30test_0
bash ../../features/convert_feature2libsvm.sh xbo_labeled_u30test_0
bash ../../features/convert_feature2libsvm.sh xbp_labeled_u30test_0
bash ../../features/convert_feature2libsvm.sh xbq_labeled_u30test_0
bash ../../features/convert_feature2libsvm.sh xbr_labeled_u30test_0
bash ../../features/convert_feature2libsvm.sh xbs_labeled_u30test_0
bash ../../features/convert_feature2libsvm.sh xbt_labeled_u30test_0
bash ../../features/convert_feature2libsvm.sh xbu_labeled_u30test_0
bash ../../features/convert_feature2libsvm.sh xbv_labeled_u30test_0
bash ../../features/convert_feature2libsvm.sh xbw_labeled_u30test_0
bash ../../features/convert_feature2libsvm.sh xbx_labeled_u30test_0
bash ../../features/convert_feature2libsvm.sh xby_labeled_u30test_0
bash ../../features/convert_feature2libsvm.sh xbz_labeled_u30test_0
bash ../../features/convert_feature2libsvm.sh xca_labeled_u30test_0
bash ../../features/convert_feature2libsvm.sh xcb_labeled_u30test_0
bash ../../features/convert_feature2libsvm.sh xcc_labeled_u30test_0
bash ../../features/convert_feature2libsvm.sh xcd_labeled_u30test_0
bash ../../features/convert_feature2libsvm.sh xce_labeled_u30test_0
bash ../../features/convert_feature2libsvm.sh xcf_labeled_u30test_0
bash ../../features/convert_feature2libsvm.sh xcg_labeled_u30test_0
bash ../../features/convert_feature2libsvm.sh xch_labeled_u30test_0
bash ../../features/convert_feature2libsvm.sh xci_labeled_u30test_0
bash ../../features/convert_feature2libsvm.sh xcj_labeled_u30test_0
bash ../../features/convert_feature2libsvm.sh xck_labeled_u30test_0
bash ../../features/convert_feature2libsvm.sh xcl_labeled_u30test_0
bash ../../features/convert_feature2libsvm.sh xcm_labeled_u30test_0
bash ../../features/convert_feature2libsvm.sh xcn_labeled_u30test_0
bash ../../features/convert_feature2libsvm.sh xco_labeled_u30test_0
bash ../../features/convert_feature2libsvm.sh xcp_labeled_u30test_0
bash ../../features/convert_feature2libsvm.sh xcq_labeled_u30test_0
bash ../../features/convert_feature2libsvm.sh xcr_labeled_u30test_0
bash ../../features/convert_feature2libsvm.sh xcs_labeled_u30test_0
bash ../../features/convert_feature2libsvm.sh xct_labeled_u30test_0
bash ../../features/convert_feature2libsvm.sh xcu_labeled_u30test_0
bash ../../features/convert_feature2libsvm.sh xcv_labeled_u30test_0
bash ../../features/convert_feature2libsvm.sh xcw_labeled_u30test_0
bash ../../features/convert_feature2libsvm.sh xcx_labeled_u30test_0
bash ../../features/convert_feature2libsvm.sh xcy_labeled_u30test_0
bash ../../features/convert_feature2libsvm.sh xcz_labeled_u30test_0
bash ../../features/convert_feature2libsvm.sh xda_labeled_u30test_0
bash ../../features/convert_feature2libsvm.sh xdb_labeled_u30test_0
bash ../../features/convert_feature2libsvm.sh xdc_labeled_u30test_0
bash ../../features/convert_feature2libsvm.sh xdd_labeled_u30test_0
bash ../../features/convert_feature2libsvm.sh xde_labeled_u30test_0
bash ../../features/convert_feature2libsvm.sh xdf_labeled_u30test_0
bash ../../features/convert_feature2libsvm.sh xdg_labeled_u30test_0
bash ../../features/convert_feature2libsvm.sh xdh_labeled_u30test_0
bash ../../features/convert_feature2libsvm.sh xdi_labeled_u30test_0
bash ../../features/convert_feature2libsvm.sh xdj_labeled_u30test_0
bash ../../features/convert_feature2libsvm.sh xdk_labeled_u30test_0
bash ../../features/convert_feature2libsvm.sh xdl_labeled_u30test_0
bash ../../features/convert_feature2libsvm.sh xdm_labeled_u30test_0
bash ../../features/convert_feature2libsvm.sh xdn_labeled_u30test_0
bash ../../features/convert_feature2libsvm.sh xdo_labeled_u30test_0
bash ../../features/convert_feature2libsvm.sh xdp_labeled_u30test_0
bash ../../features/convert_feature2libsvm.sh xdq_labeled_u30test_0
bash ../../features/convert_feature2libsvm.sh xdr_labeled_u30test_0
bash ../../features/convert_feature2libsvm.sh xds_labeled_u30test_0
bash ../../features/convert_feature2libsvm.sh xdt_labeled_u30test_0
bash ../../features/convert_feature2libsvm.sh xdu_labeled_u30test_0
bash ../../features/convert_feature2libsvm.sh xdv_labeled_u30test_0
bash ../../features/convert_feature2libsvm.sh xdw_labeled_u30test_0
bash ../../features/convert_feature2libsvm.sh xdx_labeled_u30test_0
bash ../../features/convert_feature2libsvm.sh xdy_labeled_u30test_0
bash ../../features/convert_feature2libsvm.sh xdz_labeled_u30test_0
bash ../../features/convert_feature2libsvm.sh xea_labeled_u30test_0
bash ../../features/convert_feature2libsvm.sh xeb_labeled_u30test_0
bash ../../features/convert_feature2libsvm.sh xec_labeled_u30test_0
bash ../../features/convert_feature2libsvm.sh xed_labeled_u30test_0
bash ../../features/convert_feature2libsvm.sh xee_labeled_u30test_0
bash ../../features/convert_feature2libsvm.sh xef_labeled_u30test_0
bash ../../features/convert_feature2libsvm.sh xeg_labeled_u30test_0
bash ../../features/convert_feature2libsvm.sh xeh_labeled_u30test_0
bash ../../features/convert_feature2libsvm.sh xei_labeled_u30test_0
bash ../../features/convert_feature2libsvm.sh xej_labeled_u30test_0
bash ../../features/convert_feature2libsvm.sh xek_labeled_u30test_0
bash ../../features/convert_feature2libsvm.sh xel_labeled_u30test_0
bash ../../features/convert_feature2libsvm.sh xem_labeled_u30test_0
bash ../../features/convert_feature2libsvm.sh xen_labeled_u30test_0
bash ../../features/convert_feature2libsvm.sh xeo_labeled_u30test_0
bash ../../features/convert_feature2libsvm.sh xep_labeled_u30test_0
bash ../../features/convert_feature2libsvm.sh xeq_labeled_u30test_0
bash ../../features/convert_feature2libsvm.sh xer_labeled_u30test_0
bash ../../features/convert_feature2libsvm.sh xes_labeled_u30test_0
bash ../../features/convert_feature2libsvm.sh xet_labeled_u30test_0
bash ../../features/convert_feature2libsvm.sh xeu_labeled_u30test_0
bash ../../features/convert_feature2libsvm.sh xev_labeled_u30test_0
bash ../../features/convert_feature2libsvm.sh xew_labeled_u30test_0
bash ../../features/convert_feature2libsvm.sh xex_labeled_u30test_0
bash ../../features/convert_feature2libsvm.sh xey_labeled_u30test_0
bash ../../features/convert_feature2libsvm.sh xez_labeled_u30test_0
bash ../../features/convert_feature2libsvm.sh xfa_labeled_u30test_0
bash ../../features/convert_feature2libsvm.sh xfb_labeled_u30test_0
bash ../../features/convert_feature2libsvm.sh xfc_labeled_u30test_0
bash ../../features/convert_feature2libsvm.sh xfd_labeled_u30test_0
bash ../../features/convert_feature2libsvm.sh xfe_labeled_u30test_0
bash ../../features/convert_feature2libsvm.sh xff_labeled_u30test_0
bash ../../features/convert_feature2libsvm.sh xfg_labeled_u30test_0
bash ../../features/convert_feature2libsvm.sh xfh_labeled_u30test_0
bash ../../features/convert_feature2libsvm.sh xfi_labeled_u30test_0
bash ../../features/convert_feature2libsvm.sh xfj_labeled_u30test_0
bash ../../features/convert_feature2libsvm.sh xfk_labeled_u30test_0
bash ../../features/convert_feature2libsvm.sh xfl_labeled_u30test_0
bash ../../features/convert_feature2libsvm.sh xfm_labeled_u30test_0
bash ../../features/convert_feature2libsvm.sh xfn_labeled_u30test_0
bash ../../features/convert_feature2libsvm.sh xfo_labeled_u30test_0
bash ../../features/convert_feature2libsvm.sh xfp_labeled_u30test_0
bash ../../features/convert_feature2libsvm.sh xfq_labeled_u30test_0
bash ../../features/convert_feature2libsvm.sh xfr_labeled_u30test_0
bash ../../features/convert_feature2libsvm.sh xfs_labeled_u30test_0
bash ../../features/convert_feature2libsvm.sh xft_labeled_u30test_0
bash ../../features/convert_feature2libsvm.sh xfu_labeled_u30test_0
bash ../../features/convert_feature2libsvm.sh xfv_labeled_u30test_0
bash ../../features/convert_feature2libsvm.sh xfw_labeled_u30test_0
bash ../../features/convert_feature2libsvm.sh xfx_labeled_u30test_0
bash ../../features/convert_feature2libsvm.sh xfy_labeled_u30test_0
bash ../../features/convert_feature2libsvm.sh xfz_labeled_u30test_0
bash ../../features/convert_feature2libsvm.sh xga_labeled_u30test_0
bash ../../features/convert_feature2libsvm.sh xgb_labeled_u30test_0
bash ../../features/convert_feature2libsvm.sh xgc_labeled_u30test_0
bash ../../features/convert_feature2libsvm.sh xgd_labeled_u30test_0
bash ../../features/convert_feature2libsvm.sh xge_labeled_u30test_0
bash ../../features/convert_feature2libsvm.sh xgf_labeled_u30test_0
bash ../../features/convert_feature2libsvm.sh xgg_labeled_u30test_0
bash ../../features/convert_feature2libsvm.sh xgh_labeled_u30test_0
bash ../../features/convert_feature2libsvm.sh xgi_labeled_u30test_0
bash ../../features/convert_feature2libsvm.sh xgj_labeled_u30test_0
bash ../../features/convert_feature2libsvm.sh xgk_labeled_u30test_0
bash ../../features/convert_feature2libsvm.sh xgl_labeled_u30test_0
bash ../../features/convert_feature2libsvm.sh xgm_labeled_u30test_0
bash ../../features/convert_feature2libsvm.sh xgn_labeled_u30test_0
bash ../../features/convert_feature2libsvm.sh xgo_labeled_u30test_0
bash ../../features/convert_feature2libsvm.sh xgp_labeled_u30test_0
bash ../../features/convert_feature2libsvm.sh xgq_labeled_u30test_0
bash ../../features/convert_feature2libsvm.sh xgr_labeled_u30test_0
bash ../../features/convert_feature2libsvm.sh xgs_labeled_u30test_0
bash ../../features/convert_feature2libsvm.sh xgt_labeled_u30test_0
bash ../../features/convert_feature2libsvm.sh xgu_labeled_u30test_0
bash ../../features/convert_feature2libsvm.sh xgv_labeled_u30test_0
bash ../../features/convert_feature2libsvm.sh xgw_labeled_u30test_0
bash ../../features/convert_feature2libsvm.sh xgx_labeled_u30test_0
bash ../../features/convert_feature2libsvm.sh xgy_labeled_u30test_0
bash ../../features/convert_feature2libsvm.sh xgz_labeled_u30test_0
bash ../../features/convert_feature2libsvm.sh xha_labeled_u30test_0
bash ../../features/convert_feature2libsvm.sh xhb_labeled_u30test_0
bash ../../features/convert_feature2libsvm.sh xhc_labeled_u30test_0
bash ../../features/convert_feature2libsvm.sh xhd_labeled_u30test_0
bash ../../features/convert_feature2libsvm.sh xhe_labeled_u30test_0
bash ../../features/convert_feature2libsvm.sh xhf_labeled_u30test_0
bash ../../features/convert_feature2libsvm.sh xhg_labeled_u30test_0
bash ../../features/convert_feature2libsvm.sh xhh_labeled_u30test_0
bash ../../features/convert_feature2libsvm.sh xhi_labeled_u30test_0
bash ../../features/convert_feature2libsvm.sh xhj_labeled_u30test_0
bash ../../features/convert_feature2libsvm.sh xhk_labeled_u30test_0
bash ../../features/convert_feature2libsvm.sh xhl_labeled_u30test_0
bash ../../features/convert_feature2libsvm.sh xhm_labeled_u30test_0
bash ../../features/convert_feature2libsvm.sh xhn_labeled_u30test_0
bash ../../features/convert_feature2libsvm.sh xho_labeled_u30test_0
bash ../../features/convert_feature2libsvm.sh xhp_labeled_u30test_0
bash ../../features/convert_feature2libsvm.sh xhq_labeled_u30test_0
bash ../../features/convert_feature2libsvm.sh xhr_labeled_u30test_0
bash ../../features/convert_feature2libsvm.sh xhs_labeled_u30test_0
bash ../../features/convert_feature2libsvm.sh xht_labeled_u30test_0
bash ../../features/convert_feature2libsvm.sh xaa_labeled_u30full_1
bash ../../features/convert_feature2libsvm.sh xab_labeled_u30full_1
bash ../../features/convert_feature2libsvm.sh xac_labeled_u30full_1
bash ../../features/convert_feature2libsvm.sh xad_labeled_u30full_1
bash ../../features/convert_feature2libsvm.sh xae_labeled_u30full_1
bash ../../features/convert_feature2libsvm.sh xaf_labeled_u30full_1
bash ../../features/convert_feature2libsvm.sh xag_labeled_u30full_1
bash ../../features/convert_feature2libsvm.sh xah_labeled_u30full_1
bash ../../features/convert_feature2libsvm.sh xai_labeled_u30full_1
bash ../../features/convert_feature2libsvm.sh xaj_labeled_u30full_1
bash ../../features/convert_feature2libsvm.sh xak_labeled_u30full_1
bash ../../features/convert_feature2libsvm.sh xal_labeled_u30full_1
bash ../../features/convert_feature2libsvm.sh xam_labeled_u30full_1
bash ../../features/convert_feature2libsvm.sh xan_labeled_u30full_1
bash ../../features/convert_feature2libsvm.sh xao_labeled_u30full_1
bash ../../features/convert_feature2libsvm.sh xap_labeled_u30full_1
bash ../../features/convert_feature2libsvm.sh xaq_labeled_u30full_1
bash ../../features/convert_feature2libsvm.sh xar_labeled_u30full_1
bash ../../features/convert_feature2libsvm.sh xas_labeled_u30full_1
bash ../../features/convert_feature2libsvm.sh xat_labeled_u30full_1
bash ../../features/convert_feature2libsvm.sh xau_labeled_u30full_1
bash ../../features/convert_feature2libsvm.sh xav_labeled_u30full_1
bash ../../features/convert_feature2libsvm.sh xaw_labeled_u30full_1
bash ../../features/convert_feature2libsvm.sh xax_labeled_u30full_1
bash ../../features/convert_feature2libsvm.sh xay_labeled_u30full_1
bash ../../features/convert_feature2libsvm.sh xaz_labeled_u30full_1
bash ../../features/convert_feature2libsvm.sh xba_labeled_u30full_1
bash ../../features/convert_feature2libsvm.sh xbb_labeled_u30full_1
bash ../../features/convert_feature2libsvm.sh xbc_labeled_u30full_1
bash ../../features/convert_feature2libsvm.sh xbd_labeled_u30full_1
bash ../../features/convert_feature2libsvm.sh xbe_labeled_u30full_1
bash ../../features/convert_feature2libsvm.sh xbf_labeled_u30full_1
bash ../../features/convert_feature2libsvm.sh xbg_labeled_u30full_1
bash ../../features/convert_feature2libsvm.sh xbh_labeled_u30full_1
bash ../../features/convert_feature2libsvm.sh xbi_labeled_u30full_1
bash ../../features/convert_feature2libsvm.sh xbj_labeled_u30full_1
bash ../../features/convert_feature2libsvm.sh xbk_labeled_u30full_1
bash ../../features/convert_feature2libsvm.sh xbl_labeled_u30full_1
bash ../../features/convert_feature2libsvm.sh xbm_labeled_u30full_1
bash ../../features/convert_feature2libsvm.sh xbn_labeled_u30full_1
bash ../../features/convert_feature2libsvm.sh xbo_labeled_u30full_1
bash ../../features/convert_feature2libsvm.sh xbp_labeled_u30full_1
bash ../../features/convert_feature2libsvm.sh xbq_labeled_u30full_1
bash ../../features/convert_feature2libsvm.sh xbr_labeled_u30full_1
bash ../../features/convert_feature2libsvm.sh xbs_labeled_u30full_1
bash ../../features/convert_feature2libsvm.sh xbt_labeled_u30full_1
bash ../../features/convert_feature2libsvm.sh xbu_labeled_u30full_1
bash ../../features/convert_feature2libsvm.sh xbv_labeled_u30full_1
bash ../../features/convert_feature2libsvm.sh xbw_labeled_u30full_1
bash ../../features/convert_feature2libsvm.sh xbx_labeled_u30full_1
bash ../../features/convert_feature2libsvm.sh xby_labeled_u30full_1
bash ../../features/convert_feature2libsvm.sh xbz_labeled_u30full_1
bash ../../features/convert_feature2libsvm.sh xca_labeled_u30full_1
bash ../../features/convert_feature2libsvm.sh xcb_labeled_u30full_1
bash ../../features/convert_feature2libsvm.sh xcc_labeled_u30full_1
bash ../../features/convert_feature2libsvm.sh xcd_labeled_u30full_1
bash ../../features/convert_feature2libsvm.sh xce_labeled_u30full_1
bash ../../features/convert_feature2libsvm.sh xcf_labeled_u30full_1
bash ../../features/convert_feature2libsvm.sh xcg_labeled_u30full_1
bash ../../features/convert_feature2libsvm.sh xch_labeled_u30full_1
bash ../../features/convert_feature2libsvm.sh xci_labeled_u30full_1
bash ../../features/convert_feature2libsvm.sh xcj_labeled_u30full_1
bash ../../features/convert_feature2libsvm.sh xck_labeled_u30full_1
bash ../../features/convert_feature2libsvm.sh xcl_labeled_u30full_1
bash ../../features/convert_feature2libsvm.sh xcm_labeled_u30full_1
bash ../../features/convert_feature2libsvm.sh xcn_labeled_u30full_1
bash ../../features/convert_feature2libsvm.sh xco_labeled_u30full_1
bash ../../features/convert_feature2libsvm.sh xcp_labeled_u30full_1
bash ../../features/convert_feature2libsvm.sh xcq_labeled_u30full_1
bash ../../features/convert_feature2libsvm.sh xcr_labeled_u30full_1
bash ../../features/convert_feature2libsvm.sh xcs_labeled_u30full_1
bash ../../features/convert_feature2libsvm.sh xct_labeled_u30full_1
bash ../../features/convert_feature2libsvm.sh xcu_labeled_u30full_1
bash ../../features/convert_feature2libsvm.sh xcv_labeled_u30full_1
bash ../../features/convert_feature2libsvm.sh xcw_labeled_u30full_1
bash ../../features/convert_feature2libsvm.sh xcx_labeled_u30full_1
bash ../../features/convert_feature2libsvm.sh xcy_labeled_u30full_1
bash ../../features/convert_feature2libsvm.sh xcz_labeled_u30full_1
bash ../../features/convert_feature2libsvm.sh xda_labeled_u30full_1
bash ../../features/convert_feature2libsvm.sh xdb_labeled_u30full_1
bash ../../features/convert_feature2libsvm.sh xdc_labeled_u30full_1
bash ../../features/convert_feature2libsvm.sh xdd_labeled_u30full_1
bash ../../features/convert_feature2libsvm.sh xde_labeled_u30full_1
bash ../../features/convert_feature2libsvm.sh xdf_labeled_u30full_1
bash ../../features/convert_feature2libsvm.sh xdg_labeled_u30full_1
bash ../../features/convert_feature2libsvm.sh xdh_labeled_u30full_1
bash ../../features/convert_feature2libsvm.sh xdi_labeled_u30full_1
bash ../../features/convert_feature2libsvm.sh xdj_labeled_u30full_1
bash ../../features/convert_feature2libsvm.sh xdk_labeled_u30full_1
bash ../../features/convert_feature2libsvm.sh xdl_labeled_u30full_1
bash ../../features/convert_feature2libsvm.sh xdm_labeled_u30full_1
bash ../../features/convert_feature2libsvm.sh xdn_labeled_u30full_1
bash ../../features/convert_feature2libsvm.sh xdo_labeled_u30full_1
bash ../../features/convert_feature2libsvm.sh xdp_labeled_u30full_1
bash ../../features/convert_feature2libsvm.sh xdq_labeled_u30full_1
bash ../../features/convert_feature2libsvm.sh xdr_labeled_u30full_1
bash ../../features/convert_feature2libsvm.sh xds_labeled_u30full_1
bash ../../features/convert_feature2libsvm.sh xdt_labeled_u30full_1
bash ../../features/convert_feature2libsvm.sh xdu_labeled_u30full_1
bash ../../features/convert_feature2libsvm.sh xdv_labeled_u30full_1
bash ../../features/convert_feature2libsvm.sh xdw_labeled_u30full_1
bash ../../features/convert_feature2libsvm.sh xdx_labeled_u30full_1
bash ../../features/convert_feature2libsvm.sh xdy_labeled_u30full_1
bash ../../features/convert_feature2libsvm.sh xdz_labeled_u30full_1
bash ../../features/convert_feature2libsvm.sh xea_labeled_u30full_1
bash ../../features/convert_feature2libsvm.sh xeb_labeled_u30full_1
bash ../../features/convert_feature2libsvm.sh xec_labeled_u30full_1
bash ../../features/convert_feature2libsvm.sh xed_labeled_u30full_1
bash ../../features/convert_feature2libsvm.sh xee_labeled_u30full_1
bash ../../features/convert_feature2libsvm.sh xef_labeled_u30full_1
bash ../../features/convert_feature2libsvm.sh xeg_labeled_u30full_1
bash ../../features/convert_feature2libsvm.sh xeh_labeled_u30full_1
bash ../../features/convert_feature2libsvm.sh xei_labeled_u30full_1
bash ../../features/convert_feature2libsvm.sh xej_labeled_u30full_1
bash ../../features/convert_feature2libsvm.sh xek_labeled_u30full_1
bash ../../features/convert_feature2libsvm.sh xel_labeled_u30full_1
bash ../../features/convert_feature2libsvm.sh xem_labeled_u30full_1
bash ../../features/convert_feature2libsvm.sh xen_labeled_u30full_1
bash ../../features/convert_feature2libsvm.sh xeo_labeled_u30full_1
bash ../../features/convert_feature2libsvm.sh xep_labeled_u30full_1
bash ../../features/convert_feature2libsvm.sh xeq_labeled_u30full_1
bash ../../features/convert_feature2libsvm.sh xer_labeled_u30full_1
bash ../../features/convert_feature2libsvm.sh xes_labeled_u30full_1
bash ../../features/convert_feature2libsvm.sh xet_labeled_u30full_1
bash ../../features/convert_feature2libsvm.sh xeu_labeled_u30full_1
bash ../../features/convert_feature2libsvm.sh xev_labeled_u30full_1
bash ../../features/convert_feature2libsvm.sh xew_labeled_u30full_1
bash ../../features/convert_feature2libsvm.sh xex_labeled_u30full_1
bash ../../features/convert_feature2libsvm.sh xey_labeled_u30full_1
bash ../../features/convert_feature2libsvm.sh xez_labeled_u30full_1
bash ../../features/convert_feature2libsvm.sh xfa_labeled_u30full_1
bash ../../features/convert_feature2libsvm.sh xfb_labeled_u30full_1
bash ../../features/convert_feature2libsvm.sh xfc_labeled_u30full_1
bash ../../features/convert_feature2libsvm.sh xfd_labeled_u30full_1
bash ../../features/convert_feature2libsvm.sh xfe_labeled_u30full_1
bash ../../features/convert_feature2libsvm.sh xff_labeled_u30full_1
bash ../../features/convert_feature2libsvm.sh xfg_labeled_u30full_1
bash ../../features/convert_feature2libsvm.sh xfh_labeled_u30full_1
bash ../../features/convert_feature2libsvm.sh xfi_labeled_u30full_1
bash ../../features/convert_feature2libsvm.sh xfj_labeled_u30full_1
bash ../../features/convert_feature2libsvm.sh xfk_labeled_u30full_1
bash ../../features/convert_feature2libsvm.sh xfl_labeled_u30full_1
bash ../../features/convert_feature2libsvm.sh xfm_labeled_u30full_1
bash ../../features/convert_feature2libsvm.sh xfn_labeled_u30full_1
bash ../../features/convert_feature2libsvm.sh xfo_labeled_u30full_1
bash ../../features/convert_feature2libsvm.sh xfp_labeled_u30full_1
bash ../../features/convert_feature2libsvm.sh xfq_labeled_u30full_1
bash ../../features/convert_feature2libsvm.sh xfr_labeled_u30full_1
bash ../../features/convert_feature2libsvm.sh xfs_labeled_u30full_1
bash ../../features/convert_feature2libsvm.sh xft_labeled_u30full_1
bash ../../features/convert_feature2libsvm.sh xfu_labeled_u30full_1
bash ../../features/convert_feature2libsvm.sh xfv_labeled_u30full_1
bash ../../features/convert_feature2libsvm.sh xfw_labeled_u30full_1
bash ../../features/convert_feature2libsvm.sh xfx_labeled_u30full_1
bash ../../features/convert_feature2libsvm.sh xfy_labeled_u30full_1
bash ../../features/convert_feature2libsvm.sh xfz_labeled_u30full_1
bash ../../features/convert_feature2libsvm.sh xga_labeled_u30full_1
bash ../../features/convert_feature2libsvm.sh xgb_labeled_u30full_1
bash ../../features/convert_feature2libsvm.sh xgc_labeled_u30full_1
bash ../../features/convert_feature2libsvm.sh xgd_labeled_u30full_1
bash ../../features/convert_feature2libsvm.sh xge_labeled_u30full_1
bash ../../features/convert_feature2libsvm.sh xgf_labeled_u30full_1
bash ../../features/convert_feature2libsvm.sh xgg_labeled_u30full_1
bash ../../features/convert_feature2libsvm.sh xgh_labeled_u30full_1
bash ../../features/convert_feature2libsvm.sh xgi_labeled_u30full_1
bash ../../features/convert_feature2libsvm.sh xgj_labeled_u30full_1
bash ../../features/convert_feature2libsvm.sh xgk_labeled_u30full_1
bash ../../features/convert_feature2libsvm.sh xgl_labeled_u30full_1
bash ../../features/convert_feature2libsvm.sh xgm_labeled_u30full_1
bash ../../features/convert_feature2libsvm.sh xgn_labeled_u30full_1
bash ../../features/convert_feature2libsvm.sh xgo_labeled_u30full_1
bash ../../features/convert_feature2libsvm.sh xgp_labeled_u30full_1
bash ../../features/convert_feature2libsvm.sh xgq_labeled_u30full_1
bash ../../features/convert_feature2libsvm.sh xgr_labeled_u30full_1
bash ../../features/convert_feature2libsvm.sh xgs_labeled_u30full_1
bash ../../features/convert_feature2libsvm.sh xgt_labeled_u30full_1
bash ../../features/convert_feature2libsvm.sh xgu_labeled_u30full_1
bash ../../features/convert_feature2libsvm.sh xgv_labeled_u30full_1
bash ../../features/convert_feature2libsvm.sh xgw_labeled_u30full_1
bash ../../features/convert_feature2libsvm.sh xgx_labeled_u30full_1
bash ../../features/convert_feature2libsvm.sh xgy_labeled_u30full_1
bash ../../features/convert_feature2libsvm.sh xgz_labeled_u30full_1
bash ../../features/convert_feature2libsvm.sh xha_labeled_u30full_1
bash ../../features/convert_feature2libsvm.sh xhb_labeled_u30full_1
bash ../../features/convert_feature2libsvm.sh xhc_labeled_u30full_1
bash ../../features/convert_feature2libsvm.sh xhd_labeled_u30full_1
bash ../../features/convert_feature2libsvm.sh xhe_labeled_u30full_1
bash ../../features/convert_feature2libsvm.sh xhf_labeled_u30full_1
bash ../../features/convert_feature2libsvm.sh xhg_labeled_u30full_1
bash ../../features/convert_feature2libsvm.sh xhh_labeled_u30full_1
bash ../../features/convert_feature2libsvm.sh xhi_labeled_u30full_1
bash ../../features/convert_feature2libsvm.sh xhj_labeled_u30full_1
bash ../../features/convert_feature2libsvm.sh xhk_labeled_u30full_1
bash ../../features/convert_feature2libsvm.sh xhl_labeled_u30full_1
bash ../../features/convert_feature2libsvm.sh xhm_labeled_u30full_1
bash ../../features/convert_feature2libsvm.sh xhn_labeled_u30full_1
bash ../../features/convert_feature2libsvm.sh xho_labeled_u30full_1
bash ../../features/convert_feature2libsvm.sh xhp_labeled_u30full_1
bash ../../features/convert_feature2libsvm.sh xhq_labeled_u30full_1
bash ../../features/convert_feature2libsvm.sh xhr_labeled_u30full_1
bash ../../features/convert_feature2libsvm.sh xhs_labeled_u30full_1
bash ../../features/convert_feature2libsvm.sh xht_labeled_u30full_1
bash ../../features/convert_feature2libsvm.sh xaa_labeled_u30full_0
bash ../../features/convert_feature2libsvm.sh xab_labeled_u30full_0
bash ../../features/convert_feature2libsvm.sh xac_labeled_u30full_0
bash ../../features/convert_feature2libsvm.sh xad_labeled_u30full_0
bash ../../features/convert_feature2libsvm.sh xae_labeled_u30full_0
bash ../../features/convert_feature2libsvm.sh xaf_labeled_u30full_0
bash ../../features/convert_feature2libsvm.sh xag_labeled_u30full_0
bash ../../features/convert_feature2libsvm.sh xah_labeled_u30full_0
bash ../../features/convert_feature2libsvm.sh xai_labeled_u30full_0
bash ../../features/convert_feature2libsvm.sh xaj_labeled_u30full_0
bash ../../features/convert_feature2libsvm.sh xak_labeled_u30full_0
bash ../../features/convert_feature2libsvm.sh xal_labeled_u30full_0
bash ../../features/convert_feature2libsvm.sh xam_labeled_u30full_0
bash ../../features/convert_feature2libsvm.sh xan_labeled_u30full_0
bash ../../features/convert_feature2libsvm.sh xao_labeled_u30full_0
bash ../../features/convert_feature2libsvm.sh xap_labeled_u30full_0
bash ../../features/convert_feature2libsvm.sh xaq_labeled_u30full_0
bash ../../features/convert_feature2libsvm.sh xar_labeled_u30full_0
bash ../../features/convert_feature2libsvm.sh xas_labeled_u30full_0
bash ../../features/convert_feature2libsvm.sh xat_labeled_u30full_0
bash ../../features/convert_feature2libsvm.sh xau_labeled_u30full_0
bash ../../features/convert_feature2libsvm.sh xav_labeled_u30full_0
bash ../../features/convert_feature2libsvm.sh xaw_labeled_u30full_0
bash ../../features/convert_feature2libsvm.sh xax_labeled_u30full_0
bash ../../features/convert_feature2libsvm.sh xay_labeled_u30full_0
bash ../../features/convert_feature2libsvm.sh xaz_labeled_u30full_0
bash ../../features/convert_feature2libsvm.sh xba_labeled_u30full_0
bash ../../features/convert_feature2libsvm.sh xbb_labeled_u30full_0
bash ../../features/convert_feature2libsvm.sh xbc_labeled_u30full_0
bash ../../features/convert_feature2libsvm.sh xbd_labeled_u30full_0
bash ../../features/convert_feature2libsvm.sh xbe_labeled_u30full_0
bash ../../features/convert_feature2libsvm.sh xbf_labeled_u30full_0
bash ../../features/convert_feature2libsvm.sh xbg_labeled_u30full_0
bash ../../features/convert_feature2libsvm.sh xbh_labeled_u30full_0
bash ../../features/convert_feature2libsvm.sh xbi_labeled_u30full_0
bash ../../features/convert_feature2libsvm.sh xbj_labeled_u30full_0
bash ../../features/convert_feature2libsvm.sh xbk_labeled_u30full_0
bash ../../features/convert_feature2libsvm.sh xbl_labeled_u30full_0
bash ../../features/convert_feature2libsvm.sh xbm_labeled_u30full_0
bash ../../features/convert_feature2libsvm.sh xbn_labeled_u30full_0
bash ../../features/convert_feature2libsvm.sh xbo_labeled_u30full_0
bash ../../features/convert_feature2libsvm.sh xbp_labeled_u30full_0
bash ../../features/convert_feature2libsvm.sh xbq_labeled_u30full_0
bash ../../features/convert_feature2libsvm.sh xbr_labeled_u30full_0
bash ../../features/convert_feature2libsvm.sh xbs_labeled_u30full_0
bash ../../features/convert_feature2libsvm.sh xbt_labeled_u30full_0
bash ../../features/convert_feature2libsvm.sh xbu_labeled_u30full_0
bash ../../features/convert_feature2libsvm.sh xbv_labeled_u30full_0
bash ../../features/convert_feature2libsvm.sh xbw_labeled_u30full_0
bash ../../features/convert_feature2libsvm.sh xbx_labeled_u30full_0
bash ../../features/convert_feature2libsvm.sh xby_labeled_u30full_0
bash ../../features/convert_feature2libsvm.sh xbz_labeled_u30full_0
bash ../../features/convert_feature2libsvm.sh xca_labeled_u30full_0
bash ../../features/convert_feature2libsvm.sh xcb_labeled_u30full_0
bash ../../features/convert_feature2libsvm.sh xcc_labeled_u30full_0
bash ../../features/convert_feature2libsvm.sh xcd_labeled_u30full_0
bash ../../features/convert_feature2libsvm.sh xce_labeled_u30full_0
bash ../../features/convert_feature2libsvm.sh xcf_labeled_u30full_0
bash ../../features/convert_feature2libsvm.sh xcg_labeled_u30full_0
bash ../../features/convert_feature2libsvm.sh xch_labeled_u30full_0
bash ../../features/convert_feature2libsvm.sh xci_labeled_u30full_0
bash ../../features/convert_feature2libsvm.sh xcj_labeled_u30full_0
bash ../../features/convert_feature2libsvm.sh xck_labeled_u30full_0
bash ../../features/convert_feature2libsvm.sh xcl_labeled_u30full_0
bash ../../features/convert_feature2libsvm.sh xcm_labeled_u30full_0
bash ../../features/convert_feature2libsvm.sh xcn_labeled_u30full_0
bash ../../features/convert_feature2libsvm.sh xco_labeled_u30full_0
bash ../../features/convert_feature2libsvm.sh xcp_labeled_u30full_0
bash ../../features/convert_feature2libsvm.sh xcq_labeled_u30full_0
bash ../../features/convert_feature2libsvm.sh xcr_labeled_u30full_0
bash ../../features/convert_feature2libsvm.sh xcs_labeled_u30full_0
bash ../../features/convert_feature2libsvm.sh xct_labeled_u30full_0
bash ../../features/convert_feature2libsvm.sh xcu_labeled_u30full_0
bash ../../features/convert_feature2libsvm.sh xcv_labeled_u30full_0
bash ../../features/convert_feature2libsvm.sh xcw_labeled_u30full_0
bash ../../features/convert_feature2libsvm.sh xcx_labeled_u30full_0
bash ../../features/convert_feature2libsvm.sh xcy_labeled_u30full_0
bash ../../features/convert_feature2libsvm.sh xcz_labeled_u30full_0
bash ../../features/convert_feature2libsvm.sh xda_labeled_u30full_0
bash ../../features/convert_feature2libsvm.sh xdb_labeled_u30full_0
bash ../../features/convert_feature2libsvm.sh xdc_labeled_u30full_0
bash ../../features/convert_feature2libsvm.sh xdd_labeled_u30full_0
bash ../../features/convert_feature2libsvm.sh xde_labeled_u30full_0
bash ../../features/convert_feature2libsvm.sh xdf_labeled_u30full_0
bash ../../features/convert_feature2libsvm.sh xdg_labeled_u30full_0
bash ../../features/convert_feature2libsvm.sh xdh_labeled_u30full_0
bash ../../features/convert_feature2libsvm.sh xdi_labeled_u30full_0
bash ../../features/convert_feature2libsvm.sh xdj_labeled_u30full_0
bash ../../features/convert_feature2libsvm.sh xdk_labeled_u30full_0
bash ../../features/convert_feature2libsvm.sh xdl_labeled_u30full_0
bash ../../features/convert_feature2libsvm.sh xdm_labeled_u30full_0
bash ../../features/convert_feature2libsvm.sh xdn_labeled_u30full_0
bash ../../features/convert_feature2libsvm.sh xdo_labeled_u30full_0
bash ../../features/convert_feature2libsvm.sh xdp_labeled_u30full_0
bash ../../features/convert_feature2libsvm.sh xdq_labeled_u30full_0
bash ../../features/convert_feature2libsvm.sh xdr_labeled_u30full_0
bash ../../features/convert_feature2libsvm.sh xds_labeled_u30full_0
bash ../../features/convert_feature2libsvm.sh xdt_labeled_u30full_0
bash ../../features/convert_feature2libsvm.sh xdu_labeled_u30full_0
bash ../../features/convert_feature2libsvm.sh xdv_labeled_u30full_0
bash ../../features/convert_feature2libsvm.sh xdw_labeled_u30full_0
bash ../../features/convert_feature2libsvm.sh xdx_labeled_u30full_0
bash ../../features/convert_feature2libsvm.sh xdy_labeled_u30full_0
bash ../../features/convert_feature2libsvm.sh xdz_labeled_u30full_0
bash ../../features/convert_feature2libsvm.sh xea_labeled_u30full_0
bash ../../features/convert_feature2libsvm.sh xeb_labeled_u30full_0
bash ../../features/convert_feature2libsvm.sh xec_labeled_u30full_0
bash ../../features/convert_feature2libsvm.sh xed_labeled_u30full_0
bash ../../features/convert_feature2libsvm.sh xee_labeled_u30full_0
bash ../../features/convert_feature2libsvm.sh xef_labeled_u30full_0
bash ../../features/convert_feature2libsvm.sh xeg_labeled_u30full_0
bash ../../features/convert_feature2libsvm.sh xeh_labeled_u30full_0
bash ../../features/convert_feature2libsvm.sh xei_labeled_u30full_0
bash ../../features/convert_feature2libsvm.sh xej_labeled_u30full_0
bash ../../features/convert_feature2libsvm.sh xek_labeled_u30full_0
bash ../../features/convert_feature2libsvm.sh xel_labeled_u30full_0
bash ../../features/convert_feature2libsvm.sh xem_labeled_u30full_0
bash ../../features/convert_feature2libsvm.sh xen_labeled_u30full_0
bash ../../features/convert_feature2libsvm.sh xeo_labeled_u30full_0
bash ../../features/convert_feature2libsvm.sh xep_labeled_u30full_0
bash ../../features/convert_feature2libsvm.sh xeq_labeled_u30full_0
bash ../../features/convert_feature2libsvm.sh xer_labeled_u30full_0
bash ../../features/convert_feature2libsvm.sh xes_labeled_u30full_0
bash ../../features/convert_feature2libsvm.sh xet_labeled_u30full_0
bash ../../features/convert_feature2libsvm.sh xeu_labeled_u30full_0
bash ../../features/convert_feature2libsvm.sh xev_labeled_u30full_0
bash ../../features/convert_feature2libsvm.sh xew_labeled_u30full_0
bash ../../features/convert_feature2libsvm.sh xex_labeled_u30full_0
bash ../../features/convert_feature2libsvm.sh xey_labeled_u30full_0
bash ../../features/convert_feature2libsvm.sh xez_labeled_u30full_0
bash ../../features/convert_feature2libsvm.sh xfa_labeled_u30full_0
bash ../../features/convert_feature2libsvm.sh xfb_labeled_u30full_0
bash ../../features/convert_feature2libsvm.sh xfc_labeled_u30full_0
bash ../../features/convert_feature2libsvm.sh xfd_labeled_u30full_0
bash ../../features/convert_feature2libsvm.sh xfe_labeled_u30full_0
bash ../../features/convert_feature2libsvm.sh xff_labeled_u30full_0
bash ../../features/convert_feature2libsvm.sh xfg_labeled_u30full_0
bash ../../features/convert_feature2libsvm.sh xfh_labeled_u30full_0
bash ../../features/convert_feature2libsvm.sh xfi_labeled_u30full_0
bash ../../features/convert_feature2libsvm.sh xfj_labeled_u30full_0
bash ../../features/convert_feature2libsvm.sh xfk_labeled_u30full_0
bash ../../features/convert_feature2libsvm.sh xfl_labeled_u30full_0
bash ../../features/convert_feature2libsvm.sh xfm_labeled_u30full_0
bash ../../features/convert_feature2libsvm.sh xfn_labeled_u30full_0
bash ../../features/convert_feature2libsvm.sh xfo_labeled_u30full_0
bash ../../features/convert_feature2libsvm.sh xfp_labeled_u30full_0
bash ../../features/convert_feature2libsvm.sh xfq_labeled_u30full_0
bash ../../features/convert_feature2libsvm.sh xfr_labeled_u30full_0
bash ../../features/convert_feature2libsvm.sh xfs_labeled_u30full_0
bash ../../features/convert_feature2libsvm.sh xft_labeled_u30full_0
bash ../../features/convert_feature2libsvm.sh xfu_labeled_u30full_0
bash ../../features/convert_feature2libsvm.sh xfv_labeled_u30full_0
bash ../../features/convert_feature2libsvm.sh xfw_labeled_u30full_0
bash ../../features/convert_feature2libsvm.sh xfx_labeled_u30full_0
bash ../../features/convert_feature2libsvm.sh xfy_labeled_u30full_0
bash ../../features/convert_feature2libsvm.sh xfz_labeled_u30full_0
bash ../../features/convert_feature2libsvm.sh xga_labeled_u30full_0
bash ../../features/convert_feature2libsvm.sh xgb_labeled_u30full_0
bash ../../features/convert_feature2libsvm.sh xgc_labeled_u30full_0
bash ../../features/convert_feature2libsvm.sh xgd_labeled_u30full_0
bash ../../features/convert_feature2libsvm.sh xge_labeled_u30full_0
bash ../../features/convert_feature2libsvm.sh xgf_labeled_u30full_0
bash ../../features/convert_feature2libsvm.sh xgg_labeled_u30full_0
bash ../../features/convert_feature2libsvm.sh xgh_labeled_u30full_0
bash ../../features/convert_feature2libsvm.sh xgi_labeled_u30full_0
bash ../../features/convert_feature2libsvm.sh xgj_labeled_u30full_0
bash ../../features/convert_feature2libsvm.sh xgk_labeled_u30full_0
bash ../../features/convert_feature2libsvm.sh xgl_labeled_u30full_0
bash ../../features/convert_feature2libsvm.sh xgm_labeled_u30full_0
bash ../../features/convert_feature2libsvm.sh xgn_labeled_u30full_0
bash ../../features/convert_feature2libsvm.sh xgo_labeled_u30full_0
bash ../../features/convert_feature2libsvm.sh xgp_labeled_u30full_0
bash ../../features/convert_feature2libsvm.sh xgq_labeled_u30full_0
bash ../../features/convert_feature2libsvm.sh xgr_labeled_u30full_0
bash ../../features/convert_feature2libsvm.sh xgs_labeled_u30full_0
bash ../../features/convert_feature2libsvm.sh xgt_labeled_u30full_0
bash ../../features/convert_feature2libsvm.sh xgu_labeled_u30full_0
bash ../../features/convert_feature2libsvm.sh xgv_labeled_u30full_0
bash ../../features/convert_feature2libsvm.sh xgw_labeled_u30full_0
bash ../../features/convert_feature2libsvm.sh xgx_labeled_u30full_0
bash ../../features/convert_feature2libsvm.sh xgy_labeled_u30full_0
bash ../../features/convert_feature2libsvm.sh xgz_labeled_u30full_0
bash ../../features/convert_feature2libsvm.sh xha_labeled_u30full_0
bash ../../features/convert_feature2libsvm.sh xhb_labeled_u30full_0
bash ../../features/convert_feature2libsvm.sh xhc_labeled_u30full_0
bash ../../features/convert_feature2libsvm.sh xhd_labeled_u30full_0
bash ../../features/convert_feature2libsvm.sh xhe_labeled_u30full_0
bash ../../features/convert_feature2libsvm.sh xhf_labeled_u30full_0
bash ../../features/convert_feature2libsvm.sh xhg_labeled_u30full_0
bash ../../features/convert_feature2libsvm.sh xhh_labeled_u30full_0
bash ../../features/convert_feature2libsvm.sh xhi_labeled_u30full_0
bash ../../features/convert_feature2libsvm.sh xhj_labeled_u30full_0
bash ../../features/convert_feature2libsvm.sh xhk_labeled_u30full_0
bash ../../features/convert_feature2libsvm.sh xhl_labeled_u30full_0
bash ../../features/convert_feature2libsvm.sh xhm_labeled_u30full_0
bash ../../features/convert_feature2libsvm.sh xhn_labeled_u30full_0
bash ../../features/convert_feature2libsvm.sh xho_labeled_u30full_0
bash ../../features/convert_feature2libsvm.sh xhp_labeled_u30full_0
bash ../../features/convert_feature2libsvm.sh xhq_labeled_u30full_0
bash ../../features/convert_feature2libsvm.sh xhr_labeled_u30full_0
bash ../../features/convert_feature2libsvm.sh xhs_labeled_u30full_0
bash ../../features/convert_feature2libsvm.sh xht_labeled_u30full_0
